var annotated_dup =
[
    [ "dsp", "namespacedsp.html", "namespacedsp" ],
    [ "files", "namespacefiles.html", "namespacefiles" ],
    [ "hash", "namespacehash.html", "namespacehash" ],
    [ "locale", "namespacelocale.html", "namespacelocale" ],
    [ "math", "namespacemath.html", "namespacemath" ],
    [ "midi", "namespacemidi.html", "namespacemidi" ],
    [ "music", "namespacemusic.html", "namespacemusic" ],
    [ "std", null, [
      [ "hash< limes::files::DynamicLibrary >", "structstd_1_1hash_3_01limes_1_1files_1_1_dynamic_library_01_4.html", "structstd_1_1hash_3_01limes_1_1files_1_1_dynamic_library_01_4" ],
      [ "hash< limes::files::File >", "structstd_1_1hash_3_01limes_1_1files_1_1_file_01_4.html", "structstd_1_1hash_3_01limes_1_1files_1_1_file_01_4" ],
      [ "hash< limes::files::FilesystemEntry >", "structstd_1_1hash_3_01limes_1_1files_1_1_filesystem_entry_01_4.html", "structstd_1_1hash_3_01limes_1_1files_1_1_filesystem_entry_01_4" ],
      [ "hash< limes::RawData >", "structstd_1_1hash_3_01limes_1_1_raw_data_01_4.html", "structstd_1_1hash_3_01limes_1_1_raw_data_01_4" ],
      [ "hash< limes::Version >", "structstd_1_1hash_3_01limes_1_1_version_01_4.html", "structstd_1_1hash_3_01limes_1_1_version_01_4" ]
    ] ],
    [ "threads", "namespacethreads.html", "namespacethreads" ],
    [ "time", "namespacetime.html", "namespacetime" ],
    [ "typelist", "namespacetypelist.html", "namespacetypelist" ],
    [ "vecops", "namespacevecops.html", "namespacevecops" ],
    [ "AbstractFIFO", "class_abstract_f_i_f_o.html", "class_abstract_f_i_f_o" ],
    [ "aligned_pointer", "classaligned__pointer.html", "classaligned__pointer" ],
    [ "AlignedAllocator", "class_aligned_allocator.html", "class_aligned_allocator" ],
    [ "basic_vector", "classbasic__vector.html", "classbasic__vector" ],
    [ "CallDeferred", "class_call_deferred.html", "class_call_deferred" ],
    [ "Dimensions", "struct_dimensions.html", "struct_dimensions" ],
    [ "FIFO", "class_f_i_f_o.html", "class_f_i_f_o" ],
    [ "LinkedList", "class_linked_list.html", "class_linked_list" ],
    [ "LinkedListModel", "struct_linked_list_model.html", "struct_linked_list_model" ],
    [ "Matrix", "class_matrix.html", "class_matrix" ],
    [ "MemoryPool", "class_memory_pool.html", "class_memory_pool" ],
    [ "MemoryPoolAllocator", "class_memory_pool_allocator.html", "class_memory_pool_allocator" ],
    [ "MemoryPoolPointer", "class_memory_pool_pointer.html", "class_memory_pool_pointer" ],
    [ "OptionalObject", "class_optional_object.html", "class_optional_object" ],
    [ "owned_vector", "classowned__vector.html", "classowned__vector" ],
    [ "RAIICaller", "class_r_a_i_i_caller.html", "class_r_a_i_i_caller" ],
    [ "RawData", "class_raw_data.html", "class_raw_data" ],
    [ "ReferenceCountedObject", "class_reference_counted_object.html", "class_reference_counted_object" ],
    [ "ReferenceCountedObjectPtr", "class_reference_counted_object_ptr.html", "class_reference_counted_object_ptr" ],
    [ "scalar_vector", "classscalar__vector.html", "classscalar__vector" ],
    [ "ScopedStreamFlags", "struct_scoped_stream_flags.html", "struct_scoped_stream_flags" ],
    [ "SharedObject", "struct_shared_object.html", "struct_shared_object" ],
    [ "SharedObjectOwner", "struct_shared_object_owner.html", "struct_shared_object_owner" ],
    [ "stack_buffer", "classstack__buffer.html", "classstack__buffer" ],
    [ "StackAllocator", "class_stack_allocator.html", "class_stack_allocator" ],
    [ "TextTable", "class_text_table.html", "class_text_table" ],
    [ "Version", "struct_version.html", "struct_version" ]
];