Limes: MemoryPool Class Reference
MemoryPool Class Reference final
#include <MemoryPool.h>
Public Member Functions
MemoryPool (const MemoryPool &)=delete
MemoryPool (MemoryPool &&)=delete
MemoryPool (std::size_t storageSizeBytes, std::size_t chunkSize=32)
~MemoryPool ()
template<typename ObjectType >
ObjectType * allocate () noexcept
void * allocate (std::size_t numBytesToAllocate) noexcept
template<typename ObjectType , typename... Args>
ObjectType * construct (Args &&... constructorArgs) noexcept
template<typename ObjectType , typename... Args>
ObjectType & constructOrBust (Args &&... constructorArgs)
bool contains (void *ptr) const noexcept
template<typename ObjectType >
void deallocate (ObjectType *const object) noexcept
void deallocate (void *ptr, std::size_t numBytes) noexcept
template<typename ObjectType >
void destruct (ObjectType &object) noexcept
const void *const getMemoryRootLocation () const noexcept
template<typename ObjectType >
int getRemainingCapacity () const noexcept
std::size_t getRemainingSpace () const noexcept
template<typename ObjectType >
int getTotalCapacity () const noexcept
std::size_t getTotalSize () const noexcept
MemoryPool & operator= (const MemoryPool &)=delete
MemoryPool & operator= (MemoryPool &&)=delete
template<typename ObjectType >
bool owns (const ObjectType &object) const noexcept
Static Public Member Functions
template<typename ObjectType >
static std::unique_ptr< MemoryPool > createFor (std::size_t desiredCapacity)
Detailed Description
Definition at line 29 of file MemoryPool.h.
Constructor & Destructor Documentation
MemoryPool() [1/3]
MemoryPool::MemoryPool (std::size_t storageSizeBytes, std::size_t chunkSize = 32) explicit
~MemoryPool()
MemoryPool::~MemoryPool ()
MemoryPool() [2/3]
MemoryPool::MemoryPool (const MemoryPool &) delete
MemoryPool() [3/3]
MemoryPool::MemoryPool (MemoryPool &&) delete
Member Function Documentation
allocate() [1/2]
template<typename ObjectType > ObjectType * MemoryPool::allocate noexcept
Definition at line 160 of file MemoryPool.h.
allocate() [2/2]
void* MemoryPool::allocate (std::size_t numBytesToAllocate) noexcept
construct()
template<typename ObjectType , typename... Args> ObjectType * MemoryPool::construct (Args &&... constructorArgs) noexcept
Definition at line 166 of file MemoryPool.h.
Referenced by MemoryPoolPointer< ObjectType, AllowOverflowAllocation >::MemoryPoolPointer().
constructOrBust()
template<typename ObjectType , typename... Args> ObjectType & MemoryPool::constructOrBust (Args &&... constructorArgs)
Definition at line 184 of file MemoryPool.h.
Referenced by MemoryPoolPointer< ObjectType, AllowOverflowAllocation >::MemoryPoolPointer().
contains()
bool MemoryPool::contains (void * ptr) const noexcept
createFor()
template<typename ObjectType > static std::unique_ptr<MemoryPool> MemoryPool::createFor (std::size_t desiredCapacity) static
deallocate() [1/2]
template<typename ObjectType > void MemoryPool::deallocate (ObjectType *const object) noexcept
Definition at line 195 of file MemoryPool.h.
deallocate() [2/2]
void MemoryPool::deallocate (void * ptr, std::size_t numBytes) noexcept
destruct()
template<typename ObjectType > void MemoryPool::destruct (ObjectType & object) noexcept
Definition at line 201 of file MemoryPool.h.
getMemoryRootLocation()
const void* const MemoryPool::getMemoryRootLocation () const noexcept
getRemainingCapacity()
template<typename ObjectType > int MemoryPool::getRemainingCapacity noexcept
Definition at line 154 of file MemoryPool.h.
getRemainingSpace()
std::size_t MemoryPool::getRemainingSpace () const noexcept
getTotalCapacity()
template<typename ObjectType > int MemoryPool::getTotalCapacity noexcept
Definition at line 148 of file MemoryPool.h.
getTotalSize()
std::size_t MemoryPool::getTotalSize () const noexcept
operator=() [1/2]
MemoryPool& MemoryPool::operator= (const MemoryPool &) delete
operator=() [2/2]
MemoryPool& MemoryPool::operator= (MemoryPool &&) delete
owns()
template<typename ObjectType > bool MemoryPool::owns (const ObjectType & object) const noexcept
Definition at line 216 of file MemoryPool.h.
References alg::contains().
The documentation for this class was generated from the following file:
MemoryPool.h