Limes: FIFO< ObjectType > Class Template Reference
FIFO< ObjectType > Class Template Reference final
#include <FIFO.h>
Public Member Functions
FIFO (int initialSize)
int getCapacity () const noexcept
int getFreeSpace () const noexcept
LIMES_NON_COPYABLE (FIFO)
LIMES_NON_MOVABLE (FIFO)
int numStoredObjects () const noexcept
ObjectType pop ()
void pop (basic_vector< ObjectType > &output)
void pop (ObjectType *const data, int numObjects)
void push (const basic_vector< ObjectType > &data)
void push (const ObjectType *const data, int numObjects)
void push (ObjectType &&object)
void reset ()
void setCapacity (int newCapacity)
Detailed Description
template<typename ObjectType>
class FIFO< ObjectType >
Definition at line 25 of file FIFO.h.
Constructor & Destructor Documentation
FIFO()
template<typename ObjectType > FIFO< ObjectType >::FIFO (int initialSize) inline explicit
Definition at line 29 of file FIFO.h.
Member Function Documentation
getCapacity()
template<typename ObjectType > int FIFO< ObjectType >::getCapacity () const inline noexcept
Definition at line 38 of file FIFO.h.
getFreeSpace()
template<typename ObjectType > int FIFO< ObjectType >::getFreeSpace () const inline noexcept
Definition at line 43 of file FIFO.h.
LIMES_NON_COPYABLE()
template<typename ObjectType > FIFO< ObjectType >::LIMES_NON_COPYABLE (FIFO< ObjectType >)
LIMES_NON_MOVABLE()
template<typename ObjectType > FIFO< ObjectType >::LIMES_NON_MOVABLE (FIFO< ObjectType >)
numStoredObjects()
template<typename ObjectType > int FIFO< ObjectType >::numStoredObjects () const inline noexcept
Definition at line 48 of file FIFO.h.
pop() [1/3]
template<typename ObjectType > ObjectType FIFO< ObjectType >::pop () inline
Definition at line 97 of file FIFO.h.
References LIMES_ASSERT.
pop() [2/3]
template<typename ObjectType > void FIFO< ObjectType >::pop (basic_vector< ObjectType > & output) inline
Definition at line 128 of file FIFO.h.
References basic_vector< ElementType, Allocator >::capacity(), and basic_vector< ElementType, Allocator >::data().
pop() [3/3]
template<typename ObjectType > void FIFO< ObjectType >::pop (ObjectType *const data, int numObjects) inline
Definition at line 106 of file FIFO.h.
References LIMES_ASSERT.
push() [1/3]
template<typename ObjectType > void FIFO< ObjectType >::push (const basic_vector< ObjectType > & data) inline
Definition at line 92 of file FIFO.h.
References basic_vector< ElementType, Allocator >::data(), and basic_vector< ElementType, Allocator >::numObjects().
push() [2/3]
template<typename ObjectType > void FIFO< ObjectType >::push (const ObjectType *const data, int numObjects) inline
Definition at line 74 of file FIFO.h.
References LIMES_ASSERT.
push() [3/3]
template<typename ObjectType > void FIFO< ObjectType >::push (ObjectType && object) inline
Definition at line 65 of file FIFO.h.
References LIMES_ASSERT.
reset()
template<typename ObjectType > void FIFO< ObjectType >::reset () inline
Definition at line 53 of file FIFO.h.
setCapacity()
template<typename ObjectType > void FIFO< ObjectType >::setCapacity (int newCapacity) inline
Definition at line 59 of file FIFO.h.
The documentation for this class was generated from the following file:
FIFO.h