Limes: basic_vector< ElementType, Allocator > Class Template Reference
basic_vector< ElementType, Allocator > Class Template Reference
#include <basic_vector.h>
Public Types
using const_iterator = typename vector_type::const_iterator
using iterator = typename vector_type::iterator
using ObjectType = ElementType
using vector_type = std::vector< ElementType, Allocator >
Public Member Functions
basic_vector ()=default
template<typename OtherElementType , class UnaryOp >
basic_vector (const basic_vector< OtherElementType > &otherVector, UnaryOp &&transform)
basic_vector (const std::initializer_list< ElementType > &objs)
template<class AllocatorType >
basic_vector (const std::vector< ElementType, AllocatorType > &vectorToInitFrom)
virtual ~basic_vector ()=default
decltype(auto) begin () const noexcept
decltype(auto) begin () noexcept
constexpr int capacity () const noexcept
void clear ()
void clearAndFree ()
template<typename... Args>
void clearAndInit (int numObjectsToCreate, Args &&... args)
void clearAndInit (int numObjectsToCreate, const ElementType &objectToInitializeTo)
constexpr bool contains (const ElementType &object) const
template<class UnaryPredicate >
constexpr bool contains_if (UnaryPredicate &&pred) const
template<class OtherContainerType , class UnaryOp >
OtherContainerType createFromTransform (UnaryOp &&transform) const
const ElementType * data () const noexcept
ElementType * data () noexcept
template<typename... Args>
void emplace_back (Args &&... args)
decltype(auto) end () const noexcept
decltype(auto) end () noexcept
template<class UnaryOp >
void fillFromFunctor (int numElements, UnaryOp &&functor)
template<class UnaryPredicate >
constexpr ElementType * find_if (UnaryPredicate &&pred) const
ElementType & first ()
const ElementType & first () const
template<typename UnaryFunction >
constexpr void for_each (UnaryFunction &&func) const
bool isEmpty () const noexcept
bool isNotEmpty () const noexcept
ElementType & last ()
const ElementType & last () const
LIMES_DEFAULT_COPYABLE (basic_vector)
LIMES_DEFAULT_MOVABLE (basic_vector)
constexpr ElementType max () const
constexpr ElementType min () const
template<class UnaryPredicate >
constexpr int num_of (UnaryPredicate &&pred) const
constexpr int numObjects () const noexcept
bool operator!= (const basic_vector &other) const
template<class AllocatorType >
basic_vector & operator= (const std::vector< ElementType, AllocatorType > &otherVector)
basic_vector & operator= (std::initializer_list< ElementType > objs)
bool operator== (const basic_vector &other) const
ElementType & operator[] (int index)
const ElementType & operator[] (int index) const
void push_back (const ElementType &newObject)
constexpr void remove (const ElementType &toRemove)
constexpr void removeDuplicates ()
void reserve (int newSize)
template<typename... Args>
int reserveAndInit (int newSize, Args &&... args)
int reserveAndInit (int newSize, const ElementType &objectToInitializeTo)
constexpr void reverse ()
constexpr void sort (bool forward=true)
template<class OtherContainerType , class UnaryOp >
void transform (const OtherContainerType &otherContainer, UnaryOp &&transform)
template<typename OtherElementType , class UnaryOp >
basic_vector< OtherElementType > transformElementsTo (UnaryOp &&transform) const
template<class OtherContainer , class Callable >
void zip_with (const OtherContainer &other, Callable &&callable)
Protected Types
using size_type = typename vector_type::size_type
Protected Attributes
vector_type objects
Detailed Description
template<typename ElementType, class Allocator = std::allocator<ElementType>>
class basic_vector< ElementType, Allocator >
Definition at line 26 of file basic_vector.h.
Member Typedef Documentation
const_iterator
template<typename ElementType , class Allocator = std::allocator<ElementType>> using basic_vector< ElementType, Allocator >::const_iterator = typename vector_type::const_iterator
Definition at line 33 of file basic_vector.h.
iterator
template<typename ElementType , class Allocator = std::allocator<ElementType>> using basic_vector< ElementType, Allocator >::iterator = typename vector_type::iterator
Definition at line 32 of file basic_vector.h.
ObjectType
template<typename ElementType , class Allocator = std::allocator<ElementType>> using basic_vector< ElementType, Allocator >::ObjectType = ElementType
Definition at line 30 of file basic_vector.h.
size_type
template<typename ElementType , class Allocator = std::allocator<ElementType>> using basic_vector< ElementType, Allocator >::size_type = typename vector_type::size_type protected
Definition at line 334 of file basic_vector.h.
vector_type
template<typename ElementType , class Allocator = std::allocator<ElementType>> using basic_vector< ElementType, Allocator >::vector_type = std::vector<ElementType, Allocator>
Definition at line 31 of file basic_vector.h.
Constructor & Destructor Documentation
basic_vector() [1/4]
template<typename ElementType , class Allocator = std::allocator<ElementType>> basic_vector< ElementType, Allocator >::basic_vector () default
~basic_vector()
template<typename ElementType , class Allocator = std::allocator<ElementType>> virtual basic_vector< ElementType, Allocator >::~basic_vector () virtual default
basic_vector() [2/4]
template<typename ElementType , class Allocator = std::allocator<ElementType>> basic_vector< ElementType, Allocator >::basic_vector (const std::initializer_list< ElementType > & objs) inline
Definition at line 39 of file basic_vector.h.
basic_vector() [3/4]
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class AllocatorType > basic_vector< ElementType, Allocator >::basic_vector (const std::vector< ElementType, AllocatorType > & vectorToInitFrom) inline explicit
Definition at line 45 of file basic_vector.h.
basic_vector() [4/4]
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<typename OtherElementType , class UnaryOp > basic_vector< ElementType, Allocator >::basic_vector (const basic_vector< OtherElementType > & otherVector, UnaryOp && transform) inline explicit
Definition at line 51 of file basic_vector.h.
Member Function Documentation
begin() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> decltype(auto) basic_vector< ElementType, Allocator >::begin () const inline noexcept
Definition at line 157 of file basic_vector.h.
begin() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> decltype(auto) basic_vector< ElementType, Allocator >::begin () inline noexcept
Definition at line 147 of file basic_vector.h.
capacity()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr int basic_vector< ElementType, Allocator >::capacity () const inline constexpr noexcept
Definition at line 101 of file basic_vector.h.
Referenced by FIFO< ObjectType >::pop().
clear()
template<typename ElementType , class Allocator = std::allocator<ElementType>> void basic_vector< ElementType, Allocator >::clear () inline
Definition at line 198 of file basic_vector.h.
clearAndFree()
template<typename ElementType , class Allocator = std::allocator<ElementType>> void basic_vector< ElementType, Allocator >::clearAndFree () inline
Definition at line 220 of file basic_vector.h.
clearAndInit() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<typename... Args> void basic_vector< ElementType, Allocator >::clearAndInit (int numObjectsToCreate, Args &&... args) inline
Definition at line 204 of file basic_vector.h.
Referenced by scalar_vector< Sampletype >::clearAndZero().
clearAndInit() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> void basic_vector< ElementType, Allocator >::clearAndInit (int numObjectsToCreate, const ElementType & objectToInitializeTo) inline
Definition at line 212 of file basic_vector.h.
contains()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr bool basic_vector< ElementType, Allocator >::contains (const ElementType & object) const inline constexpr
Definition at line 78 of file basic_vector.h.
contains_if()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class UnaryPredicate > constexpr bool basic_vector< ElementType, Allocator >::contains_if (UnaryPredicate && pred) const inline constexpr
Definition at line 84 of file basic_vector.h.
createFromTransform()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class OtherContainerType , class UnaryOp > OtherContainerType basic_vector< ElementType, Allocator >::createFromTransform (UnaryOp && transform) const inline
Definition at line 298 of file basic_vector.h.
data() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> const ElementType* basic_vector< ElementType, Allocator >::data () const inline noexcept
Definition at line 325 of file basic_vector.h.
data() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> ElementType* basic_vector< ElementType, Allocator >::data () inline noexcept
Definition at line 320 of file basic_vector.h.
Referenced by FIFO< ObjectType >::pop(), and FIFO< ObjectType >::push().
emplace_back()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<typename... Args> void basic_vector< ElementType, Allocator >::emplace_back (Args &&... args) inline
Definition at line 173 of file basic_vector.h.
end() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> decltype(auto) basic_vector< ElementType, Allocator >::end () const inline noexcept
Definition at line 162 of file basic_vector.h.
end() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> decltype(auto) basic_vector< ElementType, Allocator >::end () inline noexcept
Definition at line 152 of file basic_vector.h.
fillFromFunctor()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class UnaryOp > void basic_vector< ElementType, Allocator >::fillFromFunctor (int numElements, UnaryOp && functor) inline
Definition at line 310 of file basic_vector.h.
find_if()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class UnaryPredicate > constexpr ElementType* basic_vector< ElementType, Allocator >::find_if (UnaryPredicate && pred) const inline constexpr
Definition at line 90 of file basic_vector.h.
first() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> ElementType& basic_vector< ElementType, Allocator >::first () inline
Definition at line 226 of file basic_vector.h.
first() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> const ElementType& basic_vector< ElementType, Allocator >::first () const inline
Definition at line 231 of file basic_vector.h.
for_each()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<typename UnaryFunction > constexpr void basic_vector< ElementType, Allocator >::for_each (UnaryFunction && func) const inline constexpr
Definition at line 73 of file basic_vector.h.
isEmpty()
template<typename ElementType , class Allocator = std::allocator<ElementType>> bool basic_vector< ElementType, Allocator >::isEmpty () const inline noexcept
Definition at line 178 of file basic_vector.h.
isNotEmpty()
template<typename ElementType , class Allocator = std::allocator<ElementType>> bool basic_vector< ElementType, Allocator >::isNotEmpty () const inline noexcept
Definition at line 183 of file basic_vector.h.
last() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> ElementType& basic_vector< ElementType, Allocator >::last () inline
Definition at line 236 of file basic_vector.h.
last() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> const ElementType& basic_vector< ElementType, Allocator >::last () const inline
Definition at line 241 of file basic_vector.h.
LIMES_DEFAULT_COPYABLE()
template<typename ElementType , class Allocator = std::allocator<ElementType>> basic_vector< ElementType, Allocator >::LIMES_DEFAULT_COPYABLE (basic_vector< ElementType, Allocator >)
LIMES_DEFAULT_MOVABLE()
template<typename ElementType , class Allocator = std::allocator<ElementType>> basic_vector< ElementType, Allocator >::LIMES_DEFAULT_MOVABLE (basic_vector< ElementType, Allocator >)
max()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr ElementType basic_vector< ElementType, Allocator >::max () const inline constexpr
Definition at line 137 of file basic_vector.h.
min()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr ElementType basic_vector< ElementType, Allocator >::min () const inline constexpr
Definition at line 142 of file basic_vector.h.
num_of()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class UnaryPredicate > constexpr int basic_vector< ElementType, Allocator >::num_of (UnaryPredicate && pred) const inline constexpr
Definition at line 96 of file basic_vector.h.
numObjects()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr int basic_vector< ElementType, Allocator >::numObjects () const inline constexpr noexcept
Definition at line 106 of file basic_vector.h.
Referenced by FIFO< ObjectType >::push().
operator!=()
template<typename ElementType , class Allocator = std::allocator<ElementType>> bool basic_vector< ElementType, Allocator >::operator!= (const basic_vector< ElementType, Allocator > & other) const inline
Definition at line 286 of file basic_vector.h.
operator=() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class AllocatorType > basic_vector& basic_vector< ElementType, Allocator >::operator= (const std::vector< ElementType, AllocatorType > & otherVector) inline
Definition at line 66 of file basic_vector.h.
operator=() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> basic_vector& basic_vector< ElementType, Allocator >::operator= (std::initializer_list< ElementType > objs) inline
Definition at line 59 of file basic_vector.h.
operator==()
template<typename ElementType , class Allocator = std::allocator<ElementType>> bool basic_vector< ElementType, Allocator >::operator== (const basic_vector< ElementType, Allocator > & other) const inline
Definition at line 281 of file basic_vector.h.
operator[]() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> ElementType& basic_vector< ElementType, Allocator >::operator[] (int index) inline
Definition at line 188 of file basic_vector.h.
operator[]() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> const ElementType& basic_vector< ElementType, Allocator >::operator[] (int index) const inline
Definition at line 193 of file basic_vector.h.
push_back()
template<typename ElementType , class Allocator = std::allocator<ElementType>> void basic_vector< ElementType, Allocator >::push_back (const ElementType & newObject) inline
Definition at line 167 of file basic_vector.h.
remove()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr void basic_vector< ElementType, Allocator >::remove (const ElementType & toRemove) inline constexpr
Definition at line 111 of file basic_vector.h.
removeDuplicates()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr void basic_vector< ElementType, Allocator >::removeDuplicates () inline constexpr
Definition at line 116 of file basic_vector.h.
reserve()
template<typename ElementType , class Allocator = std::allocator<ElementType>> void basic_vector< ElementType, Allocator >::reserve (int newSize) inline
Definition at line 246 of file basic_vector.h.
reserveAndInit() [1/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<typename... Args> int basic_vector< ElementType, Allocator >::reserveAndInit (int newSize, Args &&... args) inline
Definition at line 257 of file basic_vector.h.
Referenced by scalar_vector< Sampletype >::reserveAndZero().
reserveAndInit() [2/2]
template<typename ElementType , class Allocator = std::allocator<ElementType>> int basic_vector< ElementType, Allocator >::reserveAndInit (int newSize, const ElementType & objectToInitializeTo) inline
Definition at line 269 of file basic_vector.h.
reverse()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr void basic_vector< ElementType, Allocator >::reverse () inline constexpr
Definition at line 121 of file basic_vector.h.
sort()
template<typename ElementType , class Allocator = std::allocator<ElementType>> constexpr void basic_vector< ElementType, Allocator >::sort (bool forward = true) inline constexpr
Definition at line 126 of file basic_vector.h.
transform()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class OtherContainerType , class UnaryOp > void basic_vector< ElementType, Allocator >::transform (const OtherContainerType & otherContainer, UnaryOp && transform) inline
Definition at line 292 of file basic_vector.h.
transformElementsTo()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<typename OtherElementType , class UnaryOp > basic_vector<OtherElementType> basic_vector< ElementType, Allocator >::transformElementsTo (UnaryOp && transform) const inline
Definition at line 304 of file basic_vector.h.
zip_with()
template<typename ElementType , class Allocator = std::allocator<ElementType>> template<class OtherContainer , class Callable > void basic_vector< ElementType, Allocator >::zip_with (const OtherContainer & other, Callable && callable) inline
Definition at line 132 of file basic_vector.h.
Member Data Documentation
objects
template<typename ElementType , class Allocator = std::allocator<ElementType>> vector_type basic_vector< ElementType, Allocator >::objects protected
Definition at line 332 of file basic_vector.h.
Referenced by scalar_vector< Sampletype >::addFrom(), scalar_vector< Sampletype >::addTo(), scalar_vector< Sampletype >::copyFrom(), scalar_vector< Sampletype >::divideFrom(), scalar_vector< Sampletype >::divideTo(), scalar_vector< Sampletype >::multiplyFrom(), scalar_vector< Sampletype >::multiplyTo(), basic_vector< SampleType, std::allocator< SampleType > >::operator!=(), basic_vector< SampleType, std::allocator< SampleType > >::operator==(), scalar_vector< Sampletype >::subtractFrom(), and scalar_vector< Sampletype >::subtractTo().
The documentation for this class was generated from the following file:
basic_vector.h