Limes: time::Month Class Reference
time::Month Class Reference final
#include <month.h>
Public Types
enum Name : int {
Name::January = 1, Name::February, Name::March, Name::April,
Name::May, Name::June, Name::July, Name::August,
Name::September, Name::October, Name::November, Name::December
}
Public Member Functions
constexpr Month ()=default
constexpr Month (const Month &)=default
constexpr Month (const std::tm &timeObj) noexcept
constexpr Month (int number) noexcept
constexpr Month (Month &&)=default
constexpr Month (Name monthName) noexcept
Month (std::time_t time)
constexpr Name getMonthName () const noexcept
constexpr int getMonthNumber () const noexcept
constexpr int getNumDays (bool leapYear=false) const noexcept
constexpr int getNumWeeks (bool leapYear=false) const noexcept
constexpr std::string_view getString (bool useShort=false) const noexcept
constexpr bool operator!= (const Month &other) const noexcept
constexpr bool operator!= (Name other) const noexcept
constexpr Month operator+ (int numMonthsToAdd) const noexcept
constexpr Month & operator++ () noexcept
constexpr Month & operator++ (int) noexcept
constexpr Month & operator+= (int numMonthsToAdd) noexcept
constexpr Month operator- (int numMonthsToSubtract) const noexcept
constexpr Month & operator-- () noexcept
constexpr Month & operator-- (int) noexcept
constexpr Month & operator-= (int numMonthsToSubtract) noexcept
constexpr bool operator< (const Month &other) const noexcept
constexpr bool operator< (Name other) const noexcept
constexpr Month & operator= (const Month &)=default
constexpr Month & operator= (int newMonth) noexcept
constexpr Month & operator= (Month &&)=default
constexpr Month & operator= (Name newMonth) noexcept
constexpr bool operator== (const Month &other) const noexcept
constexpr bool operator== (Name other) const noexcept
constexpr bool operator> (const Month &other) const noexcept
constexpr bool operator> (Name other) const noexcept
Static Public Member Functions
static consteval Month getCompilationMonth () noexcept
static Month getCurrent ()
Detailed Description
Definition at line 26 of file month.h.
Member Enumeration Documentation
Name
enum time::Month::Name : int strong
Enumerator
January
February
March
April
May
June
July
August
September
October
November
December
Definition at line 30 of file month.h.
Constructor & Destructor Documentation
Month() [1/7]
constexpr time::Month::Month () constexpr default
Month() [2/7]
constexpr time::Month::Month (int number) explicit constexpr noexcept
Definition at line 25 of file month_impl.h.
References LIMES_ASSERT.
Month() [3/7]
constexpr time::Month::Month (Name monthName) explicit constexpr noexcept
Definition at line 31 of file month_impl.h.
Month() [4/7]
constexpr time::Month::Month (const std::tm & timeObj) explicit constexpr noexcept
Definition at line 58 of file month_impl.h.
Month() [5/7]
time::Month::Month (std::time_t time) explicit
Month() [6/7]
constexpr time::Month::Month (Month &&) constexpr default
Month() [7/7]
constexpr time::Month::Month (const Month &) constexpr default
Member Function Documentation
getCompilationMonth()
consteval Month time::Month::getCompilationMonth () static noexcept
Definition at line 188 of file month_impl.h.
References time::build_month().
getCurrent()
static Month time::Month::getCurrent () static
getMonthName()
constexpr Month::Name time::Month::getMonthName () const constexpr noexcept
Definition at line 53 of file month_impl.h.
getMonthNumber()
constexpr int time::Month::getMonthNumber () const constexpr noexcept
Definition at line 48 of file month_impl.h.
Referenced by time::Date::getDayOfYear(), and time::DateTime::getStdTime().
getNumDays()
constexpr int time::Month::getNumDays (bool leapYear = false) const constexpr noexcept
Definition at line 63 of file month_impl.h.
Referenced by time::Date::getDayOfYear(), and time::Weekday< StartWeekOnSunday >::Weekday().
getNumWeeks()
constexpr int time::Month::getNumWeeks (bool leapYear = false) const constexpr noexcept
Definition at line 79 of file month_impl.h.
References math::round().
getString()
constexpr std::string_view time::Month::getString (bool useShort = false) const constexpr noexcept
Definition at line 193 of file month_impl.h.
operator!=() [1/2]
constexpr bool time::Month::operator!= (const Month & other) const constexpr noexcept
Definition at line 173 of file month_impl.h.
operator!=() [2/2]
constexpr bool time::Month::operator!= (Name other) const constexpr noexcept
Definition at line 183 of file month_impl.h.
operator+()
constexpr Month time::Month::operator+ (int numMonthsToAdd) const constexpr noexcept
Definition at line 130 of file month_impl.h.
operator++() [1/2]
constexpr Month & time::Month::operator++ () constexpr noexcept
Definition at line 84 of file month_impl.h.
operator++() [2/2]
constexpr Month & time::Month::operator++ (int) constexpr noexcept
Definition at line 104 of file month_impl.h.
operator+=()
constexpr Month & time::Month::operator+= (int numMonthsToAdd) constexpr noexcept
Definition at line 114 of file month_impl.h.
operator-()
constexpr Month time::Month::operator- (int numMonthsToSubtract) const constexpr noexcept
Definition at line 139 of file month_impl.h.
operator--() [1/2]
constexpr Month & time::Month::operator-- () constexpr noexcept
Definition at line 94 of file month_impl.h.
operator--() [2/2]
constexpr Month & time::Month::operator-- (int) constexpr noexcept
Definition at line 109 of file month_impl.h.
operator-=()
constexpr Month & time::Month::operator-= (int numMonthsToSubtract) constexpr noexcept
Definition at line 122 of file month_impl.h.
operator<() [1/2]
constexpr bool time::Month::operator< (const Month & other) const constexpr noexcept
Definition at line 153 of file month_impl.h.
operator<() [2/2]
constexpr bool time::Month::operator< (Name other) const constexpr noexcept
Definition at line 163 of file month_impl.h.
operator=() [1/4]
constexpr Month& time::Month::operator= (const Month &) constexpr default
operator=() [2/4]
constexpr Month & time::Month::operator= (int newMonth) constexpr noexcept
Definition at line 42 of file month_impl.h.
operator=() [3/4]
constexpr Month& time::Month::operator= (Month &&) constexpr default
operator=() [4/4]
constexpr Month & time::Month::operator= (Name newMonth) constexpr noexcept
Definition at line 36 of file month_impl.h.
operator==() [1/2]
constexpr bool time::Month::operator== (const Month & other) const constexpr noexcept
Definition at line 168 of file month_impl.h.
operator==() [2/2]
constexpr bool time::Month::operator== (Name other) const constexpr noexcept
Definition at line 178 of file month_impl.h.
operator>() [1/2]
constexpr bool time::Month::operator> (const Month & other) const constexpr noexcept
Definition at line 148 of file month_impl.h.
operator>() [2/2]
constexpr bool time::Month::operator> (Name other) const constexpr noexcept
Definition at line 158 of file month_impl.h.
The documentation for this class was generated from the following files:
month.h
month_impl.h