Limes: time::Hour Class Reference
time::Hour Class Reference final
#include <hour.h>
Public Member Functions
constexpr Hour ()=default
constexpr Hour (const Hour &)=default
constexpr Hour (const std::tm &timeObj) noexcept
constexpr Hour (Hour &&)=default
constexpr Hour (int hourNumber, bool isAM) noexcept
constexpr Hour (int hoursSinceMidnight) noexcept
Hour (std::time_t time)
constexpr int getIn12HourFormat () const noexcept
constexpr int hoursSinceMidnight () const noexcept
constexpr bool isAM () const noexcept
constexpr bool isMidnight () const noexcept
constexpr bool isNoon () const noexcept
constexpr bool isPM () const noexcept
constexpr bool operator!= (const Hour &other) const noexcept
constexpr Hour operator+ (int hoursToAdd) const noexcept
constexpr Hour & operator++ () noexcept
constexpr Hour & operator+= (int hoursToAdd) noexcept
constexpr Hour operator- (int hoursToSubtract) const noexcept
constexpr Hour & operator-- () noexcept
constexpr Hour & operator-= (int hoursToSubtract) noexcept
constexpr bool operator< (const Hour &other) const noexcept
constexpr Hour & operator= (const Hour &)=default
constexpr Hour & operator= (Hour &&)=default
constexpr bool operator== (const Hour &other) const noexcept
constexpr bool operator> (const Hour &other) const noexcept
Static Public Member Functions
static consteval Hour getCompilationHour () noexcept
static Hour getCurrent ()
static constexpr Hour midnight () noexcept
static constexpr Hour noon () noexcept
Detailed Description
Definition at line 26 of file hour.h.
Constructor & Destructor Documentation
Hour() [1/7]
constexpr time::Hour::Hour () constexpr default
Hour() [2/7]
constexpr time::Hour::Hour (int hoursSinceMidnight) explicit constexpr noexcept
Definition at line 24 of file hour_impl.h.
References LIMES_ASSERT.
Hour() [3/7]
constexpr time::Hour::Hour (int hourNumber, bool isAM) explicit constexpr noexcept
Definition at line 30 of file hour_impl.h.
References LIMES_ASSERT.
Hour() [4/7]
constexpr time::Hour::Hour (const std::tm & timeObj) explicit constexpr noexcept
Definition at line 39 of file hour_impl.h.
Hour() [5/7]
time::Hour::Hour (std::time_t time) explicit
Hour() [6/7]
constexpr time::Hour::Hour (Hour &&) constexpr default
Hour() [7/7]
constexpr time::Hour::Hour (const Hour &) constexpr default
Member Function Documentation
getCompilationHour()
consteval Hour time::Hour::getCompilationHour () static noexcept
Definition at line 134 of file hour_impl.h.
References time::build_hour().
getCurrent()
static Hour time::Hour::getCurrent () static
getIn12HourFormat()
constexpr int time::Hour::getIn12HourFormat () const constexpr noexcept
Definition at line 69 of file hour_impl.h.
hoursSinceMidnight()
constexpr int time::Hour::hoursSinceMidnight () const constexpr noexcept
Definition at line 64 of file hour_impl.h.
isAM()
constexpr bool time::Hour::isAM () const constexpr noexcept
Definition at line 44 of file hour_impl.h.
Referenced by time::Time::isAM().
isMidnight()
constexpr bool time::Hour::isMidnight () const constexpr noexcept
Definition at line 59 of file hour_impl.h.
isNoon()
constexpr bool time::Hour::isNoon () const constexpr noexcept
Definition at line 54 of file hour_impl.h.
isPM()
constexpr bool time::Hour::isPM () const constexpr noexcept
Definition at line 49 of file hour_impl.h.
Referenced by time::Time::isPM().
midnight()
constexpr Hour time::Hour::midnight () static constexpr noexcept
Definition at line 144 of file hour_impl.h.
noon()
constexpr Hour time::Hour::noon () static constexpr noexcept
Definition at line 139 of file hour_impl.h.
operator!=()
constexpr bool time::Hour::operator!= (const Hour & other) const constexpr noexcept
Definition at line 129 of file hour_impl.h.
operator+()
constexpr Hour time::Hour::operator+ (int hoursToAdd) const constexpr noexcept
Definition at line 104 of file hour_impl.h.
operator++()
constexpr Hour & time::Hour::operator++ () constexpr noexcept
Definition at line 80 of file hour_impl.h.
operator+=()
constexpr Hour & time::Hour::operator+= (int hoursToAdd) constexpr noexcept
Definition at line 92 of file hour_impl.h.
operator-()
constexpr Hour time::Hour::operator- (int hoursToSubtract) const constexpr noexcept
Definition at line 109 of file hour_impl.h.
operator--()
constexpr Hour & time::Hour::operator-- () constexpr noexcept
Definition at line 86 of file hour_impl.h.
operator-=()
constexpr Hour & time::Hour::operator-= (int hoursToSubtract) constexpr noexcept
Definition at line 98 of file hour_impl.h.
operator<()
constexpr bool time::Hour::operator< (const Hour & other) const constexpr noexcept
Definition at line 119 of file hour_impl.h.
operator=() [1/2]
constexpr Hour& time::Hour::operator= (const Hour &) constexpr default
operator=() [2/2]
constexpr Hour& time::Hour::operator= (Hour &&) constexpr default
operator==()
constexpr bool time::Hour::operator== (const Hour & other) const constexpr noexcept
Definition at line 124 of file hour_impl.h.
operator>()
constexpr bool time::Hour::operator> (const Hour & other) const constexpr noexcept
Definition at line 114 of file hour_impl.h.
The documentation for this class was generated from the following files:
hour.h
hour_impl.h