Limes: LinkedList< ObjectType > Class Template Reference
LinkedList< ObjectType > Class Template Reference final
#include <LinkedList.h>
Classes
struct Node
Public Member Functions
LinkedList ()=default
Node & addNode (Node &newNode)
Node & addNodeAfter (Node &newNode, Node &nodeToInsertAfter)
Node & addNodeBefore (Node &newNode, Node &nodeToInsertBefore)
Node & addNodeToFront (Node &newNode)
template<typename... Args>
Node & createAndAddNode (Args &&... args)
template<typename... Args>
Node & createAndAddNodeAfter (Node &nodeToInsertAfter, Args &&... args)
template<typename... Args>
Node & createAndAddNodeBefore (Node &nodeToInsertBefore, Args &&... args)
template<typename... Args>
Node & createAndAddNodeToFront (Args &&... args)
Node * getFirstNodeInChain () const noexcept
Node * getLastNodeInChain () const noexcept
LIMES_DEFAULT_COPYABLE (LinkedList)
LIMES_DEFAULT_MOVABLE (LinkedList)
void removeNode (const Node &node)
void swapNodes (Node &node1, Node &node2)
Detailed Description
template<typename ObjectType>
class LinkedList< ObjectType >
Definition at line 23 of file LinkedList.h.
Constructor & Destructor Documentation
LinkedList()
template<typename ObjectType > LinkedList< ObjectType >::LinkedList () default
Member Function Documentation
addNode()
template<typename ObjectType > LinkedList< ObjectType >::Node & LinkedList< ObjectType >::addNode (Node & newNode)
Definition at line 47 of file LinkedList_impl.h.
References LinkedList< ObjectType >::Node::listNode.
Referenced by LinkedList< ObjectType >::createAndAddNode().
addNodeAfter()
template<typename ObjectType > LinkedList< ObjectType >::Node & LinkedList< ObjectType >::addNodeAfter (Node & newNode, Node & nodeToInsertAfter)
Definition at line 94 of file LinkedList_impl.h.
References LIMES_ASSERT.
Referenced by LinkedList< ObjectType >::createAndAddNodeAfter().
addNodeBefore()
template<typename ObjectType > LinkedList< ObjectType >::Node & LinkedList< ObjectType >::addNodeBefore (Node & newNode, Node & nodeToInsertBefore)
Definition at line 79 of file LinkedList_impl.h.
References LIMES_ASSERT.
Referenced by LinkedList< ObjectType >::createAndAddNodeBefore().
addNodeToFront()
template<typename ObjectType > LinkedList< ObjectType >::Node & LinkedList< ObjectType >::addNodeToFront (Node & newNode)
Definition at line 63 of file LinkedList_impl.h.
References LinkedList< ObjectType >::Node::listNode.
Referenced by LinkedList< ObjectType >::createAndAddNodeToFront().
createAndAddNode()
template<typename ObjectType > template<typename... Args> LinkedList< ObjectType >::Node & LinkedList< ObjectType >::createAndAddNode (Args &&... args)
Definition at line 57 of file LinkedList_impl.h.
References LinkedList< ObjectType >::addNode().
createAndAddNodeAfter()
template<typename ObjectType > template<typename... Args> LinkedList< ObjectType >::Node & LinkedList< ObjectType >::createAndAddNodeAfter (Node & nodeToInsertAfter, Args &&... args)
Definition at line 103 of file LinkedList_impl.h.
References LinkedList< ObjectType >::addNodeAfter().
createAndAddNodeBefore()
template<typename ObjectType > template<typename... Args> LinkedList< ObjectType >::Node & LinkedList< ObjectType >::createAndAddNodeBefore (Node & nodeToInsertBefore, Args &&... args)
Definition at line 88 of file LinkedList_impl.h.
References LinkedList< ObjectType >::addNodeBefore().
createAndAddNodeToFront()
template<typename ObjectType > template<typename... Args> LinkedList< ObjectType >::Node & LinkedList< ObjectType >::createAndAddNodeToFront (Args &&... args)
Definition at line 73 of file LinkedList_impl.h.
References LinkedList< ObjectType >::addNodeToFront().
getFirstNodeInChain()
template<typename ObjectType > LinkedList< ObjectType >::Node * LinkedList< ObjectType >::getFirstNodeInChain noexcept
Definition at line 29 of file LinkedList_impl.h.
getLastNodeInChain()
template<typename ObjectType > LinkedList< ObjectType >::Node * LinkedList< ObjectType >::getLastNodeInChain noexcept
Definition at line 38 of file LinkedList_impl.h.
LIMES_DEFAULT_COPYABLE()
template<typename ObjectType > LinkedList< ObjectType >::LIMES_DEFAULT_COPYABLE (LinkedList< ObjectType >)
LIMES_DEFAULT_MOVABLE()
template<typename ObjectType > LinkedList< ObjectType >::LIMES_DEFAULT_MOVABLE (LinkedList< ObjectType >)
removeNode()
template<typename ObjectType > void LinkedList< ObjectType >::removeNode (const Node & node)
Definition at line 118 of file LinkedList_impl.h.
References LIMES_ASSERT.
swapNodes()
template<typename ObjectType > void LinkedList< ObjectType >::swapNodes (Node & node1, Node & node2)
Definition at line 109 of file LinkedList_impl.h.
References LIMES_ASSERT, and LinkedList< ObjectType >::Node::listNode.
The documentation for this class was generated from the following files:
LinkedList.h
LinkedList_impl.h