Limes: memory::ReferenceCountedObjectPtr< ObjectType > Class Template Reference
memory::ReferenceCountedObjectPtr< ObjectType > Class Template Reference final
#include <ReferenceCountedObject.h>
Public Types
using ReferencedType = ObjectType
Public Member Functions
ReferenceCountedObjectPtr ()=default
Creates a pointer to a null object.
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr &other) noexcept
Copies another pointer.
template<typename Convertible >
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > &other) noexcept
Copies another pointer.
ReferenceCountedObjectPtr (ReferenceCountedObjectPtr &&other) noexcept
Takes-over the object from another pointer.
ReferenceCountedObjectPtr (ReferencedType &refCountedObject) noexcept
Creates a pointer to an object.
ReferenceCountedObjectPtr (ReferencedType *refCountedObject) noexcept
Creates a pointer to an object.
~ReferenceCountedObjectPtr ()
Destructor.
bool exists () const noexcept
ReferencedType * get () const noexcept
Returns the object that this pointer references.
operator bool () const noexcept
Checks whether this pointer is null.
bool operator!= (const ObjectType *other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator!= (const ReferenceCountedObjectPtr &other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator!= (decltype(nullptr)) const noexcept
Checks whether this pointer is null.
ReferencedType & operator* () const noexcept
Dereferences the object that this pointer references.
ReferencedType * operator-> () const noexcept
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr &other)
Changes this pointer to point at a different object.
template<typename Convertible >
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr< Convertible > &other)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr & operator= (decltype(nullptr))
Resets this pointer to a null pointer.
ReferenceCountedObjectPtr & operator= (ReferenceCountedObjectPtr &&other) noexcept
Takes-over the object from another pointer.
ReferenceCountedObjectPtr & operator= (ReferencedType &newObject)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr & operator= (ReferencedType *newObject)
Changes this pointer to point at a different object.
bool operator== (const ObjectType *other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator== (const ReferenceCountedObjectPtr &other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator== (decltype(nullptr)) const noexcept
Checks whether this pointer is null.
void reset () noexcept
Resets this object to a null pointer.
Detailed Description
template<meta::inherits_from< ReferenceCountedObject > ObjectType>
class memory::ReferenceCountedObjectPtr< ObjectType >
Definition at line 66 of file ReferenceCountedObject.h.
Member Typedef Documentation
ReferencedType
template<meta::inherits_from< ReferenceCountedObject > ObjectType> using memory::ReferenceCountedObjectPtr< ObjectType >::ReferencedType = ObjectType
Definition at line 70 of file ReferenceCountedObject.h.
Constructor & Destructor Documentation
ReferenceCountedObjectPtr() [1/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> memory::ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr () default
Creates a pointer to a null object.
ReferenceCountedObjectPtr() [2/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> memory::ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (ReferencedType * refCountedObject) inline explicit noexcept
Creates a pointer to an object.
This will increment the object's reference-count.
Definition at line 78 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [3/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> memory::ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (ReferencedType & refCountedObject) inline explicit noexcept
Creates a pointer to an object.
This will increment the object's reference-count.
Definition at line 87 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [4/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> memory::ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< ObjectType > & other) inline explicit noexcept
Copies another pointer.
This will increment the object's reference-count.
Definition at line 96 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [5/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> memory::ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (ReferenceCountedObjectPtr< ObjectType > && other) inline explicit noexcept
Takes-over the object from another pointer.
Definition at line 103 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [6/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> template<typename Convertible > memory::ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > & other) inline explicit noexcept
Copies another pointer.
This will increment the object's reference-count (if it is non-null).
Definition at line 113 of file ReferenceCountedObject.h.
~ReferenceCountedObjectPtr()
template<meta::inherits_from< ReferenceCountedObject > ObjectType> memory::ReferenceCountedObjectPtr< ObjectType >::~ReferenceCountedObjectPtr () inline
Destructor.
This will decrement the object's reference-count, which will cause the object to be deleted when the ref-count hits zero.
Definition at line 186 of file ReferenceCountedObject.h.
Member Function Documentation
exists()
template<meta::inherits_from< ReferenceCountedObject > ObjectType> bool memory::ReferenceCountedObjectPtr< ObjectType >::exists () const inline noexcept
Definition at line 197 of file ReferenceCountedObject.h.
get()
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferencedType* memory::ReferenceCountedObjectPtr< ObjectType >::get () const inline noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
Definition at line 195 of file ReferenceCountedObject.h.
Referenced by memory::ReferenceCountedObjectPtr< ObjectType >::operator=().
operator bool()
template<meta::inherits_from< ReferenceCountedObject > ObjectType> memory::ReferenceCountedObjectPtr< ObjectType >::operator bool () const inline explicit noexcept
Checks whether this pointer is null.
Definition at line 238 of file ReferenceCountedObject.h.
operator!=() [1/3]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> bool memory::ReferenceCountedObjectPtr< ObjectType >::operator!= (const ObjectType * other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 233 of file ReferenceCountedObject.h.
operator!=() [2/3]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> bool memory::ReferenceCountedObjectPtr< ObjectType >::operator!= (const ReferenceCountedObjectPtr< ObjectType > & other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 235 of file ReferenceCountedObject.h.
operator!=() [3/3]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> bool memory::ReferenceCountedObjectPtr< ObjectType >::operator!= (decltype(nullptr)) const inline noexcept
Checks whether this pointer is null.
Definition at line 226 of file ReferenceCountedObject.h.
operator*()
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferencedType& memory::ReferenceCountedObjectPtr< ObjectType >::operator* () const inline noexcept
Dereferences the object that this pointer references.
The pointer returned may be null, of course.
Definition at line 217 of file ReferenceCountedObject.h.
References LIMES_ASSERT.
operator->()
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferencedType* memory::ReferenceCountedObjectPtr< ObjectType >::operator-> () const inline noexcept
Definition at line 208 of file ReferenceCountedObject.h.
References LIMES_ASSERT.
operator=() [1/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& memory::ReferenceCountedObjectPtr< ObjectType >::operator= (const ReferenceCountedObjectPtr< ObjectType > & other) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 123 of file ReferenceCountedObject.h.
operator=() [2/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> template<typename Convertible > ReferenceCountedObjectPtr& memory::ReferenceCountedObjectPtr< ObjectType >::operator= (const ReferenceCountedObjectPtr< Convertible > & other) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 133 of file ReferenceCountedObject.h.
References memory::ReferenceCountedObjectPtr< ObjectType >::get().
operator=() [3/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& memory::ReferenceCountedObjectPtr< ObjectType >::operator= (decltype(nullptr)) inline
Resets this pointer to a null pointer.
Definition at line 169 of file ReferenceCountedObject.h.
operator=() [4/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& memory::ReferenceCountedObjectPtr< ObjectType >::operator= (ReferenceCountedObjectPtr< ObjectType > && other) inline noexcept
Takes-over the object from another pointer.
Definition at line 176 of file ReferenceCountedObject.h.
References vecops::swap().
operator=() [5/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& memory::ReferenceCountedObjectPtr< ObjectType >::operator= (ReferencedType & newObject) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 155 of file ReferenceCountedObject.h.
operator=() [6/6]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& memory::ReferenceCountedObjectPtr< ObjectType >::operator= (ReferencedType * newObject) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 142 of file ReferenceCountedObject.h.
operator==() [1/3]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> bool memory::ReferenceCountedObjectPtr< ObjectType >::operator== (const ObjectType * other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 229 of file ReferenceCountedObject.h.
operator==() [2/3]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> bool memory::ReferenceCountedObjectPtr< ObjectType >::operator== (const ReferenceCountedObjectPtr< ObjectType > & other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 231 of file ReferenceCountedObject.h.
operator==() [3/3]
template<meta::inherits_from< ReferenceCountedObject > ObjectType> bool memory::ReferenceCountedObjectPtr< ObjectType >::operator== (decltype(nullptr)) const inline noexcept
Checks whether this pointer is null.
Definition at line 224 of file ReferenceCountedObject.h.
reset()
template<meta::inherits_from< ReferenceCountedObject > ObjectType> void memory::ReferenceCountedObjectPtr< ObjectType >::reset () inline noexcept
Resets this object to a null pointer.
Definition at line 200 of file ReferenceCountedObject.h.
The documentation for this class was generated from the following file:
ReferenceCountedObject.h