Limes: ReferenceCountedObjectPtr< ObjectType > Class Template Reference
ReferenceCountedObjectPtr< ObjectType > Class Template Reference final
#include <ReferenceCountedObject.h>
Public Types
using ReferencedType = ObjectType
Public Member Functions
ReferenceCountedObjectPtr ()=default
Creates a pointer to a null object.
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr &other) noexcept
Copies another pointer.
template<typename Convertible >
ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > &other) noexcept
Copies another pointer.
ReferenceCountedObjectPtr (ReferenceCountedObjectPtr &&other) noexcept
Takes-over the object from another pointer.
ReferenceCountedObjectPtr (ReferencedType &refCountedObject) noexcept
Creates a pointer to an object.
ReferenceCountedObjectPtr (ReferencedType *refCountedObject) noexcept
Creates a pointer to an object.
~ReferenceCountedObjectPtr ()
Destructor.
bool exists () const noexcept
ReferencedType * get () const noexcept
Returns the object that this pointer references.
operator bool () const noexcept
Checks whether this pointer is null.
bool operator!= (const ObjectType *other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator!= (const ReferenceCountedObjectPtr &other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator!= (decltype(nullptr)) const noexcept
Checks whether this pointer is null.
ReferencedType & operator* () const noexcept
Dereferences the object that this pointer references.
ReferencedType * operator-> () const noexcept
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr &other)
Changes this pointer to point at a different object.
template<typename Convertible >
ReferenceCountedObjectPtr & operator= (const ReferenceCountedObjectPtr< Convertible > &other)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr & operator= (decltype(nullptr))
Resets this pointer to a null pointer.
ReferenceCountedObjectPtr & operator= (ReferenceCountedObjectPtr &&other) noexcept
Takes-over the object from another pointer.
ReferenceCountedObjectPtr & operator= (ReferencedType &newObject)
Changes this pointer to point at a different object.
ReferenceCountedObjectPtr & operator= (ReferencedType *newObject)
Changes this pointer to point at a different object.
bool operator== (const ObjectType *other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator== (const ReferenceCountedObjectPtr &other) const noexcept
Compares two ReferenceCountedObjectPtrs.
bool operator== (decltype(nullptr)) const noexcept
Checks whether this pointer is null.
void reset () noexcept
Resets this object to a null pointer.
Detailed Description
template<inherits_from< ReferenceCountedObject > ObjectType>
class ReferenceCountedObjectPtr< ObjectType >
Definition at line 63 of file ReferenceCountedObject.h.
Member Typedef Documentation
ReferencedType
template<inherits_from< ReferenceCountedObject > ObjectType> using ReferenceCountedObjectPtr< ObjectType >::ReferencedType = ObjectType
Definition at line 67 of file ReferenceCountedObject.h.
Constructor & Destructor Documentation
ReferenceCountedObjectPtr() [1/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr () default
Creates a pointer to a null object.
ReferenceCountedObjectPtr() [2/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (ReferencedType * refCountedObject) inline explicit noexcept
Creates a pointer to an object.
This will increment the object's reference-count.
Definition at line 75 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [3/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (ReferencedType & refCountedObject) inline explicit noexcept
Creates a pointer to an object.
This will increment the object's reference-count.
Definition at line 84 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [4/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< ObjectType > & other) inline explicit noexcept
Copies another pointer.
This will increment the object's reference-count.
Definition at line 93 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [5/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (ReferenceCountedObjectPtr< ObjectType > && other) inline explicit noexcept
Takes-over the object from another pointer.
Definition at line 100 of file ReferenceCountedObject.h.
ReferenceCountedObjectPtr() [6/6]
template<inherits_from< ReferenceCountedObject > ObjectType> template<typename Convertible > ReferenceCountedObjectPtr< ObjectType >::ReferenceCountedObjectPtr (const ReferenceCountedObjectPtr< Convertible > & other) inline explicit noexcept
Copies another pointer.
This will increment the object's reference-count (if it is non-null).
Definition at line 110 of file ReferenceCountedObject.h.
~ReferenceCountedObjectPtr()
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr< ObjectType >::~ReferenceCountedObjectPtr () inline
Destructor.
This will decrement the object's reference-count, which will cause the object to be deleted when the ref-count hits zero.
Definition at line 183 of file ReferenceCountedObject.h.
Member Function Documentation
exists()
template<inherits_from< ReferenceCountedObject > ObjectType> bool ReferenceCountedObjectPtr< ObjectType >::exists () const inline noexcept
Definition at line 194 of file ReferenceCountedObject.h.
get()
template<inherits_from< ReferenceCountedObject > ObjectType> ReferencedType* ReferenceCountedObjectPtr< ObjectType >::get () const inline noexcept
Returns the object that this pointer references.
The pointer returned may be null, of course.
Definition at line 192 of file ReferenceCountedObject.h.
Referenced by ReferenceCountedObjectPtr< ObjectType >::operator=().
operator bool()
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr< ObjectType >::operator bool () const inline explicit noexcept
Checks whether this pointer is null.
Definition at line 235 of file ReferenceCountedObject.h.
operator!=() [1/3]
template<inherits_from< ReferenceCountedObject > ObjectType> bool ReferenceCountedObjectPtr< ObjectType >::operator!= (const ObjectType * other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 230 of file ReferenceCountedObject.h.
operator!=() [2/3]
template<inherits_from< ReferenceCountedObject > ObjectType> bool ReferenceCountedObjectPtr< ObjectType >::operator!= (const ReferenceCountedObjectPtr< ObjectType > & other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 232 of file ReferenceCountedObject.h.
operator!=() [3/3]
template<inherits_from< ReferenceCountedObject > ObjectType> bool ReferenceCountedObjectPtr< ObjectType >::operator!= (decltype(nullptr)) const inline noexcept
Checks whether this pointer is null.
Definition at line 223 of file ReferenceCountedObject.h.
operator*()
template<inherits_from< ReferenceCountedObject > ObjectType> ReferencedType& ReferenceCountedObjectPtr< ObjectType >::operator* () const inline noexcept
Dereferences the object that this pointer references.
The pointer returned may be null, of course.
Definition at line 214 of file ReferenceCountedObject.h.
References LIMES_ASSERT.
operator->()
template<inherits_from< ReferenceCountedObject > ObjectType> ReferencedType* ReferenceCountedObjectPtr< ObjectType >::operator-> () const inline noexcept
Definition at line 205 of file ReferenceCountedObject.h.
References LIMES_ASSERT.
operator=() [1/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ObjectType >::operator= (const ReferenceCountedObjectPtr< ObjectType > & other) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 120 of file ReferenceCountedObject.h.
operator=() [2/6]
template<inherits_from< ReferenceCountedObject > ObjectType> template<typename Convertible > ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ObjectType >::operator= (const ReferenceCountedObjectPtr< Convertible > & other) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 130 of file ReferenceCountedObject.h.
References ReferenceCountedObjectPtr< ObjectType >::get().
operator=() [3/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ObjectType >::operator= (decltype(nullptr)) inline
Resets this pointer to a null pointer.
Definition at line 166 of file ReferenceCountedObject.h.
operator=() [4/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ObjectType >::operator= (ReferenceCountedObjectPtr< ObjectType > && other) inline noexcept
Takes-over the object from another pointer.
Definition at line 173 of file ReferenceCountedObject.h.
References vecops::swap().
operator=() [5/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ObjectType >::operator= (ReferencedType & newObject) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 152 of file ReferenceCountedObject.h.
operator=() [6/6]
template<inherits_from< ReferenceCountedObject > ObjectType> ReferenceCountedObjectPtr& ReferenceCountedObjectPtr< ObjectType >::operator= (ReferencedType * newObject) inline
Changes this pointer to point at a different object.
The reference count of the old object is decremented, and it might be deleted if it hits zero. The new object's count is incremented.
Definition at line 139 of file ReferenceCountedObject.h.
operator==() [1/3]
template<inherits_from< ReferenceCountedObject > ObjectType> bool ReferenceCountedObjectPtr< ObjectType >::operator== (const ObjectType * other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 226 of file ReferenceCountedObject.h.
operator==() [2/3]
template<inherits_from< ReferenceCountedObject > ObjectType> bool ReferenceCountedObjectPtr< ObjectType >::operator== (const ReferenceCountedObjectPtr< ObjectType > & other) const inline noexcept
Compares two ReferenceCountedObjectPtrs.
Definition at line 228 of file ReferenceCountedObject.h.
operator==() [3/3]
template<inherits_from< ReferenceCountedObject > ObjectType> bool ReferenceCountedObjectPtr< ObjectType >::operator== (decltype(nullptr)) const inline noexcept
Checks whether this pointer is null.
Definition at line 221 of file ReferenceCountedObject.h.
reset()
template<inherits_from< ReferenceCountedObject > ObjectType> void ReferenceCountedObjectPtr< ObjectType >::reset () inline noexcept
Resets this object to a null pointer.
Definition at line 197 of file ReferenceCountedObject.h.
The documentation for this class was generated from the following file:
ReferenceCountedObject.h