Limes: time::Time Class Reference
time::Time Class Reference final
#include <time.h>
Public Member Functions
constexpr Time ()=default
constexpr Time (const Hour &h, int min, int sec) noexcept
template<Clock ClockType>
Time (const Point< ClockType > &timePoint)
constexpr Time (const std::tm &timeObj) noexcept
constexpr Time (const Time &)=default
constexpr Time (int hourIn24HourFormat, int min, int sec) noexcept
Time (std::time_t time)
constexpr Time (Time &&)=default
constexpr Hour getHour () const noexcept
constexpr int getMinute () const noexcept
constexpr int getSecond () const noexcept
constexpr bool isAfter (const Time &other) const noexcept
constexpr bool isAM () const noexcept
constexpr bool isBefore (const Time &other) const noexcept
bool isInFuture () const noexcept
bool isInPast () const noexcept
constexpr bool isOnTheHour () const noexcept
constexpr bool isPM () const noexcept
constexpr bool operator!= (const Time &other) const noexcept
constexpr bool operator< (const Time &other) const noexcept
constexpr Time & operator= (const Time &)=default
constexpr Time & operator= (Time &&)=default
constexpr bool operator== (const Time &other) const noexcept
constexpr bool operator> (const Time &other) const noexcept
std::string toString (bool as24HourTime=true) const
Static Public Member Functions
static consteval Time getCompilationTime () noexcept
static Time getCurrent ()
Detailed Description
Definition at line 29 of file time.h.
Constructor & Destructor Documentation
Time() [1/8]
constexpr time::Time::Time () constexpr default
Time() [2/8]
constexpr time::Time::Time (const Hour & h, int min, int sec) explicit constexpr noexcept
Definition at line 23 of file time_impl.h.
Time() [3/8]
constexpr time::Time::Time (int hourIn24HourFormat, int min, int sec) explicit constexpr noexcept
Definition at line 30 of file time_impl.h.
Time() [4/8]
constexpr time::Time::Time (const std::tm & timeObj) explicit constexpr noexcept
Definition at line 37 of file time_impl.h.
Time() [5/8]
time::Time::Time (std::time_t time) explicit
Time() [6/8]
template<Clock ClockType> time::Time::Time (const Point< ClockType > & timePoint) explicit
Definition at line 43 of file time_impl.h.
Time() [7/8]
constexpr time::Time::Time (Time &&) constexpr default
Time() [8/8]
constexpr time::Time::Time (const Time &) constexpr default
Member Function Documentation
getCompilationTime()
consteval Time time::Time::getCompilationTime () static noexcept
Definition at line 120 of file time_impl.h.
References time::build_hour(), time::build_minute(), and time::build_second().
Referenced by time::DateTime::getCompilation().
getCurrent()
static Time time::Time::getCurrent () static
getHour()
constexpr Hour time::Time::getHour () const constexpr noexcept
Definition at line 63 of file time_impl.h.
getMinute()
constexpr int time::Time::getMinute () const constexpr noexcept
Definition at line 68 of file time_impl.h.
getSecond()
constexpr int time::Time::getSecond () const constexpr noexcept
Definition at line 73 of file time_impl.h.
isAfter()
constexpr bool time::Time::isAfter (const Time & other) const constexpr noexcept
Definition at line 89 of file time_impl.h.
isAM()
constexpr bool time::Time::isAM () const constexpr noexcept
Definition at line 48 of file time_impl.h.
References time::Hour::isAM().
isBefore()
constexpr bool time::Time::isBefore (const Time & other) const constexpr noexcept
Definition at line 78 of file time_impl.h.
isInFuture()
bool time::Time::isInFuture () const noexcept
isInPast()
bool time::Time::isInPast () const noexcept
isOnTheHour()
constexpr bool time::Time::isOnTheHour () const constexpr noexcept
Definition at line 58 of file time_impl.h.
isPM()
constexpr bool time::Time::isPM () const constexpr noexcept
Definition at line 53 of file time_impl.h.
References time::Hour::isPM().
operator!=()
constexpr bool time::Time::operator!= (const Time & other) const constexpr noexcept
Definition at line 115 of file time_impl.h.
operator<()
constexpr bool time::Time::operator< (const Time & other) const constexpr noexcept
Definition at line 105 of file time_impl.h.
operator=() [1/2]
constexpr Time& time::Time::operator= (const Time &) constexpr default
operator=() [2/2]
constexpr Time& time::Time::operator= (Time &&) constexpr default
operator==()
constexpr bool time::Time::operator== (const Time & other) const constexpr noexcept
Definition at line 110 of file time_impl.h.
operator>()
constexpr bool time::Time::operator> (const Time & other) const constexpr noexcept
Definition at line 100 of file time_impl.h.
toString()
std::string time::Time::toString (bool as24HourTime = true) const
The documentation for this class was generated from the following files:
time.h
time_impl.h