Limes: time::Weekday< StartWeekOnSunday > Class Template Reference
time::Weekday< StartWeekOnSunday > Class Template Reference final
#include <weekday.h>
Public Types
enum Name : int {
Name::Sunday = 0, Name::Monday, Name::Tuesday, Name::Wednesday,
Name::Thursday, Name::Friday, Name::Saturday
}
using OtherWeekdayType = Weekday<! StartWeekOnSunday >
Public Member Functions
constexpr Weekday ()=default
constexpr Weekday (const OtherWeekdayType &other) noexcept
constexpr Weekday (const std::tm &timeObj) noexcept
constexpr Weekday (const Weekday &)=default
constexpr Weekday (const Weekday< false > &other) noexcept
constexpr Weekday (const Weekday< true > &other) noexcept
constexpr Weekday (const Year &year, const Month &month, int day) noexcept
constexpr Weekday (int daysSinceStartOfWeek) noexcept
constexpr Weekday (int year, int month, int day) noexcept
constexpr Weekday (Name day) noexcept
Weekday (std::time_t time)
constexpr Weekday (Weekday &&)=default
constexpr int daysSinceStartOfWeek () const noexcept
constexpr std::string_view getString (bool useShort=false) const noexcept
constexpr Name getWeekdayName () const noexcept
constexpr bool isWeekday () const noexcept
constexpr bool isWeekend () const noexcept
constexpr bool operator!= (const OtherWeekdayType &other) const noexcept
constexpr bool operator!= (const Weekday &other) const noexcept
constexpr Weekday operator+ (int numDaysToAdd) const noexcept
constexpr Weekday & operator++ () noexcept
constexpr Weekday & operator+= (int numDaysToAdd) noexcept
constexpr Weekday operator- (int numDaysToSubtract) const noexcept
constexpr Weekday & operator-- () noexcept
constexpr Weekday & operator-= (int numDaysToSubtract) noexcept
constexpr bool operator< (const OtherWeekdayType &other) const noexcept
constexpr bool operator< (const Weekday &other) const noexcept
constexpr bool operator< (const Weekday< false > &other) const noexcept
constexpr bool operator< (const Weekday< true > &other) const noexcept
constexpr Weekday & operator= (const Weekday &)=default
constexpr Weekday & operator= (Weekday &&)=default
constexpr bool operator== (const OtherWeekdayType &other) const noexcept
constexpr bool operator== (const Weekday &other) const noexcept
constexpr bool operator== (const Weekday< false > &other) const noexcept
constexpr bool operator== (const Weekday< true > &other) const noexcept
constexpr bool operator> (const OtherWeekdayType &other) const noexcept
constexpr bool operator> (const Weekday &other) const noexcept
constexpr bool operator> (const Weekday< false > &other) const noexcept
constexpr bool operator> (const Weekday< true > &other) const noexcept
constexpr OtherWeekdayType toOtherWeekdayType () const noexcept
Static Public Member Functions
static consteval Weekday getCompilationWeekday () noexcept
static Weekday getCurrent ()
static consteval bool startsWeekOnSunday () noexcept
Detailed Description
template<bool StartWeekOnSunday = false>
class time::Weekday< StartWeekOnSunday >
Definition at line 31 of file weekday.h.
Member Typedef Documentation
OtherWeekdayType
template<bool StartWeekOnSunday = false> using time::Weekday< StartWeekOnSunday >::OtherWeekdayType = Weekday<! StartWeekOnSunday>
Definition at line 60 of file weekday.h.
Member Enumeration Documentation
Name
template<bool StartWeekOnSunday = false> enum time::Weekday::Name : int strong
Enumerator
Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Definition at line 35 of file weekday.h.
Constructor & Destructor Documentation
Weekday() [1/12]
template<bool StartWeekOnSunday = false> constexpr time::Weekday< StartWeekOnSunday >::Weekday () constexpr default
Weekday() [2/12]
template<bool StartWeekOnSunday> constexpr time::Weekday< StartWeekOnSunday >::Weekday (int daysSinceStartOfWeek) explicit constexpr noexcept
Definition at line 25 of file weekday_impl.h.
Weekday() [3/12]
template<bool StartWeekOnSunday> constexpr time::Weekday< StartWeekOnSunday >::Weekday (int year, int month, int day) explicit constexpr noexcept
Definition at line 32 of file weekday_impl.h.
References time::Month::getNumDays(), time::Year::isLeap(), and LIMES_ASSERT.
Weekday() [4/12]
template<bool StartWeekOnSunday> constexpr time::Weekday< StartWeekOnSunday >::Weekday (const Year & year, const Month & month, int day) explicit constexpr noexcept
Definition at line 51 of file weekday_impl.h.
Weekday() [5/12]
template<bool StartWeekOnSunday> constexpr time::Weekday< StartWeekOnSunday >::Weekday (Name day) explicit constexpr noexcept
Definition at line 57 of file weekday_impl.h.
Weekday() [6/12]
template<bool StartWeekOnSunday> constexpr time::Weekday< StartWeekOnSunday >::Weekday (const std::tm & timeObj) explicit constexpr noexcept
Definition at line 77 of file weekday_impl.h.
Weekday() [7/12]
template<bool StartWeekOnSunday = false> time::Weekday< StartWeekOnSunday >::Weekday (std::time_t time) explicit
Weekday() [8/12]
template<bool StartWeekOnSunday = false> constexpr time::Weekday< StartWeekOnSunday >::Weekday (const OtherWeekdayType & other) explicit constexpr noexcept
Weekday() [9/12]
template<bool StartWeekOnSunday = false> constexpr time::Weekday< StartWeekOnSunday >::Weekday (Weekday< StartWeekOnSunday > &&) constexpr default
Weekday() [10/12]
template<bool StartWeekOnSunday = false> constexpr time::Weekday< StartWeekOnSunday >::Weekday (const Weekday< StartWeekOnSunday > &) constexpr default
Weekday() [11/12]
constexpr time::Weekday< true >::Weekday (const Weekday< false > & other) constexpr noexcept
Definition at line 65 of file weekday_impl.h.
Weekday() [12/12]
constexpr time::Weekday< false >::Weekday (const Weekday< true > & other) constexpr noexcept
Definition at line 71 of file weekday_impl.h.
Member Function Documentation
daysSinceStartOfWeek()
template<bool StartWeekOnSunday> constexpr int time::Weekday< StartWeekOnSunday >::daysSinceStartOfWeek constexpr noexcept
Definition at line 94 of file weekday_impl.h.
getCompilationWeekday()
template<bool StartWeekOnSunday> consteval Weekday< StartWeekOnSunday > time::Weekday< StartWeekOnSunday >::getCompilationWeekday static noexcept
Definition at line 250 of file weekday_impl.h.
References time::build_day(), time::build_month(), and time::build_year().
getCurrent()
template<bool StartWeekOnSunday = false> static Weekday time::Weekday< StartWeekOnSunday >::getCurrent () static
getString()
template<bool StartWeekOnSunday> constexpr std::string_view time::Weekday< StartWeekOnSunday >::getString (bool useShort = false) const constexpr noexcept
Definition at line 220 of file weekday_impl.h.
getWeekdayName()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday >::Name time::Weekday< StartWeekOnSunday >::getWeekdayName constexpr noexcept
Definition at line 85 of file weekday_impl.h.
isWeekday()
template<bool StartWeekOnSunday> constexpr bool time::Weekday< StartWeekOnSunday >::isWeekday constexpr noexcept
Definition at line 214 of file weekday_impl.h.
isWeekend()
template<bool StartWeekOnSunday> constexpr bool time::Weekday< StartWeekOnSunday >::isWeekend constexpr noexcept
Definition at line 206 of file weekday_impl.h.
operator!=() [1/2]
template<bool StartWeekOnSunday> constexpr bool time::Weekday< StartWeekOnSunday >::operator!= (const OtherWeekdayType & other) const constexpr noexcept
Definition at line 200 of file weekday_impl.h.
operator!=() [2/2]
template<bool StartWeekOnSunday> constexpr bool time::Weekday< StartWeekOnSunday >::operator!= (const Weekday< StartWeekOnSunday > & other) const constexpr noexcept
Definition at line 182 of file weekday_impl.h.
operator+()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday > time::Weekday< StartWeekOnSunday >::operator+ (int numDaysToAdd) const constexpr noexcept
Definition at line 128 of file weekday_impl.h.
operator++()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday > & time::Weekday< StartWeekOnSunday >::operator++ constexpr noexcept
Definition at line 100 of file weekday_impl.h.
operator+=()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday > & time::Weekday< StartWeekOnSunday >::operator+= (int numDaysToAdd) constexpr noexcept
Definition at line 114 of file weekday_impl.h.
operator-()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday > time::Weekday< StartWeekOnSunday >::operator- (int numDaysToSubtract) const constexpr noexcept
Definition at line 134 of file weekday_impl.h.
operator--()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday > & time::Weekday< StartWeekOnSunday >::operator-- constexpr noexcept
Definition at line 107 of file weekday_impl.h.
operator-=()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday > & time::Weekday< StartWeekOnSunday >::operator-= (int numDaysToSubtract) constexpr noexcept
Definition at line 121 of file weekday_impl.h.
operator<() [1/4]
template<bool StartWeekOnSunday = false> constexpr bool time::Weekday< StartWeekOnSunday >::operator< (const OtherWeekdayType & other) const constexpr noexcept
operator<() [2/4]
template<bool StartWeekOnSunday> constexpr bool time::Weekday< StartWeekOnSunday >::operator< (const Weekday< StartWeekOnSunday > & other) const constexpr noexcept
Definition at line 146 of file weekday_impl.h.
operator<() [3/4]
constexpr bool time::Weekday< true >::operator< (const Weekday< false > & other) const constexpr noexcept
Definition at line 152 of file weekday_impl.h.
operator<() [4/4]
constexpr bool time::Weekday< false >::operator< (const Weekday< true > & other) const constexpr noexcept
Definition at line 158 of file weekday_impl.h.
operator=() [1/2]
template<bool StartWeekOnSunday = false> constexpr Weekday& time::Weekday< StartWeekOnSunday >::operator= (const Weekday< StartWeekOnSunday > &) constexpr default
operator=() [2/2]
template<bool StartWeekOnSunday = false> constexpr Weekday& time::Weekday< StartWeekOnSunday >::operator= (Weekday< StartWeekOnSunday > &&) constexpr default
operator==() [1/4]
template<bool StartWeekOnSunday = false> constexpr bool time::Weekday< StartWeekOnSunday >::operator== (const OtherWeekdayType & other) const constexpr noexcept
operator==() [2/4]
template<bool StartWeekOnSunday> constexpr bool time::Weekday< StartWeekOnSunday >::operator== (const Weekday< StartWeekOnSunday > & other) const constexpr noexcept
Definition at line 176 of file weekday_impl.h.
operator==() [3/4]
constexpr bool time::Weekday< true >::operator== (const Weekday< false > & other) const constexpr noexcept
Definition at line 188 of file weekday_impl.h.
operator==() [4/4]
constexpr bool time::Weekday< false >::operator== (const Weekday< true > & other) const constexpr noexcept
Definition at line 194 of file weekday_impl.h.
operator>() [1/4]
template<bool StartWeekOnSunday = false> constexpr bool time::Weekday< StartWeekOnSunday >::operator> (const OtherWeekdayType & other) const constexpr noexcept
operator>() [2/4]
template<bool StartWeekOnSunday> constexpr bool time::Weekday< StartWeekOnSunday >::operator> (const Weekday< StartWeekOnSunday > & other) const constexpr noexcept
Definition at line 140 of file weekday_impl.h.
operator>() [3/4]
constexpr bool time::Weekday< true >::operator> (const Weekday< false > & other) const constexpr noexcept
Definition at line 164 of file weekday_impl.h.
operator>() [4/4]
constexpr bool time::Weekday< false >::operator> (const Weekday< true > & other) const constexpr noexcept
Definition at line 170 of file weekday_impl.h.
startsWeekOnSunday()
template<bool StartWeekOnSunday> consteval bool time::Weekday< StartWeekOnSunday >::startsWeekOnSunday static noexcept
Definition at line 256 of file weekday_impl.h.
toOtherWeekdayType()
template<bool StartWeekOnSunday> constexpr Weekday< StartWeekOnSunday >::OtherWeekdayType time::Weekday< StartWeekOnSunday >::toOtherWeekdayType constexpr noexcept
Definition at line 241 of file weekday_impl.h.
The documentation for this class was generated from the following files:
weekday.h
weekday_impl.h