Limes: time::Year Class Reference
time::Year Class Reference final
#include <year.h>
Public Member Functions
constexpr Year ()=default
constexpr Year (const std::tm &timeObj) noexcept
constexpr Year (const Year &)=default
constexpr Year (int yearNumber) noexcept
Year (std::time_t time)
constexpr Year (Year &&)=default
constexpr int getNumDays () const noexcept
int getNumWeeks () const noexcept
constexpr int getYear () const noexcept
constexpr bool isBC () const noexcept
bool isInFuture () const noexcept
bool isInPast () const noexcept
constexpr bool isLeap () const noexcept
constexpr operator int () const noexcept
constexpr bool operator!= (const Year &other) const noexcept
constexpr Year operator+ (int numYearsToAdd) const noexcept
constexpr Year & operator++ () noexcept
constexpr Year & operator+= (int numYearsToAdd) noexcept
constexpr Year operator- (int numYearsToSubtract) const noexcept
constexpr Year & operator-- () noexcept
constexpr Year & operator-= (int numYearsToSubtract) noexcept
constexpr bool operator< (const Year &other) const noexcept
constexpr Year & operator= (const Year &)=default
constexpr Year & operator= (int newYear) noexcept
constexpr Year & operator= (Year &&)=default
constexpr bool operator== (const Year &other) const noexcept
constexpr bool operator> (const Year &other) const noexcept
Static Public Member Functions
static consteval Year getCompilationYear () noexcept
static Year getCurrent ()
Detailed Description
Definition at line 26 of file year.h.
Constructor & Destructor Documentation
Year() [1/6]
constexpr time::Year::Year () constexpr default
Year() [2/6]
constexpr time::Year::Year (int yearNumber) explicit constexpr noexcept
Definition at line 24 of file year_impl.h.
Year() [3/6]
constexpr time::Year::Year (const std::tm & timeObj) explicit constexpr noexcept
Definition at line 29 of file year_impl.h.
Year() [4/6]
time::Year::Year (std::time_t time) explicit
Year() [5/6]
constexpr time::Year::Year (Year &&) constexpr default
Year() [6/6]
constexpr time::Year::Year (const Year &) constexpr default
Member Function Documentation
getCompilationYear()
consteval Year time::Year::getCompilationYear () static noexcept
Definition at line 40 of file year_impl.h.
References time::build_year().
getCurrent()
static Year time::Year::getCurrent () static
getNumDays()
constexpr int time::Year::getNumDays () const constexpr noexcept
Definition at line 56 of file year_impl.h.
References isLeap().
getNumWeeks()
int time::Year::getNumWeeks () const noexcept
getYear()
constexpr int time::Year::getYear () const constexpr noexcept
Definition at line 69 of file year_impl.h.
Referenced by time::DateTime::getStdTime().
isBC()
constexpr bool time::Year::isBC () const constexpr noexcept
Definition at line 64 of file year_impl.h.
isInFuture()
bool time::Year::isInFuture () const noexcept
isInPast()
bool time::Year::isInPast () const noexcept
isLeap()
constexpr bool time::Year::isLeap () const constexpr noexcept
Definition at line 45 of file year_impl.h.
References math::isDivisibleBy().
Referenced by time::Date::getDayOfYear(), getNumDays(), and time::Weekday< StartWeekOnSunday >::Weekday().
operator int()
constexpr time::Year::operator int () const inline constexpr noexcept
Definition at line 53 of file year.h.
operator!=()
constexpr bool time::Year::operator!= (const Year & other) const constexpr noexcept
Definition at line 123 of file year_impl.h.
operator+()
constexpr Year time::Year::operator+ (int numYearsToAdd) const constexpr noexcept
Definition at line 86 of file year_impl.h.
operator++()
constexpr Year & time::Year::operator++ () constexpr noexcept
Definition at line 74 of file year_impl.h.
operator+=()
constexpr Year & time::Year::operator+= (int numYearsToAdd) constexpr noexcept
Definition at line 96 of file year_impl.h.
operator-()
constexpr Year time::Year::operator- (int numYearsToSubtract) const constexpr noexcept
Definition at line 91 of file year_impl.h.
operator--()
constexpr Year & time::Year::operator-- () constexpr noexcept
Definition at line 80 of file year_impl.h.
operator-=()
constexpr Year & time::Year::operator-= (int numYearsToSubtract) constexpr noexcept
Definition at line 102 of file year_impl.h.
operator<()
constexpr bool time::Year::operator< (const Year & other) const constexpr noexcept
Definition at line 113 of file year_impl.h.
operator=() [1/3]
constexpr Year& time::Year::operator= (const Year &) constexpr default
operator=() [2/3]
constexpr Year & time::Year::operator= (int newYear) constexpr noexcept
Definition at line 34 of file year_impl.h.
operator=() [3/3]
constexpr Year& time::Year::operator= (Year &&) constexpr default
operator==()
constexpr bool time::Year::operator== (const Year & other) const constexpr noexcept
Definition at line 118 of file year_impl.h.
operator>()
constexpr bool time::Year::operator> (const Year & other) const constexpr noexcept
Definition at line 108 of file year_impl.h.
The documentation for this class was generated from the following files:
year.h
year_impl.h