Limes: math::geometry::Triangle< ValueType > Class Template Reference
math::geometry::Triangle< ValueType > Class Template Reference final
#include <triangle.h>
Public Types
enum Side { Side::base, Side::height, Side::hypotenuse }
Public Member Functions
constexpr Triangle (const Triangle &)=default
constexpr Triangle (Triangle &&)=default
constexpr Triangle (ValueType base, ValueType height, ValueType hypotenuse) noexcept
Triangle (ValueType sideLength, const Angle< ValueType > &oppositeAngle, const Angle< ValueType > &anotherAngle)
Triangle (ValueType sideOne, ValueType sideTwo, const Angle< ValueType > &angleBetweenThem)
constexpr ValueType altitude () const noexcept
constexpr ValueType area () const noexcept final
constexpr ValueType base () const noexcept
Triangle bisect (Side side=Side::base) const noexcept
Angle< ValueType > getAngle (Side side) const noexcept
Angle< ValueType > getBaseAngle () const noexcept
Angle< ValueType > getHeightAngle () const noexcept
Angle< ValueType > getHypotenuseAngle () const noexcept
ValueType getSide (Side side) const noexcept
constexpr ValueType height () const noexcept
constexpr ValueType hypotenuse () const noexcept
constexpr bool isAcute () const noexcept
constexpr bool isEquilateral () const noexcept
constexpr bool isIsosceles () const noexcept
constexpr bool isObtuse () const noexcept
constexpr bool isRight () const noexcept
constexpr bool isScalene () const noexcept
bool isSimilarTo (const Triangle &other) const noexcept
constexpr bool operator!= (const Triangle &other) const noexcept
constexpr Triangle & operator= (const Triangle &)=default
constexpr Triangle & operator= (Triangle &&)=default
constexpr bool operator== (const Triangle &other) const noexcept
constexpr ValueType perimeter () const noexcept final
Detailed Description
template<Scalar ValueType>
class math::geometry::Triangle< ValueType >
Definition at line 30 of file triangle.h.
Member Enumeration Documentation
Side
template<Scalar ValueType> enum math::geometry::Triangle::Side strong
Enumerator
base
height
hypotenuse
Definition at line 78 of file triangle.h.
Constructor & Destructor Documentation
Triangle() [1/5]
template<Scalar ValueType> constexpr math::geometry::Triangle< ValueType >::Triangle (ValueType base, ValueType height, ValueType hypotenuse) explicit constexpr noexcept
Definition at line 98 of file triangle.h.
References LIMES_ASSERT.
Triangle() [2/5]
template<Scalar ValueType> math::geometry::Triangle< ValueType >::Triangle (ValueType sideLength, const Angle< ValueType > & oppositeAngle, const Angle< ValueType > & anotherAngle) explicit
Definition at line 107 of file triangle.h.
References math::geometry::Angle< ValueType >::degrees(), vecops::max(), math::middleOfThree(), and vecops::min().
Triangle() [3/5]
template<Scalar ValueType> math::geometry::Triangle< ValueType >::Triangle (ValueType sideOne, ValueType sideTwo, const Angle< ValueType > & angleBetweenThem) explicit
Definition at line 125 of file triangle.h.
References math::geometry::Angle< ValueType >::degrees(), vecops::max(), math::middleOfThree(), and vecops::min().
Triangle() [4/5]
template<Scalar ValueType> constexpr math::geometry::Triangle< ValueType >::Triangle (const Triangle< ValueType > &) constexpr default
Triangle() [5/5]
template<Scalar ValueType> constexpr math::geometry::Triangle< ValueType >::Triangle (Triangle< ValueType > &&) constexpr default
Member Function Documentation
altitude()
template<Scalar ValueType> constexpr ValueType math::geometry::Triangle< ValueType >::altitude constexpr noexcept
Definition at line 167 of file triangle.h.
area()
template<Scalar ValueType> constexpr ValueType math::geometry::Triangle< ValueType >::area constexpr final virtual noexcept
Implements math::geometry::TwoDShape< ValueType >.
Definition at line 137 of file triangle.h.
base()
template<Scalar ValueType> constexpr ValueType math::geometry::Triangle< ValueType >::base constexpr noexcept
Definition at line 149 of file triangle.h.
bisect()
template<Scalar ValueType> Triangle< ValueType > math::geometry::Triangle< ValueType >::bisect (Side side = Side::base) const noexcept
Definition at line 271 of file triangle.h.
getAngle()
template<Scalar ValueType> Angle< ValueType > math::geometry::Triangle< ValueType >::getAngle (Side side) const noexcept
Definition at line 239 of file triangle.h.
getBaseAngle()
template<Scalar ValueType> Angle< ValueType > math::geometry::Triangle< ValueType >::getBaseAngle noexcept
Definition at line 221 of file triangle.h.
getHeightAngle()
template<Scalar ValueType> Angle< ValueType > math::geometry::Triangle< ValueType >::getHeightAngle noexcept
Definition at line 227 of file triangle.h.
getHypotenuseAngle()
template<Scalar ValueType> Angle< ValueType > math::geometry::Triangle< ValueType >::getHypotenuseAngle noexcept
Definition at line 233 of file triangle.h.
getSide()
template<Scalar ValueType> ValueType math::geometry::Triangle< ValueType >::getSide (Side side) const noexcept
Definition at line 251 of file triangle.h.
height()
template<Scalar ValueType> constexpr ValueType math::geometry::Triangle< ValueType >::height constexpr noexcept
Definition at line 155 of file triangle.h.
hypotenuse()
template<Scalar ValueType> constexpr ValueType math::geometry::Triangle< ValueType >::hypotenuse constexpr noexcept
Definition at line 161 of file triangle.h.
isAcute()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::isAcute constexpr noexcept
Definition at line 197 of file triangle.h.
isEquilateral()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::isEquilateral constexpr noexcept
Definition at line 173 of file triangle.h.
isIsosceles()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::isIsosceles constexpr noexcept
Definition at line 179 of file triangle.h.
isObtuse()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::isObtuse constexpr noexcept
Definition at line 203 of file triangle.h.
isRight()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::isRight constexpr noexcept
Definition at line 191 of file triangle.h.
isScalene()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::isScalene constexpr noexcept
Definition at line 185 of file triangle.h.
isSimilarTo()
template<Scalar ValueType> bool math::geometry::Triangle< ValueType >::isSimilarTo (const Triangle< ValueType > & other) const noexcept
Definition at line 263 of file triangle.h.
operator!=()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::operator!= (const Triangle< ValueType > & other) const constexpr noexcept
Definition at line 215 of file triangle.h.
operator=() [1/2]
template<Scalar ValueType> constexpr Triangle& math::geometry::Triangle< ValueType >::operator= (const Triangle< ValueType > &) constexpr default
operator=() [2/2]
template<Scalar ValueType> constexpr Triangle& math::geometry::Triangle< ValueType >::operator= (Triangle< ValueType > &&) constexpr default
operator==()
template<Scalar ValueType> constexpr bool math::geometry::Triangle< ValueType >::operator== (const Triangle< ValueType > & other) const constexpr noexcept
Definition at line 209 of file triangle.h.
perimeter()
template<Scalar ValueType> constexpr ValueType math::geometry::Triangle< ValueType >::perimeter constexpr final virtual noexcept
Implements math::geometry::TwoDShape< ValueType >.
Definition at line 143 of file triangle.h.
The documentation for this class was generated from the following file:
triangle.h