Limes: Math
Math
Functions
template<Scalar T>
constexpr LIMES_EXPORT T math::abs (T val) noexcept
A constexpr-enabled absolute value function.
template<Integral T>
constexpr LIMES_EXPORT T math::factorial (T number) noexcept
template<Scalar PeriodType>
constexpr LIMES_EXPORT PeriodType math::freqFromPeriod (double samplerate, PeriodType period) noexcept
Returns the frequency in Hz with a given period in samples at the specified samplerate.
template<Scalar T>
LIMES_EXPORT T math::freqToMidi (T freqHz) noexcept
Converts a frequency in Hz to a MIDI note.
template<Integral Integer>
constexpr LIMES_EXPORT bool math::isDivisibleBy (Integer number, Integer divisor) noexcept
Returns true if the number is divisible by the divisor with no remainder.
template<Integral Integer>
constexpr LIMES_EXPORT bool math::isPowerOf2 (Integer val) noexcept
Returns true if val is 2^something.
template<Integral Integer>
constexpr LIMES_EXPORT bool math::isPrime (Integer number) noexcept
template<Scalar T>
constexpr LIMES_EXPORT T math::limit (T input, T min, T max) noexcept
template<Scalar T>
constexpr LIMES_EXPORT T math::map (T input, T sourceRangeMin, T sourceRangeMax, T targetRangeMin, T targetRangeMax) noexcept
template<Scalar T>
constexpr LIMES_EXPORT T math::middleOfThree (T a, T b, T c) noexcept
template<Scalar T>
constexpr LIMES_EXPORT T math::midiToFreq (T midiNote) noexcept
Converts a MIDI note to a frequency in Hz.
template<Scalar msType>
constexpr LIMES_EXPORT int math::msToSamps (double samplerate, msType ms) noexcept
Converts a number of milliseconds to the closest integer number of samples at the specified samplerate.
template<Scalar T>
constexpr LIMES_EXPORT T math::negate (T val) noexcept
template<Integral Integer>
constexpr LIMES_EXPORT bool math::numberIsEven (Integer number) noexcept
Returns true if the number is evenly divisible by 2.
template<Scalar FreqType>
constexpr LIMES_EXPORT int math::periodInSamples (double samplerate, FreqType freqHz) noexcept
Returns the period in samples of a frequency at the specified samplerate.
template<Integral T>
constexpr LIMES_EXPORT T math::power (T number, T power) noexcept
template<Scalar T>
constexpr LIMES_EXPORT int math::round (T val) noexcept
template<Integral Integer>
constexpr LIMES_EXPORT double math::sampsToMs (double samplerate, Integer numSamples) noexcept
Converts a number of samples to milliseconds at the specified samplerate.
Detailed Description
Math utility functions.
Function Documentation
abs()
template<Scalar T> constexpr LIMES_EXPORT T math::abs (T val) constexpr noexcept
A constexpr-enabled absolute value function.
Definition at line 153 of file mathHelpers.h.
factorial()
template<Integral T> constexpr LIMES_EXPORT T math::factorial (T number) constexpr noexcept
Definition at line 266 of file mathHelpers.h.
References math::factorial(), and LIMES_ASSERT.
Referenced by math::factorial().
freqFromPeriod()
template<Scalar PeriodType> constexpr LIMES_EXPORT PeriodType math::freqFromPeriod (double samplerate, PeriodType period) constexpr noexcept
Returns the frequency in Hz with a given period in samples at the specified samplerate.
Definition at line 295 of file mathHelpers.h.
References LIMES_ASSERT, and math::round().
freqToMidi()
template<Scalar T> LIMES_EXPORT T math::freqToMidi (T freqHz) inline noexcept
Converts a frequency in Hz to a MIDI note.
Definition at line 339 of file mathHelpers.h.
References math::round().
isDivisibleBy()
template<Integral Integer> constexpr LIMES_EXPORT bool math::isDivisibleBy (Integer number, Integer divisor) constexpr noexcept
Returns true if the number is divisible by the divisor with no remainder.
Definition at line 235 of file mathHelpers.h.
Referenced by time::Year::isLeap(), math::geometry::Angle< ValueType >::isOblique(), math::isPrime(), and math::numberIsEven().
isPowerOf2()
template<Integral Integer> constexpr LIMES_EXPORT bool math::isPowerOf2 (Integer val) constexpr noexcept
Returns true if val is 2^something.
Definition at line 229 of file mathHelpers.h.
Referenced by music::NoteDuration::NoteDuration().
isPrime()
template<Integral Integer> constexpr LIMES_EXPORT bool math::isPrime (Integer number) constexpr noexcept
Definition at line 247 of file mathHelpers.h.
References math::isDivisibleBy().
limit()
template<Scalar T> constexpr LIMES_EXPORT T math::limit (T input, T min, T max) constexpr noexcept
Definition at line 190 of file mathHelpers.h.
References LIMES_ASSERT, vecops::max(), and vecops::min().
map()
template<Scalar T> constexpr LIMES_EXPORT T math::map (T input, T sourceRangeMin, T sourceRangeMax, T targetRangeMin, T targetRangeMax) constexpr noexcept
Definition at line 220 of file mathHelpers.h.
References LIMES_ASSERT.
Referenced by math::Random::next().
middleOfThree()
template<Scalar T> constexpr LIMES_EXPORT T math::middleOfThree (T a, T b, T c) constexpr noexcept
Definition at line 277 of file mathHelpers.h.
References vecops::max(), and vecops::min().
Referenced by math::geometry::Triangle< ValueType >::Triangle().
midiToFreq()
template<Scalar T> constexpr LIMES_EXPORT T math::midiToFreq (T midiNote) constexpr noexcept
Converts a MIDI note to a frequency in Hz.
Definition at line 326 of file mathHelpers.h.
References math::power(), and math::round().
msToSamps()
template<Scalar msType> constexpr LIMES_EXPORT int math::msToSamps (double samplerate, msType ms) constexpr noexcept
Converts a number of milliseconds to the closest integer number of samples at the specified samplerate.
Definition at line 318 of file mathHelpers.h.
References math::round().
negate()
template<Scalar T> constexpr LIMES_EXPORT T math::negate (T val) constexpr noexcept
Definition at line 167 of file mathHelpers.h.
numberIsEven()
template<Integral Integer> constexpr LIMES_EXPORT bool math::numberIsEven (Integer number) constexpr noexcept
Returns true if the number is evenly divisible by 2.
Definition at line 241 of file mathHelpers.h.
References math::isDivisibleBy().
periodInSamples()
template<Scalar FreqType> constexpr LIMES_EXPORT int math::periodInSamples (double samplerate, FreqType freqHz) constexpr noexcept
Returns the period in samples of a frequency at the specified samplerate.
Definition at line 285 of file mathHelpers.h.
References LIMES_ASSERT, and math::round().
power()
template<Integral T> constexpr LIMES_EXPORT T math::power (T number, T power) constexpr noexcept
Definition at line 200 of file mathHelpers.h.
References math::power().
Referenced by math::midiToFreq(), and math::power().
round()
template<Scalar T> constexpr LIMES_EXPORT int math::round (T val) constexpr noexcept
Definition at line 176 of file mathHelpers.h.
Referenced by math::freqFromPeriod(), math::freqToMidi(), time::Month::getNumWeeks(), math::midiToFreq(), math::msToSamps(), and math::periodInSamples().
sampsToMs()
template<Integral Integer> constexpr LIMES_EXPORT double math::sampsToMs (double samplerate, Integer numSamples) constexpr noexcept
Converts a number of samples to milliseconds at the specified samplerate.
Definition at line 308 of file mathHelpers.h.
References LIMES_ASSERT.