Limes: vecops::fb Namespace Reference
vecops::fb Namespace Reference
Namespaces
detail
window
Functions
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void abs (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void absAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void add (DataType *const data, SizeType size, DataType constantToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void add (DataType *const dataAndDest, SizeType size, const DataType *const dataToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void applyRamp (DataType *const dataAndDest, SizeType size, DataType startValue, DataType endValue)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void applyRampAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType startValue, DataType endValue)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void cartesianInterleavedToMagnitudes (DataType *const mag, const DataType *const src, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void cartesianToMagnitudes (DataType *const mag, const DataType *const real, const DataType *const imag, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void cartesianToPolar (DataType *const mag, DataType *const phase, const DataType *const real, const DataType *const imag, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void catesianInterleavedToPolar (DataType *const mag, DataType *const phase, const DataType *const src, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void clear (DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void clip (DataType *const dataAndDest, SizeType size, DataType lowClip, DataType hiClip)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void clipAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType lowClip, DataType hiClip)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void copy (DataType *const dest, const DataType *const source, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE int countZeroCrossings (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void deinterleave (DataType *const *const output, const DataType *const interleavedData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void divide (DataType *const data, SizeType size, DataType constantToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void divide (DataType *const dataAndDest, SizeType size, const DataType *const dataToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void divideInv (DataType *const data, SizeType size, DataType constantToDivideFrom)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void divideInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivideFrom)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType dotProduct (const DataType *const vecA, const DataType *const vecB, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void fill (DataType *const data, SizeType size, DataType constantToFill)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void generateRamp (DataType *const output, SizeType size, DataType startValue, DataType endValue)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void interleave (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void invSquareRoot (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void invSquareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType max (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void max (const DataType *const data, SizeType size, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType maxAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void maxAbs (const DataType *const data, SizeType size, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType mean (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType min (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void min (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType minAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void minAbs (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void minMax (const DataType *const data, SizeType size, DataType &minValue, DataType &maxValue)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void minMax (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void minMaxAbs (const DataType *const data, SizeType size, DataType &minValue, DataType &maxValue)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void minMaxAbs (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void mix (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void multiply (DataType *const data, SizeType size, DataType constantToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void multiply (DataType *const dataAndDest, SizeType size, const DataType *const dataToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void negate (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void negateAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void polarToCartesian (DataType *const real, DataType *const imag, const DataType *const mag, const DataType *const phase, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void polarToCartesianInterleaved (DataType *const dest, const DataType *const mag, const DataType *const phase, SizeType size)
template<Scalar DataType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType quake3_fast_inv_sqrt (DataType number)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType range (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType rangeAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void reverse (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void reverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType rms (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void sort (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void sortAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void sortReverse (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void sortReverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void square (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void squareAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void squareRoot (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void squareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void subtract (DataType *const data, SizeType size, DataType constantToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void subtract (DataType *const dataAndDest, SizeType size, const DataType *const dataToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void subtractInv (DataType *const data, SizeType size, DataType constantToSubtractFrom)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void subtractInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtractFrom)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType sum (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_NO_EXPORT LIMES_FORCE_INLINE void swap (DataType *const vecA, DataType *const vecB, SizeType size)
Function Documentation
abs()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::abs (DataType *const dataAndDest, SizeType size)
Definition at line 461 of file fallback_impl.h.
References abs(), and alg::size().
Referenced by vecops::abs(), absAndCopy(), maxAbs(), and minAbs().
absAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::absAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 468 of file fallback_impl.h.
References abs(), absAndCopy(), and alg::size().
Referenced by vecops::absAndCopy().
add() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::add (DataType *const data, SizeType size, DataType constantToAdd)
Definition at line 75 of file fallback_impl.h.
References add(), and alg::size().
Referenced by vecops::add(), and mix().
add() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::add (DataType *const dataAndDest, SizeType size, const DataType *const dataToAdd)
Definition at line 82 of file fallback_impl.h.
References add(), and alg::size().
addAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToAdd)
Definition at line 96 of file fallback_impl.h.
References addAndCopy(), and alg::size().
addAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToAdd)
Definition at line 89 of file fallback_impl.h.
References addAndCopy(), and alg::size().
Referenced by vecops::addAndCopy().
applyRamp()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::applyRamp (DataType *const dataAndDest, SizeType size, DataType startValue, DataType endValue)
Definition at line 734 of file fallback_impl.h.
References applyRamp(), and alg::size().
Referenced by vecops::applyRamp().
applyRampAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::applyRampAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType startValue, DataType endValue)
Definition at line 743 of file fallback_impl.h.
References applyRampAndCopy(), and alg::size().
Referenced by vecops::applyRampAndCopy().
cartesianInterleavedToMagnitudes()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::cartesianInterleavedToMagnitudes (DataType *const mag, const DataType *const src, SizeType size)
Definition at line 934 of file fallback_impl.h.
References cartesianInterleavedToMagnitudes(), and alg::size().
Referenced by vecops::cartesianInterleavedToMagnitudes().
cartesianToMagnitudes()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::cartesianToMagnitudes (DataType *const mag, const DataType *const real, const DataType *const imag, SizeType size)
Definition at line 927 of file fallback_impl.h.
References cartesianToMagnitudes(), and alg::size().
Referenced by vecops::cartesianToMagnitudes().
cartesianToPolar()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::cartesianToPolar (DataType *const mag, DataType *const phase, const DataType *const real, const DataType *const imag, SizeType size)
Definition at line 910 of file fallback_impl.h.
References cartesianToPolar(), and alg::size().
Referenced by vecops::cartesianToPolar().
catesianInterleavedToPolar()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::catesianInterleavedToPolar (DataType *const mag, DataType *const phase, const DataType *const src, SizeType size)
Definition at line 917 of file fallback_impl.h.
References catesianInterleavedToPolar(), and alg::size().
Referenced by vecops::catesianInterleavedToPolar().
clear()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::clear (DataType *const data, SizeType size)
Definition at line 44 of file fallback_impl.h.
References clear(), fill(), and alg::size().
Referenced by vecops::clear().
clip()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::clip (DataType *const dataAndDest, SizeType size, DataType lowClip, DataType hiClip)
Definition at line 489 of file fallback_impl.h.
References clip(), max(), min(), and alg::size().
Referenced by vecops::clip().
clipAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::clipAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType lowClip, DataType hiClip)
Definition at line 501 of file fallback_impl.h.
References clipAndCopy(), max(), min(), and alg::size().
Referenced by vecops::clipAndCopy().
copy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::copy (DataType *const dest, const DataType *const source, SizeType size)
Definition at line 50 of file fallback_impl.h.
References copy(), and alg::size().
Referenced by vecops::copy(), deinterleave(), interleave(), mix(), reverseAndCopy(), sortAndCopy(), and sortReverseAndCopy().
countZeroCrossings()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE int vecops::fb::countZeroCrossings (const DataType *const data, SizeType size)
Definition at line 701 of file fallback_impl.h.
References countZeroCrossings(), and alg::size().
Referenced by vecops::countZeroCrossings().
deinterleave()
template<Scalar DataType, Integral SizeType1, Integral SizeType2> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::deinterleave (DataType *const *const output, const DataType *const interleavedData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 426 of file fallback_impl.h.
References copy(), and deinterleave().
Referenced by vecops::deinterleave().
divide() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::divide (DataType *const data, SizeType size, DataType constantToDivide)
Definition at line 193 of file fallback_impl.h.
References divide(), and alg::size().
Referenced by vecops::divide().
divide() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::divide (DataType *const dataAndDest, SizeType size, const DataType *const dataToDivide)
Definition at line 200 of file fallback_impl.h.
References divide(), and alg::size().
divideAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToDivide)
Definition at line 214 of file fallback_impl.h.
References divideAndCopy(), and alg::size().
divideAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivide)
Definition at line 207 of file fallback_impl.h.
References divideAndCopy(), and alg::size().
Referenced by vecops::divideAndCopy().
divideInv()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::divideInv (DataType *const data, SizeType size, DataType constantToDivideFrom)
Definition at line 221 of file fallback_impl.h.
References divideInv(), and alg::size().
Referenced by vecops::divideInv().
divideInvAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::divideInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivideFrom)
Definition at line 233 of file fallback_impl.h.
References divideInvAndCopy(), and alg::size().
Referenced by vecops::divideInvAndCopy().
dotProduct()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::dotProduct (const DataType *const vecA, const DataType *const vecB, SizeType size)
Definition at line 179 of file fallback_impl.h.
References dotProduct(), and alg::size().
Referenced by vecops::dotProduct().
fill()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::fill (DataType *const data, SizeType size, DataType constantToFill)
Definition at line 38 of file fallback_impl.h.
References fill(), and alg::size().
Referenced by clear(), and vecops::fill().
generateRamp()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::generateRamp (DataType *const output, SizeType size, DataType startValue, DataType endValue)
Definition at line 725 of file fallback_impl.h.
References generateRamp(), and alg::size().
Referenced by vecops::generateRamp().
interleave()
template<Scalar DataType, Integral SizeType1, Integral SizeType2> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::interleave (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 396 of file fallback_impl.h.
References copy(), and interleave().
Referenced by vecops::interleave().
invSquareRoot()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::invSquareRoot (DataType *const dataAndDest, SizeType size)
Definition at line 307 of file fallback_impl.h.
References invSquareRoot(), quake3_fast_inv_sqrt(), and alg::size().
Referenced by vecops::invSquareRoot().
invSquareRootAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::invSquareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 329 of file fallback_impl.h.
References invSquareRootAndCopy(), quake3_fast_inv_sqrt(), and alg::size().
Referenced by vecops::invSquareRootAndCopy().
max() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::max (const DataType *const data, SizeType size)
Definition at line 513 of file fallback_impl.h.
References max(), and alg::size().
Referenced by vecops::max().
max() [2/2]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::max (const DataType *const data, SizeType size, DataType & maxValue, IndexType & maxIndex)
Definition at line 519 of file fallback_impl.h.
References max(), and alg::size().
Referenced by clip(), clipAndCopy(), maxAbs(), and minAbs().
maxAbs() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::maxAbs (const DataType *const data, SizeType size)
Definition at line 528 of file fallback_impl.h.
References abs(), max(), maxAbs(), and alg::size().
Referenced by vecops::maxAbs(), and minMaxAbs().
maxAbs() [2/2]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::maxAbs (const DataType *const data, SizeType size, DataType & maxValue, IndexType & maxIndex)
Definition at line 539 of file fallback_impl.h.
References abs(), maxAbs(), and alg::size().
mean()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::mean (const DataType *const data, SizeType size)
Definition at line 660 of file fallback_impl.h.
References mean(), alg::size(), and sum().
Referenced by vecops::mean().
min() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::min (const DataType *const data, SizeType size)
Definition at line 556 of file fallback_impl.h.
References min(), and alg::size().
Referenced by vecops::min().
min() [2/2]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::min (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex)
Definition at line 562 of file fallback_impl.h.
References min(), and alg::size().
Referenced by clip(), clipAndCopy(), and minAbs().
minAbs() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::minAbs (const DataType *const data, SizeType size)
Definition at line 571 of file fallback_impl.h.
References abs(), max(), min(), minAbs(), and alg::size().
Referenced by vecops::minAbs(), and minMaxAbs().
minAbs() [2/2]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::minAbs (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex)
Definition at line 582 of file fallback_impl.h.
References abs(), max(), minAbs(), and alg::size().
minMax() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::minMax (const DataType *const data, SizeType size, DataType & minValue, DataType & maxValue)
Definition at line 599 of file fallback_impl.h.
References minMax(), and alg::size().
Referenced by vecops::minMax(), and range().
minMax() [2/2]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::minMax (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex, DataType & maxValue, IndexType & maxIndex)
Definition at line 608 of file fallback_impl.h.
References minMax(), and alg::size().
minMaxAbs() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::minMaxAbs (const DataType *const data, SizeType size, DataType & minValue, DataType & maxValue)
Definition at line 620 of file fallback_impl.h.
References maxAbs(), minAbs(), minMaxAbs(), and alg::size().
Referenced by vecops::minMaxAbs(), and rangeAbs().
minMaxAbs() [2/2]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::minMaxAbs (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex, DataType & maxValue, IndexType & maxIndex)
Definition at line 627 of file fallback_impl.h.
References maxAbs(), minAbs(), minMaxAbs(), and alg::size().
mix()
template<Scalar DataType, Integral SizeType1, Integral SizeType2> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::mix (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 670 of file fallback_impl.h.
References add(), copy(), mix(), and multiply().
Referenced by vecops::mix().
multiply() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::multiply (DataType *const data, SizeType size, DataType constantToMultiply)
Definition at line 151 of file fallback_impl.h.
References multiply(), and alg::size().
Referenced by mix(), and vecops::multiply().
multiply() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::multiply (DataType *const dataAndDest, SizeType size, const DataType *const dataToMultiply)
Definition at line 158 of file fallback_impl.h.
References multiply(), and alg::size().
multiplyAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToMultiply)
Definition at line 172 of file fallback_impl.h.
References multiplyAndCopy(), and alg::size().
multiplyAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToMultiply)
Definition at line 165 of file fallback_impl.h.
References multiplyAndCopy(), and alg::size().
Referenced by vecops::multiplyAndCopy().
negate()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::negate (DataType *const dataAndDest, SizeType size)
Definition at line 475 of file fallback_impl.h.
References negate(), and alg::size().
Referenced by vecops::negate().
negateAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::negateAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 482 of file fallback_impl.h.
References negateAndCopy(), and alg::size().
Referenced by vecops::negateAndCopy().
polarToCartesian()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::polarToCartesian (DataType *const real, DataType *const imag, const DataType *const mag, const DataType *const phase, SizeType size)
Definition at line 865 of file fallback_impl.h.
References vecops::multiply(), vecops::pommier::polarToCartesian(), polarToCartesian(), and alg::size().
Referenced by vecops::polarToCartesian().
polarToCartesianInterleaved()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::polarToCartesianInterleaved (DataType *const dest, const DataType *const mag, const DataType *const phase, SizeType size)
Definition at line 883 of file fallback_impl.h.
References vecops::pommier::polarToCartesianInterleaved(), polarToCartesianInterleaved(), and alg::size().
Referenced by vecops::polarToCartesianInterleaved().
quake3_fast_inv_sqrt()
template<Scalar DataType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::quake3_fast_inv_sqrt (DataType number)
Definition at line 281 of file fallback_impl.h.
Referenced by invSquareRoot(), and invSquareRootAndCopy().
range()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::range (const DataType *const data, SizeType size)
Definition at line 634 of file fallback_impl.h.
References minMax(), range(), and alg::size().
Referenced by vecops::range().
rangeAbs()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::rangeAbs (const DataType *const data, SizeType size)
Definition at line 644 of file fallback_impl.h.
References minMaxAbs(), rangeAbs(), and alg::size().
Referenced by vecops::rangeAbs().
reverse()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::reverse (DataType *const dataAndDest, SizeType size)
Definition at line 356 of file fallback_impl.h.
References reverse(), and alg::size().
Referenced by vecops::reverse(), reverseAndCopy(), and sortReverse().
reverseAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::reverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 362 of file fallback_impl.h.
References copy(), reverse(), reverseAndCopy(), and alg::size().
Referenced by vecops::reverseAndCopy().
rms()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::rms (const DataType *const data, SizeType size)
Definition at line 685 of file fallback_impl.h.
References rms(), and alg::size().
Referenced by vecops::rms().
sort()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::sort (DataType *const dataAndDest, SizeType size)
Definition at line 369 of file fallback_impl.h.
References alg::size(), and sort().
Referenced by vecops::sort(), sortAndCopy(), and sortReverse().
sortAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::sortAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 375 of file fallback_impl.h.
References copy(), alg::size(), sort(), and sortAndCopy().
Referenced by vecops::sortAndCopy().
sortReverse()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::sortReverse (DataType *const dataAndDest, SizeType size)
Definition at line 382 of file fallback_impl.h.
References reverse(), alg::size(), sort(), and sortReverse().
Referenced by vecops::sortReverse(), and sortReverseAndCopy().
sortReverseAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::sortReverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 389 of file fallback_impl.h.
References copy(), alg::size(), sortReverse(), and sortReverseAndCopy().
Referenced by vecops::sortReverseAndCopy().
square()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::square (DataType *const dataAndDest, SizeType size)
Definition at line 251 of file fallback_impl.h.
References alg::size(), and square().
Referenced by vecops::square().
squareAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::squareAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 258 of file fallback_impl.h.
References alg::size(), and squareAndCopy().
Referenced by vecops::squareAndCopy().
squareRoot()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::squareRoot (DataType *const dataAndDest, SizeType size)
Definition at line 265 of file fallback_impl.h.
References alg::size(), and squareRoot().
Referenced by vecops::squareRoot().
squareRootAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::squareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 272 of file fallback_impl.h.
References alg::size(), and squareRootAndCopy().
Referenced by vecops::squareRootAndCopy().
subtract() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::subtract (DataType *const data, SizeType size, DataType constantToSubtract)
Definition at line 106 of file fallback_impl.h.
References alg::size(), and subtract().
Referenced by vecops::subtract().
subtract() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::subtract (DataType *const dataAndDest, SizeType size, const DataType *const dataToSubtract)
Definition at line 113 of file fallback_impl.h.
References alg::size(), and subtract().
subtractAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToSubtract)
Definition at line 127 of file fallback_impl.h.
References alg::size(), and subtractAndCopy().
subtractAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtract)
Definition at line 120 of file fallback_impl.h.
References alg::size(), and subtractAndCopy().
Referenced by vecops::subtractAndCopy().
subtractInv()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::subtractInv (DataType *const data, SizeType size, DataType constantToSubtractFrom)
Definition at line 134 of file fallback_impl.h.
References alg::size(), and subtractInv().
Referenced by vecops::subtractInv().
subtractInvAndCopy()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::subtractInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtractFrom)
Definition at line 141 of file fallback_impl.h.
References alg::size(), and subtractInvAndCopy().
Referenced by vecops::subtractInvAndCopy().
sum()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE DataType vecops::fb::sum (const DataType *const data, SizeType size)
Definition at line 654 of file fallback_impl.h.
References alg::size(), and sum().
Referenced by mean(), and vecops::sum().
swap()
template<Scalar DataType, Integral SizeType> LIMES_NO_EXPORT LIMES_FORCE_INLINE void vecops::fb::swap (DataType *const vecA, DataType *const vecB, SizeType size)
Definition at line 56 of file fallback_impl.h.
References alg::size(), and swap().
Referenced by vecops::swap().