Limes: alg Namespace Reference
alg Namespace Reference
Typedefs
template<Container ContainerType>
using ElementType = std::remove_reference_t< decltype(*std::begin(std::declval< ContainerType & >()))>
template<Container ContainerType>
using IteratorType = decltype(std::begin(std::declval< ContainerType >()))
Functions
template<Container Container1, Container Container2, class Callable >
constexpr LIMES_EXPORT int call_both (const Container1 &container1, const Container2 &container2, Callable &&callable)
template<Container ContainerType>
constexpr LIMES_EXPORT bool contains (const ContainerType &container, const ElementType< ContainerType > &value)
template<Container ContainerType, class UnaryPredicate >
constexpr LIMES_EXPORT bool contains_if (const ContainerType &container, UnaryPredicate &&p)
template<Container ContainerType, class UnaryPredicate >
constexpr const LIMES_EXPORT ElementType< ContainerType > & contains_or (const ContainerType &container, const ElementType< ContainerType > &defaultValue, UnaryPredicate &&p)
template<Container ContainerType, class UnaryPredicate >
constexpr LIMES_EXPORT ElementType< ContainerType > & contains_or (const ContainerType &container, ElementType< ContainerType > &defaultValue, UnaryPredicate &&p)
template<Container ContainerType, class UnaryPredicate >
constexpr LIMES_EXPORT auto contains_or_default (const ContainerType &container, UnaryPredicate &&p)
template<Container ContainerType, class UnaryPredicate >
constexpr const LIMES_EXPORT ElementType< ContainerType > * contains_or_null (const ContainerType &container, UnaryPredicate &&p)
template<Container ContainerType, class UnaryPredicate >
constexpr LIMES_EXPORT ElementType< ContainerType > * contains_or_null (ContainerType &container, UnaryPredicate &&p)
template<Container OutputContainerType, Container InputContainer, class UnaryOp >
constexpr LIMES_EXPORT OutputContainerType createFromTransform (const InputContainer &input, UnaryOp &&func)
template<Container ContainerType>
constexpr LIMES_EXPORT auto enumerate (ContainerType &&iterable)
template<Container ContainerType>
constexpr LIMES_EXPORT void fill (ContainerType &container, const ElementType< ContainerType > &toFillWith)
template<Container ContainerType, class UnaryPredicate >
constexpr LIMES_EXPORT auto * find_if (const ContainerType &container, UnaryPredicate &&p)
static LIMES_NO_EXPORT auto & get_rand_engine ()
template<Container ContainerType>
constexpr LIMES_EXPORT auto max_value (const ContainerType &container)
template<Container ContainerType>
constexpr LIMES_EXPORT auto max_value (const ContainerType &container, int &maxIndex)
template<Container ContainerType>
constexpr LIMES_EXPORT auto min_value (const ContainerType &container)
template<Container ContainerType>
constexpr LIMES_EXPORT auto min_value (const ContainerType &container, int &minIndex)
template<Container ContainerType, class UnaryPredicate >
constexpr LIMES_EXPORT int num_of (const ContainerType &container, UnaryPredicate &&p)
template<Container ContainerType>
constexpr LIMES_EXPORT void remove (ContainerType &container, const ElementType< ContainerType > &object)
template<Container ContainerType>
constexpr LIMES_EXPORT void removeDuplicates (ContainerType &container)
template<Container ContainerType>
constexpr LIMES_EXPORT void reverse (ContainerType &container)
template<Container ContainerType>
LIMES_EXPORT void shuffle (ContainerType &container)
template<Container ContainerType>
constexpr LIMES_EXPORT int size (const ContainerType &container)
template<Container ContainerType>
constexpr LIMES_EXPORT void sort (ContainerType &container, bool forward=true)
template<Container ContainerType, class Comparison >
constexpr LIMES_EXPORT void sort (ContainerType &container, Comparison &&predicate, bool forward=true)
template<Container InputContainer, Container OutputContainer, class UnaryOp >
constexpr LIMES_EXPORT void transform (const InputContainer &input, OutputContainer &output, UnaryOp &&func)
Variables
template<typename T >
concept Container
Typedef Documentation
ElementType
template<Container ContainerType> using alg::ElementType = typedef std::remove_reference_t<decltype (*std::begin (std::declval<ContainerType&>()))>
Definition at line 34 of file Algorithm.h.
IteratorType
template<Container ContainerType> using alg::IteratorType = typedef decltype (std::begin (std::declval<ContainerType>()))
Definition at line 37 of file Algorithm.h.
Function Documentation
call_both()
template<Container Container1, Container Container2, class Callable > constexpr LIMES_EXPORT int alg::call_both (const Container1 & container1, const Container2 & container2, Callable && callable) constexpr
Definition at line 202 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::zip_with().
contains()
template<Container ContainerType> constexpr LIMES_EXPORT bool alg::contains (const ContainerType & container, const ElementType< ContainerType > & value) constexpr
Definition at line 46 of file Algorithm.h.
Referenced by memory::stack_buffer< N, alignof(std::max_align_t) >::allocate(), ds::basic_vector< SampleType, std::allocator< SampleType > >::contains(), memory::stack_buffer< N, alignof(std::max_align_t) >::deallocate(), and memory::MemoryPool::owns().
contains_if()
template<Container ContainerType, class UnaryPredicate > constexpr LIMES_EXPORT bool alg::contains_if (const ContainerType & container, UnaryPredicate && p) constexpr
Definition at line 52 of file Algorithm.h.
References find_if().
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::contains_if().
contains_or() [1/2]
template<Container ContainerType, class UnaryPredicate > constexpr const LIMES_EXPORT ElementType<ContainerType>& alg::contains_or (const ContainerType & container, const ElementType< ContainerType > & defaultValue, UnaryPredicate && p) constexpr
Definition at line 69 of file Algorithm.h.
References find_if().
contains_or() [2/2]
template<Container ContainerType, class UnaryPredicate > constexpr LIMES_EXPORT ElementType<ContainerType>& alg::contains_or (const ContainerType & container, ElementType< ContainerType > & defaultValue, UnaryPredicate && p) constexpr
Definition at line 58 of file Algorithm.h.
References find_if().
contains_or_default()
template<Container ContainerType, class UnaryPredicate > constexpr LIMES_EXPORT auto alg::contains_or_default (const ContainerType & container, UnaryPredicate && p) constexpr
Definition at line 80 of file Algorithm.h.
References find_if().
contains_or_null() [1/2]
template<Container ContainerType, class UnaryPredicate > constexpr const LIMES_EXPORT ElementType<ContainerType>* alg::contains_or_null (const ContainerType & container, UnaryPredicate && p) constexpr
Definition at line 107 of file Algorithm.h.
References find_if().
contains_or_null() [2/2]
template<Container ContainerType, class UnaryPredicate > constexpr LIMES_EXPORT ElementType<ContainerType>* alg::contains_or_null (ContainerType & container, UnaryPredicate && p) constexpr
Definition at line 96 of file Algorithm.h.
References find_if().
createFromTransform()
template<Container OutputContainerType, Container InputContainer, class UnaryOp > constexpr LIMES_EXPORT OutputContainerType alg::createFromTransform (const InputContainer & input, UnaryOp && func) constexpr
Definition at line 255 of file Algorithm.h.
References transform().
enumerate()
template<Container ContainerType> constexpr LIMES_EXPORT auto alg::enumerate (ContainerType && iterable) constexpr
Definition at line 269 of file Algorithm.h.
References math::geometry::operator!=().
fill()
template<Container ContainerType> constexpr LIMES_EXPORT void alg::fill (ContainerType & container, const ElementType< ContainerType > & toFillWith) constexpr
Definition at line 40 of file Algorithm.h.
find_if()
template<Container ContainerType, class UnaryPredicate > constexpr LIMES_EXPORT auto* alg::find_if (const ContainerType & container, UnaryPredicate && p) constexpr
Definition at line 118 of file Algorithm.h.
Referenced by contains_if(), contains_or(), contains_or_default(), contains_or_null(), and ds::basic_vector< SampleType, std::allocator< SampleType > >::find_if().
get_rand_engine()
static LIMES_NO_EXPORT auto& alg::get_rand_engine () inline static
Definition at line 182 of file Algorithm.h.
Referenced by shuffle().
max_value() [1/2]
template<Container ContainerType> constexpr LIMES_EXPORT auto alg::max_value (const ContainerType & container) constexpr
Definition at line 217 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::max().
max_value() [2/2]
template<Container ContainerType> constexpr LIMES_EXPORT auto alg::max_value (const ContainerType & container, int & maxIndex) constexpr
Definition at line 223 of file Algorithm.h.
min_value() [1/2]
template<Container ContainerType> constexpr LIMES_EXPORT auto alg::min_value (const ContainerType & container) constexpr
Definition at line 233 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::min().
min_value() [2/2]
template<Container ContainerType> constexpr LIMES_EXPORT auto alg::min_value (const ContainerType & container, int & minIndex) constexpr
Definition at line 239 of file Algorithm.h.
num_of()
template<Container ContainerType, class UnaryPredicate > constexpr LIMES_EXPORT int alg::num_of (const ContainerType & container, UnaryPredicate && p) constexpr
Definition at line 132 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::num_of(), and size().
remove()
template<Container ContainerType> constexpr LIMES_EXPORT void alg::remove (ContainerType & container, const ElementType< ContainerType > & object) constexpr
Definition at line 147 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::remove().
removeDuplicates()
template<Container ContainerType> constexpr LIMES_EXPORT void alg::removeDuplicates (ContainerType & container) constexpr
Definition at line 153 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::removeDuplicates().
reverse()
template<Container ContainerType> constexpr LIMES_EXPORT void alg::reverse (ContainerType & container) constexpr
Definition at line 159 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::reverse(), and sort().
shuffle()
template<Container ContainerType> LIMES_EXPORT void alg::shuffle (ContainerType & container)
Definition at line 196 of file Algorithm.h.
References get_rand_engine().
size()
template<Container ContainerType> constexpr LIMES_EXPORT int alg::size (const ContainerType & container) constexpr
Definition at line 138 of file Algorithm.h.
References num_of().
Referenced by vecops::abs(), vecops::fb::abs(), vecops::absAndCopy(), vecops::fb::absAndCopy(), vecops::fb::add(), vecops::add(), vecops::fb::addAndCopy(), vecops::addAndCopy(), vecops::window::applyBlackman(), vecops::fb::window::applyBlackman(), vecops::window::applyBlackmanAndCopy(), vecops::fb::window::applyBlackmanAndCopy(), vecops::window::applyHamm(), vecops::fb::window::applyHamm(), vecops::window::applyHammAndCopy(), vecops::fb::window::applyHammAndCopy(), vecops::window::applyHanning(), vecops::fb::window::applyHanning(), vecops::window::applyHanningAndCopy(), vecops::fb::window::applyHanningAndCopy(), vecops::applyRamp(), vecops::fb::applyRamp(), vecops::applyRampAndCopy(), vecops::fb::applyRampAndCopy(), vecops::cartesianInterleavedToMagnitudes(), vecops::fb::cartesianInterleavedToMagnitudes(), vecops::cartesianToMagnitudes(), vecops::fb::cartesianToMagnitudes(), vecops::cartesianToPolar(), vecops::fb::cartesianToPolar(), vecops::catesianInterleavedToPolar(), vecops::fb::catesianInterleavedToPolar(), vecops::fb::clear(), vecops::clear(), vecops::clip(), vecops::fb::clip(), vecops::clipAndCopy(), vecops::fb::clipAndCopy(), vecops::convert(), vecops::fb::copy(), vecops::copy(), vecops::countZeroCrossings(), vecops::fb::countZeroCrossings(), vecops::fb::divide(), vecops::divide(), vecops::divideAndCopy(), vecops::fb::divideAndCopy(), vecops::divideInv(), vecops::fb::divideInv(), vecops::divideInvAndCopy(), vecops::fb::divideInvAndCopy(), vecops::fb::dotProduct(), vecops::dotProduct(), vecops::fb::fill(), vecops::fill(), vecops::window::generateBlackman(), vecops::fb::window::generateBlackman(), vecops::window::generateHamm(), vecops::fb::window::generateHamm(), vecops::window::generateHanning(), vecops::fb::window::generateHanning(), vecops::generateRamp(), vecops::fb::generateRamp(), vecops::fb::window::detail::getBlackmanSample(), vecops::fb::window::detail::getHammSample(), vecops::fb::window::detail::getHanningSample(), vecops::detail::getVecLoopSize(), vecops::invSquareRoot(), vecops::fb::invSquareRoot(), vecops::invSquareRootAndCopy(), vecops::fb::invSquareRootAndCopy(), vecops::max(), vecops::fb::max(), vecops::maxAbs(), vecops::fb::maxAbs(), vecops::mean(), vecops::fb::mean(), vecops::min(), vecops::fb::min(), vecops::minAbs(), vecops::fb::minAbs(), vecops::minMax(), vecops::fb::minMax(), vecops::minMaxAbs(), vecops::fb::minMaxAbs(), vecops::fb::multiply(), vecops::multiply(), vecops::fb::multiplyAndCopy(), vecops::multiplyAndCopy(), vecops::fb::window::detail::ncos(), vecops::negate(), vecops::fb::negate(), vecops::negateAndCopy(), vecops::fb::negateAndCopy(), vecops::detail::perform(), vecops::polarToCartesian(), vecops::fb::polarToCartesian(), vecops::polarToCartesianInterleaved(), vecops::fb::polarToCartesianInterleaved(), vecops::range(), vecops::fb::range(), vecops::rangeAbs(), vecops::fb::rangeAbs(), vecops::reverse(), vecops::fb::reverse(), vecops::reverseAndCopy(), vecops::fb::reverseAndCopy(), vecops::rms(), vecops::fb::rms(), ds::LinkedListModel< ds::LinkedList::Node >::sizeOfList(), vecops::sort(), vecops::fb::sort(), vecops::sortAndCopy(), vecops::fb::sortAndCopy(), vecops::sortReverse(), vecops::fb::sortReverse(), vecops::sortReverseAndCopy(), vecops::fb::sortReverseAndCopy(), vecops::square(), vecops::fb::square(), vecops::squareAndCopy(), vecops::fb::squareAndCopy(), vecops::squareRoot(), vecops::fb::squareRoot(), vecops::squareRootAndCopy(), vecops::fb::squareRootAndCopy(), vecops::fb::subtract(), vecops::subtract(), vecops::fb::subtractAndCopy(), vecops::subtractAndCopy(), vecops::fb::subtractInv(), vecops::subtractInv(), vecops::fb::subtractInvAndCopy(), vecops::subtractInvAndCopy(), vecops::sum(), vecops::fb::sum(), vecops::fb::swap(), and vecops::swap().
sort() [1/2]
template<Container ContainerType> constexpr LIMES_EXPORT void alg::sort (ContainerType & container, bool forward = true) constexpr
Definition at line 165 of file Algorithm.h.
References reverse(), and sort().
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::sort().
sort() [2/2]
template<Container ContainerType, class Comparison > constexpr LIMES_EXPORT void alg::sort (ContainerType & container, Comparison && predicate, bool forward = true) constexpr
Definition at line 174 of file Algorithm.h.
References reverse().
Referenced by sort().
transform()
template<Container InputContainer, Container OutputContainer, class UnaryOp > constexpr LIMES_EXPORT void alg::transform (const InputContainer & input, OutputContainer & output, UnaryOp && func) constexpr
Definition at line 249 of file Algorithm.h.
Referenced by ds::basic_vector< SampleType, std::allocator< SampleType > >::basic_vector(), createFromTransform(), ds::basic_vector< SampleType, std::allocator< SampleType > >::createFromTransform(), ds::basic_vector< SampleType, std::allocator< SampleType > >::transform(), and ds::basic_vector< SampleType, std::allocator< SampleType > >::transformElementsTo().
Variable Documentation
Container
template<typename T > concept alg::Container
Initial value:
= requires (T a)
{
    { std::begin (a) };
    { std::end (a) };
}
Definition at line 27 of file Algorithm.h.