Limes: vecops::window Namespace Reference
vecops::window Namespace Reference
Functions
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyBlackman (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void applyBlackman (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyBlackmanAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void applyBlackmanAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyHamm (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void applyHamm (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyHammAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void applyHammAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyHanning (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void applyHanning (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyHanningAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void applyHanningAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void generateBlackman (DataType *const output, SizeType size)
template<Scalar DataType, Integral SizeType>
void generateBlackman (DataType *const output, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void generateHamm (DataType *const output, SizeType size)
template<Scalar DataType, Integral SizeType>
void generateHamm (DataType *const output, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void generateHanning (DataType *const output, SizeType size)
template<Scalar DataType, Integral SizeType>
void generateHanning (DataType *const output, SizeType size)
Function Documentation
applyBlackman() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::applyBlackman (DataType *const dataAndDest, SizeType size)
Definition at line 480 of file fallback.h.
References vecops::fb::window::applyBlackman(), and alg::size().
Referenced by applyBlackman().
applyBlackman() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::applyBlackman (DataType *const dataAndDest, SizeType size)
Definition at line 480 of file fallback.h.
applyBlackmanAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::applyBlackmanAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 486 of file fallback.h.
References vecops::fb::window::applyBlackmanAndCopy(), and alg::size().
Referenced by applyBlackmanAndCopy().
applyBlackmanAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::applyBlackmanAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 486 of file fallback.h.
applyHamm() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::applyHamm (DataType *const dataAndDest, SizeType size)
Definition at line 498 of file fallback.h.
References vecops::fb::window::applyHamm(), and alg::size().
Referenced by applyHamm().
applyHamm() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::applyHamm (DataType *const dataAndDest, SizeType size)
Definition at line 498 of file fallback.h.
applyHammAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::applyHammAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 504 of file fallback.h.
References vecops::fb::window::applyHammAndCopy(), and alg::size().
Referenced by applyHammAndCopy().
applyHammAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::applyHammAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 504 of file fallback.h.
applyHanning() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::applyHanning (DataType *const dataAndDest, SizeType size)
Definition at line 516 of file fallback.h.
References vecops::fb::window::applyHanning(), and alg::size().
Referenced by applyHanning().
applyHanning() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::applyHanning (DataType *const dataAndDest, SizeType size)
Definition at line 516 of file fallback.h.
applyHanningAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::applyHanningAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 522 of file fallback.h.
References vecops::fb::window::applyHanningAndCopy(), and alg::size().
Referenced by applyHanningAndCopy().
applyHanningAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::applyHanningAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 522 of file fallback.h.
generateBlackman() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::generateBlackman (DataType *const output, SizeType size)
Definition at line 474 of file fallback.h.
References vecops::fb::window::generateBlackman(), and alg::size().
Referenced by generateBlackman().
generateBlackman() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::generateBlackman (DataType *const output, SizeType size)
Definition at line 474 of file fallback.h.
generateHamm() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::generateHamm (DataType *const output, SizeType size)
Definition at line 492 of file fallback.h.
References vecops::fb::window::generateHamm(), and alg::size().
Referenced by generateHamm().
generateHamm() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::generateHamm (DataType *const output, SizeType size)
Definition at line 492 of file fallback.h.
generateHanning() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::window::generateHanning (DataType *const output, SizeType size)
Definition at line 510 of file fallback.h.
References vecops::fb::window::generateHanning(), and alg::size().
Referenced by generateHanning().
generateHanning() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::window::generateHanning (DataType *const output, SizeType size)
Definition at line 510 of file fallback.h.