Limes: vecops::fft Namespace Reference
vecops::fft Namespace Reference
Functions
static const consteval char *const getImplementationName () noexcept
consteval bool isUsingFallback () noexcept
consteval bool isUsingFFTW () noexcept
consteval bool isUsingIPP () noexcept
consteval bool isUsingVDSP () noexcept
Function Documentation
getImplementationName()
static const consteval char* const vecops::fft::getImplementationName () static noexcept
Definition at line 64 of file limes_fft.h.
References isUsingFFTW(), isUsingIPP(), and isUsingVDSP().
isUsingFallback()
consteval bool vecops::fft::isUsingFallback () noexcept
Definition at line 57 of file limes_fft.h.
References isUsingFFTW(), isUsingIPP(), and isUsingVDSP().
isUsingFFTW()
consteval bool vecops::fft::isUsingFFTW () noexcept
Definition at line 38 of file limes_fft.h.
Referenced by getImplementationName(), isUsingFallback(), isUsingIPP(), and isUsingVDSP().
isUsingIPP()
consteval bool vecops::fft::isUsingIPP () noexcept
Definition at line 52 of file limes_fft.h.
References isUsingFFTW(), and vecops::isUsingIPP().
Referenced by getImplementationName(), and isUsingFallback().
isUsingVDSP()
consteval bool vecops::fft::isUsingVDSP () noexcept
Definition at line 47 of file limes_fft.h.
References isUsingFFTW(), and vecops::isUsingVDSP().
Referenced by getImplementationName(), and isUsingFallback().