Limes: vecops Namespace Reference
vecops Namespace Reference
Namespaces
detail
fb
fft
fftw
pommier
window
Classes
class FallbackFFT
class FFT
class FFTImpl
class FFTW_FFT
class IPP_FFT
class ScopedFlushToZero
class ScopedNoDenormals
class vDSP_FFT
Typedefs
template<bool Value>
using ConditionalType = std::conditional_t< Value, std::true_type, std::false_type >
template<typename DataType >
using is_double_type = ConditionalType< std::is_same_v< DataType, double > >
template<typename DataType >
using is_float_type = ConditionalType< std::is_same_v< DataType, float > >
template<typename DataType >
using is_signed_32_bit_type = ConditionalType< std::is_integral_v< DataType > &&std::is_signed_v< DataType > &&std::numeric_limits< DataType >::digits==32 >
template<typename DataType >
using is_signed_int = ConditionalType< std::is_integral_v< DataType > &&std::is_signed_v< DataType > &&std::numeric_limits< DataType >::digits==32 >
template<typename DataType >
using is_unsigned_int = ConditionalType< std::is_integral_v< DataType > &&! std::is_signed_v< DataType > &&std::numeric_limits< DataType >::digits==32 >
Functions
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void abs (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void abs (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void absAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void absAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void add (DataType *const data, SizeType size, DataType constantToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void add (DataType *const data, SizeType size, DataType constantToAdd)
template<Scalar DataType, Integral SizeType>
void add (DataType *const dataAndDest, SizeType size, const DataType *const dataToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void add (DataType *const dataAndDest, SizeType size, const DataType *const dataToAdd)
template<Scalar DataType, Integral SizeType>
void addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToAdd)
template<Scalar DataType, Integral SizeType>
void addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToAdd)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyRamp (DataType *const dataAndDest, SizeType size, DataType startValue, DataType endValue)
template<Scalar DataType, Integral SizeType>
void applyRamp (DataType *const dataAndDest, SizeType size, DataType startValue, DataType endValue)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void applyRampAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType startValue, DataType endValue)
template<Scalar DataType, Integral SizeType>
void applyRampAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType startValue, DataType endValue)
LIMES_EXPORT bool areDenormalsDisabled () noexcept
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void cartesianInterleavedToMagnitudes (DataType *const mag, const DataType *const src, SizeType size)
template<Scalar DataType, Integral SizeType>
void cartesianInterleavedToMagnitudes (DataType *const mag, const DataType *const src, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void cartesianToMagnitudes (DataType *const mag, const DataType *const real, const DataType *const imag, SizeType size)
template<Scalar DataType, Integral SizeType>
void cartesianToMagnitudes (DataType *const mag, const DataType *const real, const DataType *const imag, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void cartesianToPolar (DataType *const mag, DataType *const phase, const DataType *const real, const DataType *const imag, SizeType size)
template<Scalar DataType, Integral SizeType>
void cartesianToPolar (DataType *const mag, DataType *const phase, const DataType *const real, const DataType *const imag, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void catesianInterleavedToPolar (DataType *const mag, DataType *const phase, const DataType *const src, SizeType size)
template<Scalar DataType, Integral SizeType>
void catesianInterleavedToPolar (DataType *const mag, DataType *const phase, const DataType *const src, SizeType size)
template<Scalar DataType, Integral SizeType>
void clear (DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void clear (DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void clip (DataType *const dataAndDest, SizeType size, DataType lowClip, DataType hiClip)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void clip (DataType *const dataAndDest, SizeType size, DataType lowClip=-1, DataType hiClip=1)
template<Scalar DataType, Integral SizeType>
void clipAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType lowClip, DataType hiClip)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void clipAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType lowClip=-1, DataType hiClip=1)
template<Scalar DataType1, Scalar DataType2>
static void convert (DataType1 *const dest, const DataType2 *const source, int size)
template<Scalar DataType1, Scalar DataType2, Integral SizeType>
static void convert (DataType1 *const dest, const DataType2 *const source, SizeType size)
template<>
void convert (double *const dest, const float *const source, int size)
template<>
void convert (float *const dest, const double *const source, int size)
template<Scalar DataType, Integral SizeType>
void copy (DataType *const dest, const DataType *const source, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void copy (DataType *const dest, const DataType *const source, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT int countZeroCrossings (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
int countZeroCrossings (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
LIMES_EXPORT void deinterleave (DataType *const *const output, const DataType *const interleavedData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
void deinterleave (DataType *const *const output, const DataType *const interleavedData, SizeType1 numChannels, SizeType2 numSamples)
LIMES_EXPORT void disableDenormalisedNumberSupport (bool shouldDisable=true) noexcept
template<Scalar DataType, Integral SizeType>
void divide (DataType *const data, SizeType size, DataType constantToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void divide (DataType *const data, SizeType size, DataType constantToDivide)
template<Scalar DataType, Integral SizeType>
void divide (DataType *const dataAndDest, SizeType size, const DataType *const dataToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void divide (DataType *const dataAndDest, SizeType size, const DataType *const dataToDivide)
template<Scalar DataType, Integral SizeType>
void divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToDivide)
template<Scalar DataType, Integral SizeType>
void divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivide)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivide)
template<Scalar DataType, Integral SizeType>
void divideInv (DataType *const data, SizeType size, DataType constantToDivideFrom)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void divideInv (DataType *const data, SizeType size, DataType constantToDivideFrom)
template<Scalar DataType, Integral SizeType>
void divideInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivideFrom)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void divideInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivideFrom)
template<Scalar DataType, Integral SizeType>
DataType dotProduct (const DataType *const vecA, const DataType *const vecB, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType dotProduct (const DataType *const vecA, const DataType *const vecB, SizeType size)
LIMES_EXPORT void enableFlushToZeroMode (bool shouldEnable=true) noexcept
template<bool IsDouble>
LIMES_NO_EXPORT void fftw_load_wisdom ()
template<bool IsDouble>
LIMES_NO_EXPORT void fftw_save_wisdom ()
template<Scalar DataType, Integral SizeType>
void fill (DataType *const data, SizeType size, DataType constantToFill)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void fill (DataType *const data, SizeType size, DataType constantToFill)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void generateRamp (DataType *const output, SizeType size, DataType startValue, DataType endValue)
template<Scalar DataType, Integral SizeType>
void generateRamp (DataType *const output, SizeType size, DataType startValue, DataType endValue)
static LIMES_EXPORT const consteval char *const getImplementationName () noexcept
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
LIMES_EXPORT void interleave (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
void interleave (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType>
void invSquareRoot (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void invSquareRoot (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void invSquareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void invSquareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
LIMES_EXPORT bool isFlushToZeroEnabled () noexcept
LIMES_EXPORT consteval bool isUsingFallback () noexcept
LIMES_EXPORT consteval bool isUsingIPP () noexcept
LIMES_EXPORT consteval bool isUsingMIPP () noexcept
LIMES_EXPORT consteval bool isUsingPommierExtensions () noexcept
LIMES_EXPORT consteval bool isUsingVDSP () noexcept
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType max (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType max (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_EXPORT void max (const DataType *const data, SizeType size, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType, Integral IndexType>
void max (const DataType *const data, SizeType size, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType maxAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType maxAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_EXPORT void maxAbs (const DataType *const data, SizeType size, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType, Integral IndexType>
void maxAbs (const DataType *const data, SizeType size, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType mean (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType mean (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType min (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType min (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_EXPORT void min (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex)
template<Scalar DataType, Integral SizeType, Integral IndexType>
void min (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType minAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType minAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_EXPORT void minAbs (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex)
template<Scalar DataType, Integral SizeType, Integral IndexType>
void minAbs (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void minMax (const DataType *const data, SizeType size, DataType &minValue, DataType &maxValue)
template<Scalar DataType, Integral SizeType>
void minMax (const DataType *const data, SizeType size, DataType &minValue, DataType &maxValue)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_EXPORT void minMax (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType, Integral IndexType>
void minMax (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void minMaxAbs (const DataType *const data, SizeType size, DataType &minValue, DataType &maxValue)
template<Scalar DataType, Integral SizeType>
void minMaxAbs (const DataType *const data, SizeType size, DataType &minValue, DataType &maxValue)
template<Scalar DataType, Integral SizeType, Integral IndexType>
LIMES_EXPORT void minMaxAbs (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType, Integral IndexType>
void minMaxAbs (const DataType *const data, SizeType size, DataType &minValue, IndexType &minIndex, DataType &maxValue, IndexType &maxIndex)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
LIMES_EXPORT void mix (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType1, Integral SizeType2>
void mix (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
template<Scalar DataType, Integral SizeType>
void multiply (DataType *const data, SizeType size, DataType constantToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void multiply (DataType *const data, SizeType size, DataType constantToMultiply)
template<Scalar DataType, Integral SizeType>
void multiply (DataType *const dataAndDest, SizeType size, const DataType *const dataToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void multiply (DataType *const dataAndDest, SizeType size, const DataType *const dataToMultiply)
template<Scalar DataType, Integral SizeType>
void multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToMultiply)
template<Scalar DataType, Integral SizeType>
void multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToMultiply)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void negate (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void negate (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void negateAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void negateAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void polarToCartesian (DataType *const real, DataType *const imag, const DataType *const mag, const DataType *const phase, SizeType size)
template<Scalar DataType, Integral SizeType>
void polarToCartesian (DataType *const real, DataType *const imag, const DataType *const mag, const DataType *const phase, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void polarToCartesianInterleaved (DataType *const dest, const DataType *const mag, const DataType *const phase, SizeType size)
template<Scalar DataType, Integral SizeType>
void polarToCartesianInterleaved (DataType *const dest, const DataType *const mag, const DataType *const phase, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType range (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType range (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType rangeAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType rangeAbs (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void reverse (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void reverse (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void reverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void reverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType rms (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType rms (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void sort (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void sort (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void sortAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void sortAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void sortReverse (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void sortReverse (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void sortReverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void sortReverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void square (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void square (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void squareAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void squareAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void squareRoot (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void squareRoot (DataType *const dataAndDest, SizeType size)
template<Scalar DataType, Integral SizeType>
void squareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void squareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void subtract (DataType *const data, SizeType size, DataType constantToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void subtract (DataType *const data, SizeType size, DataType constantToSubtract)
template<Scalar DataType, Integral SizeType>
void subtract (DataType *const dataAndDest, SizeType size, const DataType *const dataToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void subtract (DataType *const dataAndDest, SizeType size, const DataType *const dataToSubtract)
template<Scalar DataType, Integral SizeType>
void subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToSubtract)
template<Scalar DataType, Integral SizeType>
void subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtract)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtract)
template<Scalar DataType, Integral SizeType>
void subtractInv (DataType *const data, SizeType size, DataType constantToSubtractFrom)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void subtractInv (DataType *const data, SizeType size, DataType constantToSubtractFrom)
template<Scalar DataType, Integral SizeType>
void subtractInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtractFrom)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void subtractInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtractFrom)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT DataType sum (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
DataType sum (const DataType *const data, SizeType size)
template<Scalar DataType, Integral SizeType>
void swap (DataType *const vecA, DataType *const vecB, SizeType size)
template<Scalar DataType, Integral SizeType>
LIMES_EXPORT void swap (DataType *const vecA, DataType *const vecB, SizeType size)
Variables
static constexpr LIMES_NO_EXPORT auto alg_hint_type = ippAlgHintFast
static constexpr LIMES_NO_EXPORT auto integer_scale_factor = 0
template<typename T >
concept Integral = std::is_integral_v<T>
template<typename T >
concept Scalar = std::is_scalar_v<T>
template<Scalar SampleType>
constexpr LIMES_NO_EXPORT SampleType shiftAmount = SampleType (0.000001)
Typedef Documentation
ConditionalType
template<bool Value> using vecops::ConditionalType = typedef std::conditional_t<Value, std::true_type, std::false_type>
Definition at line 29 of file ipp.h.
is_double_type
template<typename DataType > using vecops::is_double_type = typedef ConditionalType<std::is_same_v<DataType, double> >
Definition at line 36 of file ipp.h.
is_float_type
template<typename DataType > using vecops::is_float_type = typedef ConditionalType<std::is_same_v<DataType, float> >
Definition at line 33 of file ipp.h.
is_signed_32_bit_type
template<typename DataType > using vecops::is_signed_32_bit_type = typedef ConditionalType<std::is_integral_v<DataType> && std::is_signed_v<DataType> && std::numeric_limits<DataType>::digits == 32>
Definition at line 40 of file vdsp.h.
is_signed_int
template<typename DataType > using vecops::is_signed_int = typedef ConditionalType<std::is_integral_v<DataType> && std::is_signed_v<DataType> && std::numeric_limits<DataType>::digits == 32>
Definition at line 39 of file ipp.h.
is_unsigned_int
template<typename DataType > using vecops::is_unsigned_int = typedef ConditionalType<std::is_integral_v<DataType> && ! std::is_signed_v<DataType> && std::numeric_limits<DataType>::digits == 32>
Definition at line 42 of file ipp.h.
Function Documentation
abs() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::abs (DataType *const dataAndDest, SizeType size)
Definition at line 293 of file fallback.h.
References vecops::fb::abs(), and alg::size().
Referenced by abs(), vecops::fb::absAndCopy(), vecops::fb::maxAbs(), and vecops::fb::minAbs().
abs() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::abs (DataType *const dataAndDest, SizeType size)
Definition at line 293 of file fallback.h.
absAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::absAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 299 of file fallback.h.
References vecops::fb::abs(), vecops::fb::absAndCopy(), and alg::size().
Referenced by absAndCopy().
absAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::absAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 299 of file fallback.h.
add() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::add (DataType *const data, SizeType size, DataType constantToAdd)
Definition at line 60 of file fallback.h.
Referenced by ds::scalar_vector< Sampletype >::add(), ds::scalar_vector< Sampletype >::addFrom(), ds::scalar_vector< Sampletype >::addTo(), math::Fraction< ValueType >::operator+(), and math::Fraction< ValueType >::operator+=().
add() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::add (DataType *const data, SizeType size, DataType constantToAdd)
Definition at line 60 of file fallback.h.
References vecops::fb::add(), and alg::size().
Referenced by ds::scalar_vector< Sampletype >::add(), add(), ds::scalar_vector< Sampletype >::addFrom(), ds::scalar_vector< Sampletype >::addTo(), vecops::fb::mix(), math::Fraction< ValueType >::operator+(), and math::Fraction< ValueType >::operator+=().
add() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::add (DataType *const dataAndDest, SizeType size, const DataType *const dataToAdd)
Definition at line 66 of file fallback.h.
add() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::add (DataType *const dataAndDest, SizeType size, const DataType *const dataToAdd)
Definition at line 66 of file fallback.h.
References vecops::fb::add(), and alg::size().
addAndCopy() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToAdd)
Definition at line 78 of file fallback.h.
addAndCopy() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToAdd)
Definition at line 78 of file fallback.h.
References vecops::fb::addAndCopy(), and alg::size().
addAndCopy() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToAdd)
Definition at line 72 of file fallback.h.
addAndCopy() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::addAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToAdd)
Definition at line 72 of file fallback.h.
References vecops::fb::addAndCopy(), and alg::size().
Referenced by addAndCopy().
applyRamp() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::applyRamp (DataType *const dataAndDest, SizeType size, DataType startValue, DataType endValue)
Definition at line 457 of file fallback.h.
References vecops::fb::applyRamp(), and alg::size().
Referenced by applyRamp().
applyRamp() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::applyRamp (DataType *const dataAndDest, SizeType size, DataType startValue, DataType endValue)
Definition at line 457 of file fallback.h.
applyRampAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::applyRampAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType startValue, DataType endValue)
Definition at line 463 of file fallback.h.
References vecops::fb::applyRampAndCopy(), and alg::size().
Referenced by applyRampAndCopy().
applyRampAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::applyRampAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType startValue, DataType endValue)
Definition at line 463 of file fallback.h.
areDenormalsDisabled()
LIMES_EXPORT bool vecops::areDenormalsDisabled () noexcept
cartesianInterleavedToMagnitudes() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::cartesianInterleavedToMagnitudes (DataType *const mag, const DataType *const src, SizeType size)
Definition at line 562 of file fallback.h.
References vecops::fb::cartesianInterleavedToMagnitudes(), and alg::size().
Referenced by cartesianInterleavedToMagnitudes().
cartesianInterleavedToMagnitudes() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::cartesianInterleavedToMagnitudes (DataType *const mag, const DataType *const src, SizeType size)
Definition at line 562 of file fallback.h.
cartesianToMagnitudes() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::cartesianToMagnitudes (DataType *const mag, const DataType *const real, const DataType *const imag, SizeType size)
Definition at line 556 of file fallback.h.
References vecops::fb::cartesianToMagnitudes(), and alg::size().
Referenced by cartesianToMagnitudes().
cartesianToMagnitudes() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::cartesianToMagnitudes (DataType *const mag, const DataType *const real, const DataType *const imag, SizeType size)
Definition at line 556 of file fallback.h.
cartesianToPolar() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::cartesianToPolar (DataType *const mag, DataType *const phase, const DataType *const real, const DataType *const imag, SizeType size)
Definition at line 544 of file fallback.h.
References vecops::fb::cartesianToPolar(), and alg::size().
Referenced by cartesianToPolar().
cartesianToPolar() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::cartesianToPolar (DataType *const mag, DataType *const phase, const DataType *const real, const DataType *const imag, SizeType size)
Definition at line 544 of file fallback.h.
catesianInterleavedToPolar() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::catesianInterleavedToPolar (DataType *const mag, DataType *const phase, const DataType *const src, SizeType size)
Definition at line 550 of file fallback.h.
References vecops::fb::catesianInterleavedToPolar(), and alg::size().
Referenced by catesianInterleavedToPolar().
catesianInterleavedToPolar() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::catesianInterleavedToPolar (DataType *const mag, DataType *const phase, const DataType *const src, SizeType size)
Definition at line 550 of file fallback.h.
clear() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::clear (DataType *const data, SizeType size)
Definition at line 35 of file fallback.h.
Referenced by ds::scalar_vector< Sampletype >::zero().
clear() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::clear (DataType *const data, SizeType size)
Definition at line 35 of file fallback.h.
References vecops::fb::clear(), vecops::fb::fill(), and alg::size().
Referenced by clear(), and ds::scalar_vector< Sampletype >::zero().
clip() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::clip (DataType *const dataAndDest, SizeType size, DataType lowClip, DataType hiClip)
Definition at line 317 of file fallback.h.
clip() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::clip (DataType *const dataAndDest, SizeType size, DataType lowClip = -1, DataType hiClip = 1)
Definition at line 317 of file fallback.h.
References vecops::fb::clip(), vecops::fb::max(), vecops::fb::min(), and alg::size().
Referenced by clip().
clipAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::clipAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType lowClip, DataType hiClip)
Definition at line 323 of file fallback.h.
clipAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::clipAndCopy (DataType *const dest, const DataType *const data, SizeType size, DataType lowClip = -1, DataType hiClip = 1)
Definition at line 323 of file fallback.h.
References vecops::fb::clipAndCopy(), vecops::fb::max(), vecops::fb::min(), and alg::size().
Referenced by clipAndCopy().
convert() [1/4]
template<Scalar DataType1, Scalar DataType2> static void vecops::convert (DataType1 *const dest, const DataType2 *const source, int size) static
Definition at line 124 of file limes_vecops.h.
References alg::size().
convert() [2/4]
template<Scalar DataType1, Scalar DataType2, Integral SizeType> static void vecops::convert (DataType1 *const dest, const DataType2 *const source, SizeType size) static
Definition at line 131 of file limes_vecops.h.
References convert(), and alg::size().
convert() [3/4]
template<> void vecops::convert (double *const dest, const float *const source, int size)
Definition at line 98 of file vdsp.h.
References alg::size().
convert() [4/4]
template<> void vecops::convert (float *const dest, const double *const source, int size)
Definition at line 92 of file vdsp.h.
References alg::size().
Referenced by convert().
copy() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::copy (DataType *const dest, const DataType *const source, SizeType size)
Definition at line 41 of file fallback.h.
Referenced by threads::detail::NonRealtimeMutatableObject< ObjectType >::acquire_write(), ds::scalar_vector< Sampletype >::copyFrom(), ds::scalar_vector< Sampletype >::copyTo(), and threads::detail::NonRealtimeMutatableObject< ObjectType >::release_write().
copy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::copy (DataType *const dest, const DataType *const source, SizeType size)
Definition at line 41 of file fallback.h.
References vecops::fb::copy(), and alg::size().
Referenced by threads::detail::NonRealtimeMutatableObject< ObjectType >::acquire_write(), copy(), ds::scalar_vector< Sampletype >::copyFrom(), ds::scalar_vector< Sampletype >::copyTo(), vecops::fb::deinterleave(), vecops::fb::interleave(), vecops::fb::mix(), threads::detail::NonRealtimeMutatableObject< ObjectType >::release_write(), vecops::fb::reverseAndCopy(), vecops::fb::sortAndCopy(), and vecops::fb::sortReverseAndCopy().
countZeroCrossings() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT int vecops::countZeroCrossings (const DataType *const data, SizeType size)
Definition at line 441 of file fallback.h.
References vecops::fb::countZeroCrossings(), and alg::size().
Referenced by countZeroCrossings().
countZeroCrossings() [2/2]
template<Scalar DataType, Integral SizeType> int vecops::countZeroCrossings (const DataType *const data, SizeType size)
Definition at line 441 of file fallback.h.
deinterleave() [1/2]
template<Scalar DataType, Integral SizeType1, Integral SizeType2> LIMES_EXPORT void vecops::deinterleave (DataType *const *const output, const DataType *const interleavedData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 282 of file fallback.h.
References vecops::fb::copy(), and vecops::fb::deinterleave().
Referenced by deinterleave().
deinterleave() [2/2]
template<Scalar DataType, Integral SizeType1, Integral SizeType2> void vecops::deinterleave (DataType *const *const output, const DataType *const interleavedData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 282 of file fallback.h.
disableDenormalisedNumberSupport()
LIMES_EXPORT void vecops::disableDenormalisedNumberSupport (bool shouldDisable = true) noexcept
divide() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::divide (DataType *const data, SizeType size, DataType constantToDivide)
Definition at line 159 of file fallback.h.
Referenced by ds::scalar_vector< Sampletype >::divide(), ds::scalar_vector< Sampletype >::divideFrom(), ds::scalar_vector< Sampletype >::divideTo(), math::Fraction< ValueType >::operator/(), and math::Fraction< ValueType >::operator/=().
divide() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::divide (DataType *const data, SizeType size, DataType constantToDivide)
Definition at line 159 of file fallback.h.
References vecops::fb::divide(), and alg::size().
Referenced by ds::scalar_vector< Sampletype >::divide(), divide(), ds::scalar_vector< Sampletype >::divideFrom(), ds::scalar_vector< Sampletype >::divideTo(), math::Fraction< ValueType >::operator/(), and math::Fraction< ValueType >::operator/=().
divide() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::divide (DataType *const dataAndDest, SizeType size, const DataType *const dataToDivide)
Definition at line 165 of file fallback.h.
divide() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::divide (DataType *const dataAndDest, SizeType size, const DataType *const dataToDivide)
Definition at line 165 of file fallback.h.
References vecops::fb::divide(), and alg::size().
divideAndCopy() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToDivide)
Definition at line 177 of file fallback.h.
divideAndCopy() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToDivide)
Definition at line 177 of file fallback.h.
References vecops::fb::divideAndCopy(), and alg::size().
divideAndCopy() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivide)
Definition at line 171 of file fallback.h.
divideAndCopy() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::divideAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivide)
Definition at line 171 of file fallback.h.
References vecops::fb::divideAndCopy(), and alg::size().
Referenced by divideAndCopy().
divideInv() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::divideInv (DataType *const data, SizeType size, DataType constantToDivideFrom)
Definition at line 183 of file fallback.h.
divideInv() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::divideInv (DataType *const data, SizeType size, DataType constantToDivideFrom)
Definition at line 183 of file fallback.h.
References vecops::fb::divideInv(), and alg::size().
Referenced by divideInv().
divideInvAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::divideInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivideFrom)
Definition at line 189 of file fallback.h.
divideInvAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::divideInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToDivideFrom)
Definition at line 189 of file fallback.h.
References vecops::fb::divideInvAndCopy(), and alg::size().
Referenced by divideInvAndCopy().
dotProduct() [1/2]
template<Scalar DataType, Integral SizeType> DataType vecops::dotProduct (const DataType *const vecA, const DataType *const vecB, SizeType size)
Definition at line 150 of file fallback.h.
dotProduct() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::dotProduct (const DataType *const vecA, const DataType *const vecB, SizeType size)
Definition at line 150 of file fallback.h.
References vecops::fb::dotProduct(), and alg::size().
Referenced by dotProduct().
enableFlushToZeroMode()
LIMES_EXPORT void vecops::enableFlushToZeroMode (bool shouldEnable = true) noexcept
fftw_load_wisdom()
template<bool IsDouble> LIMES_NO_EXPORT void vecops::fftw_load_wisdom ()
fftw_save_wisdom()
template<bool IsDouble> LIMES_NO_EXPORT void vecops::fftw_save_wisdom ()
fill() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::fill (DataType *const data, SizeType size, DataType constantToFill)
Definition at line 29 of file fallback.h.
Referenced by ds::scalar_vector< Sampletype >::fill().
fill() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::fill (DataType *const data, SizeType size, DataType constantToFill)
Definition at line 29 of file fallback.h.
References vecops::fb::fill(), and alg::size().
Referenced by vecops::fb::clear(), ds::scalar_vector< Sampletype >::fill(), and fill().
generateRamp() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::generateRamp (DataType *const output, SizeType size, DataType startValue, DataType endValue)
Definition at line 451 of file fallback.h.
References vecops::fb::generateRamp(), and alg::size().
Referenced by generateRamp().
generateRamp() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::generateRamp (DataType *const output, SizeType size, DataType startValue, DataType endValue)
Definition at line 451 of file fallback.h.
getImplementationName()
static LIMES_EXPORT const consteval char* const vecops::getImplementationName () static noexcept
Definition at line 504 of file limes_vecops.h.
References isUsingIPP(), isUsingMIPP(), and isUsingVDSP().
interleave() [1/2]
template<Scalar DataType, Integral SizeType1, Integral SizeType2> LIMES_EXPORT void vecops::interleave (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 276 of file fallback.h.
References vecops::fb::copy(), and vecops::fb::interleave().
Referenced by interleave().
interleave() [2/2]
template<Scalar DataType, Integral SizeType1, Integral SizeType2> void vecops::interleave (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 276 of file fallback.h.
invSquareRoot() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::invSquareRoot (DataType *const dataAndDest, SizeType size)
Definition at line 223 of file fallback.h.
invSquareRoot() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::invSquareRoot (DataType *const dataAndDest, SizeType size)
Definition at line 223 of file fallback.h.
References vecops::fb::invSquareRoot(), vecops::fb::quake3_fast_inv_sqrt(), and alg::size().
Referenced by invSquareRoot().
invSquareRootAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::invSquareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 229 of file fallback.h.
invSquareRootAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::invSquareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 229 of file fallback.h.
References vecops::fb::invSquareRootAndCopy(), vecops::fb::quake3_fast_inv_sqrt(), and alg::size().
Referenced by invSquareRootAndCopy().
isFlushToZeroEnabled()
LIMES_EXPORT bool vecops::isFlushToZeroEnabled () noexcept
isUsingFallback()
LIMES_EXPORT consteval bool vecops::isUsingFallback () noexcept
Definition at line 496 of file limes_vecops.h.
References isUsingIPP(), isUsingMIPP(), and isUsingVDSP().
isUsingIPP()
LIMES_EXPORT consteval bool vecops::isUsingIPP () noexcept
Definition at line 478 of file limes_vecops.h.
Referenced by getImplementationName(), isUsingFallback(), and vecops::fft::isUsingIPP().
isUsingMIPP()
LIMES_EXPORT consteval bool vecops::isUsingMIPP () noexcept
Definition at line 487 of file limes_vecops.h.
Referenced by getImplementationName(), and isUsingFallback().
isUsingPommierExtensions()
LIMES_EXPORT consteval bool vecops::isUsingPommierExtensions () noexcept
Definition at line 516 of file limes_vecops.h.
isUsingVDSP()
LIMES_EXPORT consteval bool vecops::isUsingVDSP () noexcept
Definition at line 469 of file limes_vecops.h.
Referenced by getImplementationName(), isUsingFallback(), and vecops::fft::isUsingVDSP().
max() [1/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::max (const DataType *const data, SizeType size)
Definition at line 329 of file fallback.h.
References vecops::fb::max(), and alg::size().
Referenced by math::Fraction< ValueType >::leastCommonDenominatorWith(), math::limit(), max(), math::middleOfThree(), math::Random::next(), math::Fraction< ValueType >::reduce(), ds::basic_vector< SampleType, std::allocator< SampleType > >::reserve(), and math::geometry::Triangle< ValueType >::Triangle().
max() [2/4]
template<Scalar DataType, Integral SizeType> DataType vecops::max (const DataType *const data, SizeType size)
Definition at line 329 of file fallback.h.
Referenced by math::Fraction< ValueType >::leastCommonDenominatorWith(), math::limit(), math::middleOfThree(), math::Random::next(), math::Fraction< ValueType >::reduce(), ds::basic_vector< SampleType, std::allocator< SampleType > >::reserve(), and math::geometry::Triangle< ValueType >::Triangle().
max() [3/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_EXPORT void vecops::max (const DataType *const data, SizeType size, DataType & maxValue, IndexType & maxIndex)
Definition at line 335 of file fallback.h.
References vecops::fb::max(), and alg::size().
Referenced by vecops::fb::clip(), vecops::fb::clipAndCopy(), vecops::fb::maxAbs(), and vecops::fb::minAbs().
max() [4/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> void vecops::max (const DataType *const data, SizeType size, DataType & maxValue, IndexType & maxIndex)
Definition at line 335 of file fallback.h.
maxAbs() [1/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::maxAbs (const DataType *const data, SizeType size)
Definition at line 341 of file fallback.h.
References vecops::fb::abs(), vecops::fb::max(), vecops::fb::maxAbs(), and alg::size().
Referenced by maxAbs(), and vecops::fb::minMaxAbs().
maxAbs() [2/4]
template<Scalar DataType, Integral SizeType> DataType vecops::maxAbs (const DataType *const data, SizeType size)
Definition at line 341 of file fallback.h.
maxAbs() [3/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_EXPORT void vecops::maxAbs (const DataType *const data, SizeType size, DataType & maxValue, IndexType & maxIndex)
Definition at line 347 of file fallback.h.
References vecops::fb::abs(), vecops::fb::maxAbs(), and alg::size().
maxAbs() [4/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> void vecops::maxAbs (const DataType *const data, SizeType size, DataType & maxValue, IndexType & maxIndex)
Definition at line 347 of file fallback.h.
mean() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::mean (const DataType *const data, SizeType size)
Definition at line 419 of file fallback.h.
References vecops::fb::mean(), alg::size(), and vecops::fb::sum().
Referenced by mean().
mean() [2/2]
template<Scalar DataType, Integral SizeType> DataType vecops::mean (const DataType *const data, SizeType size)
Definition at line 419 of file fallback.h.
min() [1/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::min (const DataType *const data, SizeType size)
Definition at line 353 of file fallback.h.
References vecops::fb::min(), and alg::size().
Referenced by math::limit(), math::middleOfThree(), min(), math::Random::next(), and math::geometry::Triangle< ValueType >::Triangle().
min() [2/4]
template<Scalar DataType, Integral SizeType> DataType vecops::min (const DataType *const data, SizeType size)
Definition at line 353 of file fallback.h.
Referenced by math::limit(), math::middleOfThree(), math::Random::next(), and math::geometry::Triangle< ValueType >::Triangle().
min() [3/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_EXPORT void vecops::min (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex)
Definition at line 359 of file fallback.h.
References vecops::fb::min(), and alg::size().
Referenced by vecops::fb::clip(), vecops::fb::clipAndCopy(), and vecops::fb::minAbs().
min() [4/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> void vecops::min (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex)
Definition at line 359 of file fallback.h.
minAbs() [1/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::minAbs (const DataType *const data, SizeType size)
Definition at line 365 of file fallback.h.
References vecops::fb::abs(), vecops::fb::max(), vecops::fb::min(), vecops::fb::minAbs(), and alg::size().
Referenced by minAbs(), and vecops::fb::minMaxAbs().
minAbs() [2/4]
template<Scalar DataType, Integral SizeType> DataType vecops::minAbs (const DataType *const data, SizeType size)
Definition at line 365 of file fallback.h.
minAbs() [3/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_EXPORT void vecops::minAbs (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex)
Definition at line 371 of file fallback.h.
References vecops::fb::abs(), vecops::fb::max(), vecops::fb::minAbs(), and alg::size().
minAbs() [4/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> void vecops::minAbs (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex)
Definition at line 371 of file fallback.h.
minMax() [1/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::minMax (const DataType *const data, SizeType size, DataType & minValue, DataType & maxValue)
Definition at line 377 of file fallback.h.
References vecops::fb::minMax(), and alg::size().
Referenced by minMax(), and vecops::fb::range().
minMax() [2/4]
template<Scalar DataType, Integral SizeType> void vecops::minMax (const DataType *const data, SizeType size, DataType & minValue, DataType & maxValue)
Definition at line 377 of file fallback.h.
minMax() [3/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_EXPORT void vecops::minMax (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex, DataType & maxValue, IndexType & maxIndex)
Definition at line 383 of file fallback.h.
References vecops::fb::minMax(), and alg::size().
minMax() [4/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> void vecops::minMax (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex, DataType & maxValue, IndexType & maxIndex)
Definition at line 383 of file fallback.h.
minMaxAbs() [1/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::minMaxAbs (const DataType *const data, SizeType size, DataType & minValue, DataType & maxValue)
Definition at line 389 of file fallback.h.
References vecops::fb::maxAbs(), vecops::fb::minAbs(), vecops::fb::minMaxAbs(), and alg::size().
Referenced by minMaxAbs(), and vecops::fb::rangeAbs().
minMaxAbs() [2/4]
template<Scalar DataType, Integral SizeType> void vecops::minMaxAbs (const DataType *const data, SizeType size, DataType & minValue, DataType & maxValue)
Definition at line 389 of file fallback.h.
minMaxAbs() [3/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> LIMES_EXPORT void vecops::minMaxAbs (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex, DataType & maxValue, IndexType & maxIndex)
Definition at line 395 of file fallback.h.
References vecops::fb::maxAbs(), vecops::fb::minAbs(), vecops::fb::minMaxAbs(), and alg::size().
minMaxAbs() [4/4]
template<Scalar DataType, Integral SizeType, Integral IndexType> void vecops::minMaxAbs (const DataType *const data, SizeType size, DataType & minValue, IndexType & minIndex, DataType & maxValue, IndexType & maxIndex)
Definition at line 395 of file fallback.h.
mix() [1/2]
template<Scalar DataType, Integral SizeType1, Integral SizeType2> LIMES_EXPORT void vecops::mix (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 429 of file fallback.h.
References vecops::fb::add(), vecops::fb::copy(), vecops::fb::mix(), and vecops::fb::multiply().
Referenced by mix().
mix() [2/2]
template<Scalar DataType, Integral SizeType1, Integral SizeType2> void vecops::mix (DataType *const output, const DataType *const *const origData, SizeType1 numChannels, SizeType2 numSamples)
Definition at line 429 of file fallback.h.
multiply() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::multiply (DataType *const data, SizeType size, DataType constantToMultiply)
Definition at line 126 of file fallback.h.
Referenced by ds::scalar_vector< Sampletype >::multiply(), ds::scalar_vector< Sampletype >::multiplyFrom(), ds::scalar_vector< Sampletype >::multiplyTo(), math::Fraction< ValueType >::operator*(), math::Fraction< ValueType >::operator*=(), and vecops::fb::polarToCartesian().
multiply() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::multiply (DataType *const data, SizeType size, DataType constantToMultiply)
Definition at line 126 of file fallback.h.
References vecops::fb::multiply(), and alg::size().
Referenced by vecops::fb::mix(), ds::scalar_vector< Sampletype >::multiply(), multiply(), ds::scalar_vector< Sampletype >::multiplyFrom(), ds::scalar_vector< Sampletype >::multiplyTo(), math::Fraction< ValueType >::operator*(), math::Fraction< ValueType >::operator*=(), and vecops::fb::polarToCartesian().
multiply() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::multiply (DataType *const dataAndDest, SizeType size, const DataType *const dataToMultiply)
Definition at line 132 of file fallback.h.
multiply() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::multiply (DataType *const dataAndDest, SizeType size, const DataType *const dataToMultiply)
Definition at line 132 of file fallback.h.
References vecops::fb::multiply(), and alg::size().
multiplyAndCopy() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToMultiply)
Definition at line 144 of file fallback.h.
multiplyAndCopy() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToMultiply)
Definition at line 144 of file fallback.h.
References vecops::fb::multiplyAndCopy(), and alg::size().
multiplyAndCopy() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToMultiply)
Definition at line 138 of file fallback.h.
multiplyAndCopy() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::multiplyAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToMultiply)
Definition at line 138 of file fallback.h.
References vecops::fb::multiplyAndCopy(), and alg::size().
Referenced by multiplyAndCopy().
negate() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::negate (DataType *const dataAndDest, SizeType size)
Definition at line 305 of file fallback.h.
References vecops::fb::negate(), and alg::size().
Referenced by negate().
negate() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::negate (DataType *const dataAndDest, SizeType size)
Definition at line 305 of file fallback.h.
negateAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::negateAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 311 of file fallback.h.
References vecops::fb::negateAndCopy(), and alg::size().
Referenced by negateAndCopy().
negateAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::negateAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 311 of file fallback.h.
polarToCartesian() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::polarToCartesian (DataType *const real, DataType *const imag, const DataType *const mag, const DataType *const phase, SizeType size)
Definition at line 532 of file fallback.h.
References multiply(), vecops::pommier::polarToCartesian(), vecops::fb::polarToCartesian(), and alg::size().
Referenced by polarToCartesian().
polarToCartesian() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::polarToCartesian (DataType *const real, DataType *const imag, const DataType *const mag, const DataType *const phase, SizeType size)
Definition at line 532 of file fallback.h.
polarToCartesianInterleaved() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::polarToCartesianInterleaved (DataType *const dest, const DataType *const mag, const DataType *const phase, SizeType size)
Definition at line 538 of file fallback.h.
References vecops::pommier::polarToCartesianInterleaved(), vecops::fb::polarToCartesianInterleaved(), and alg::size().
Referenced by polarToCartesianInterleaved().
polarToCartesianInterleaved() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::polarToCartesianInterleaved (DataType *const dest, const DataType *const mag, const DataType *const phase, SizeType size)
Definition at line 538 of file fallback.h.
range() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::range (const DataType *const data, SizeType size)
Definition at line 401 of file fallback.h.
References vecops::fb::minMax(), vecops::fb::range(), and alg::size().
Referenced by range().
range() [2/2]
template<Scalar DataType, Integral SizeType> DataType vecops::range (const DataType *const data, SizeType size)
Definition at line 401 of file fallback.h.
rangeAbs() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::rangeAbs (const DataType *const data, SizeType size)
Definition at line 407 of file fallback.h.
References vecops::fb::minMaxAbs(), vecops::fb::rangeAbs(), and alg::size().
Referenced by rangeAbs().
rangeAbs() [2/2]
template<Scalar DataType, Integral SizeType> DataType vecops::rangeAbs (const DataType *const data, SizeType size)
Definition at line 407 of file fallback.h.
reverse() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::reverse (DataType *const dataAndDest, SizeType size)
Definition at line 240 of file fallback.h.
reverse() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::reverse (DataType *const dataAndDest, SizeType size)
Definition at line 240 of file fallback.h.
References vecops::fb::reverse(), and alg::size().
Referenced by reverse(), vecops::fb::reverseAndCopy(), and vecops::fb::sortReverse().
reverseAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::reverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 246 of file fallback.h.
References vecops::fb::copy(), vecops::fb::reverse(), vecops::fb::reverseAndCopy(), and alg::size().
Referenced by reverseAndCopy().
reverseAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::reverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 246 of file fallback.h.
rms() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::rms (const DataType *const data, SizeType size)
Definition at line 435 of file fallback.h.
References vecops::fb::rms(), and alg::size().
Referenced by rms().
rms() [2/2]
template<Scalar DataType, Integral SizeType> DataType vecops::rms (const DataType *const data, SizeType size)
Definition at line 435 of file fallback.h.
sort() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::sort (DataType *const dataAndDest, SizeType size)
Definition at line 252 of file fallback.h.
References alg::size(), and vecops::fb::sort().
Referenced by sort(), vecops::fb::sortAndCopy(), and vecops::fb::sortReverse().
sort() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::sort (DataType *const dataAndDest, SizeType size)
Definition at line 252 of file fallback.h.
sortAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::sortAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 258 of file fallback.h.
References vecops::fb::copy(), alg::size(), vecops::fb::sort(), and vecops::fb::sortAndCopy().
Referenced by sortAndCopy().
sortAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::sortAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 258 of file fallback.h.
sortReverse() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::sortReverse (DataType *const dataAndDest, SizeType size)
Definition at line 264 of file fallback.h.
References vecops::fb::reverse(), alg::size(), vecops::fb::sort(), and vecops::fb::sortReverse().
Referenced by sortReverse(), and vecops::fb::sortReverseAndCopy().
sortReverse() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::sortReverse (DataType *const dataAndDest, SizeType size)
Definition at line 264 of file fallback.h.
sortReverseAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::sortReverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 270 of file fallback.h.
References vecops::fb::copy(), alg::size(), vecops::fb::sortReverse(), and vecops::fb::sortReverseAndCopy().
Referenced by sortReverseAndCopy().
sortReverseAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> void vecops::sortReverseAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 270 of file fallback.h.
square() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::square (DataType *const dataAndDest, SizeType size)
Definition at line 199 of file fallback.h.
Referenced by math::geometry::operator!=(), and math::geometry::operator==().
square() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::square (DataType *const dataAndDest, SizeType size)
Definition at line 199 of file fallback.h.
References alg::size(), and vecops::fb::square().
Referenced by math::geometry::operator!=(), math::geometry::operator==(), and square().
squareAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::squareAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 205 of file fallback.h.
squareAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::squareAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 205 of file fallback.h.
References alg::size(), and vecops::fb::squareAndCopy().
Referenced by squareAndCopy().
squareRoot() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::squareRoot (DataType *const dataAndDest, SizeType size)
Definition at line 211 of file fallback.h.
squareRoot() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::squareRoot (DataType *const dataAndDest, SizeType size)
Definition at line 211 of file fallback.h.
References alg::size(), and vecops::fb::squareRoot().
Referenced by squareRoot().
squareRootAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::squareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 217 of file fallback.h.
squareRootAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::squareRootAndCopy (DataType *const dest, const DataType *const data, SizeType size)
Definition at line 217 of file fallback.h.
References alg::size(), and vecops::fb::squareRootAndCopy().
Referenced by squareRootAndCopy().
subtract() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::subtract (DataType *const data, SizeType size, DataType constantToSubtract)
Definition at line 87 of file fallback.h.
Referenced by math::Fraction< ValueType >::operator-(), math::Fraction< ValueType >::operator-=(), ds::scalar_vector< Sampletype >::subtract(), ds::scalar_vector< Sampletype >::subtractFrom(), and ds::scalar_vector< Sampletype >::subtractTo().
subtract() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::subtract (DataType *const data, SizeType size, DataType constantToSubtract)
Definition at line 87 of file fallback.h.
References alg::size(), and vecops::fb::subtract().
Referenced by math::Fraction< ValueType >::operator-(), math::Fraction< ValueType >::operator-=(), ds::scalar_vector< Sampletype >::subtract(), subtract(), ds::scalar_vector< Sampletype >::subtractFrom(), and ds::scalar_vector< Sampletype >::subtractTo().
subtract() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::subtract (DataType *const dataAndDest, SizeType size, const DataType *const dataToSubtract)
Definition at line 93 of file fallback.h.
subtract() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::subtract (DataType *const dataAndDest, SizeType size, const DataType *const dataToSubtract)
Definition at line 93 of file fallback.h.
References alg::size(), and vecops::fb::subtract().
subtractAndCopy() [1/4]
template<Scalar DataType, Integral SizeType> void vecops::subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToSubtract)
Definition at line 105 of file fallback.h.
subtractAndCopy() [2/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, const DataType *const dataToSubtract)
Definition at line 105 of file fallback.h.
References alg::size(), and vecops::fb::subtractAndCopy().
subtractAndCopy() [3/4]
template<Scalar DataType, Integral SizeType> void vecops::subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtract)
Definition at line 99 of file fallback.h.
subtractAndCopy() [4/4]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::subtractAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtract)
Definition at line 99 of file fallback.h.
References alg::size(), and vecops::fb::subtractAndCopy().
Referenced by subtractAndCopy().
subtractInv() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::subtractInv (DataType *const data, SizeType size, DataType constantToSubtractFrom)
Definition at line 111 of file fallback.h.
subtractInv() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::subtractInv (DataType *const data, SizeType size, DataType constantToSubtractFrom)
Definition at line 111 of file fallback.h.
References alg::size(), and vecops::fb::subtractInv().
Referenced by subtractInv().
subtractInvAndCopy() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::subtractInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtractFrom)
Definition at line 117 of file fallback.h.
subtractInvAndCopy() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::subtractInvAndCopy (DataType *const dest, const DataType *const origData, SizeType size, DataType constantToSubtractFrom)
Definition at line 117 of file fallback.h.
References alg::size(), and vecops::fb::subtractInvAndCopy().
Referenced by subtractInvAndCopy().
sum() [1/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT DataType vecops::sum (const DataType *const data, SizeType size)
Definition at line 413 of file fallback.h.
References alg::size(), and vecops::fb::sum().
Referenced by vecops::fb::mean(), and sum().
sum() [2/2]
template<Scalar DataType, Integral SizeType> DataType vecops::sum (const DataType *const data, SizeType size)
Definition at line 413 of file fallback.h.
swap() [1/2]
template<Scalar DataType, Integral SizeType> void vecops::swap (DataType *const vecA, DataType *const vecB, SizeType size)
Definition at line 47 of file fallback.h.
Referenced by memory::ReferenceCountedObjectPtr< ObjectType >::operator=().
swap() [2/2]
template<Scalar DataType, Integral SizeType> LIMES_EXPORT void vecops::swap (DataType *const vecA, DataType *const vecB, SizeType size)
Definition at line 47 of file fallback.h.
References alg::size(), and vecops::fb::swap().
Referenced by memory::ReferenceCountedObjectPtr< ObjectType >::operator=(), and swap().
Variable Documentation
alg_hint_type
constexpr LIMES_NO_EXPORT auto vecops::alg_hint_type = ippAlgHintFast static constexpr
Definition at line 46 of file ipp.h.
integer_scale_factor
constexpr LIMES_NO_EXPORT auto vecops::integer_scale_factor = 0 static constexpr
Definition at line 45 of file ipp.h.
Integral
template<typename T > concept vecops::Integral = std::is_integral_v<T>
Definition at line 106 of file limes_vecops.h.
Scalar
template<typename T > concept vecops::Scalar = std::is_scalar_v<T>
Definition at line 103 of file limes_vecops.h.
shiftAmount
template<Scalar SampleType> constexpr LIMES_NO_EXPORT SampleType vecops::shiftAmount = SampleType (0.000001) constexpr
Definition at line 26 of file fft_common.h.