Limes: time Namespace Reference
time Namespace Reference
Classes
class Date
class DateTime
class Hour
class Month
class Time
class Weekday
class Year
Typedefs
template<Clock ClockType>
using Point = std::chrono::time_point< ClockType >
using SystemClock = std::chrono::system_clock
Functions
LIMES_EXPORT consteval int build_day () noexcept
LIMES_EXPORT consteval int build_hour () noexcept
LIMES_EXPORT consteval int build_minute () noexcept
LIMES_EXPORT consteval int build_month () noexcept
LIMES_EXPORT consteval int build_second () noexcept
LIMES_EXPORT consteval int build_year () noexcept
template<Clock InputClock, Clock OutputClock>
LIMES_EXPORT Point< OutputClock > convertClockTimePoints (const Point< InputClock > &inputTime)
template<Clock ClockType>
LIMES_EXPORT Point< ClockType > fromTimeObj (std::time_t time)
template<Clock ClockType>
LIMES_EXPORT Point< ClockType > fromTimeObj (std::tm &timeObj)
template<Clock InputClock>
LIMES_EXPORT Point< SystemClock > toSystemTime (const Point< InputClock > &inputTime)
template<Clock ClockType>
LIMES_EXPORT std::tm toTimeObj (const Point< ClockType > &inputTime)
Variables
template<typename T >
concept Clock
Typedef Documentation
Point
template<Clock ClockType> using time::Point = typedef std::chrono::time_point<ClockType>
Definition at line 38 of file time_utils.h.
SystemClock
using time::SystemClock = typedef std::chrono::system_clock
Definition at line 40 of file time_utils.h.
Function Documentation
build_day()
LIMES_EXPORT consteval int time::build_day () noexcept
Definition at line 58 of file build_date.h.
Referenced by time::Date::getCompilationDate(), and time::Weekday< StartWeekOnSunday >::getCompilationWeekday().
build_hour()
LIMES_EXPORT consteval int time::build_hour () noexcept
Definition at line 72 of file build_date.h.
Referenced by time::Hour::getCompilationHour(), and time::Time::getCompilationTime().
build_minute()
LIMES_EXPORT consteval int time::build_minute () noexcept
Definition at line 79 of file build_date.h.
Referenced by time::Time::getCompilationTime().
build_month()
LIMES_EXPORT consteval int time::build_month () noexcept
Definition at line 39 of file build_date.h.
Referenced by time::Date::getCompilationDate(), time::Month::getCompilationMonth(), and time::Weekday< StartWeekOnSunday >::getCompilationWeekday().
build_second()
LIMES_EXPORT consteval int time::build_second () noexcept
Definition at line 86 of file build_date.h.
Referenced by time::Time::getCompilationTime().
build_year()
LIMES_EXPORT consteval int time::build_year () noexcept
Definition at line 25 of file build_date.h.
Referenced by time::Date::getCompilationDate(), time::Weekday< StartWeekOnSunday >::getCompilationWeekday(), and time::Year::getCompilationYear().
convertClockTimePoints()
template<Clock InputClock, Clock OutputClock> LIMES_EXPORT Point<OutputClock> time::convertClockTimePoints (const Point< InputClock > & inputTime)
Definition at line 43 of file time_utils.h.
fromTimeObj() [1/2]
template<Clock ClockType> LIMES_EXPORT Point<ClockType> time::fromTimeObj (std::time_t time)
Definition at line 75 of file time_utils.h.
fromTimeObj() [2/2]
template<Clock ClockType> LIMES_EXPORT Point<ClockType> time::fromTimeObj (std::tm & timeObj)
Definition at line 83 of file time_utils.h.
toSystemTime()
template<Clock InputClock> LIMES_EXPORT Point<SystemClock> time::toSystemTime (const Point< InputClock > & inputTime)
Definition at line 61 of file time_utils.h.
Referenced by toTimeObj().
toTimeObj()
template<Clock ClockType> LIMES_EXPORT std::tm time::toTimeObj (const Point< ClockType > & inputTime)
Definition at line 67 of file time_utils.h.
References toSystemTime().
Variable Documentation
Clock
template<typename T > concept time::Clock
Initial value:
= requires (T c)
{
    { c.now() } -> meta::convertible_to<std::chrono::time_point<T>>;
}
Definition at line 31 of file time_utils.h.