var namespaces_dup =
[
    [ "alg", "d2/d9f/namespacealg.html", null ],
    [ "assert", "d2/dab/namespaceassert.html", null ],
    [ "debugger", "db/d4b/namespacedebugger.html", null ],
    [ "ds", "d3/d4e/namespaceds.html", null ],
    [ "dsp", "d0/d41/namespacedsp.html", "d0/d41/namespacedsp" ],
    [ "files", "d6/d04/namespacefiles.html", null ],
    [ "func", "d9/dd6/namespacefunc.html", null ],
    [ "hash", "de/de9/namespacehash.html", "de/de9/namespacehash" ],
    [ "json", "d1/db2/namespacejson.html", null ],
    [ "locale", "de/d31/namespacelocale.html", null ],
    [ "math", "dd/d47/namespacemath.html", "dd/d47/namespacemath" ],
    [ "memory", "d4/daf/namespacememory.html", null ],
    [ "meta", "d8/db6/namespacemeta.html", null ],
    [ "midi", "da/d3d/namespacemidi.html", null ],
    [ "misc", "d9/d37/namespacemisc.html", null ],
    [ "music", "d3/d28/namespacemusic.html", "d3/d28/namespacemusic" ],
    [ "pommier", "dc/d2b/namespacepommier.html", null ],
    [ "strings", "df/dcb/namespacestrings.html", null ],
    [ "threads", "d5/d58/namespacethreads.html", "d5/d58/namespacethreads" ],
    [ "time", "d0/dfb/namespacetime.html", null ],
    [ "typelist", "dd/d4b/namespacetypelist.html", null ],
    [ "vecops", "d9/d1a/namespacevecops.html", "d9/d1a/namespacevecops" ]
];