Limes: math::Fraction< ValueType > Struct Template Reference
math::Fraction< ValueType > Struct Template Reference final
#include <Fraction.h>
Public Member Functions
constexpr Fraction ()=default
constexpr Fraction (const Fraction &)=default
template<typename T >
constexpr Fraction (const Fraction< T > &other) noexcept
constexpr Fraction (Fraction &&)=default
constexpr Fraction (ValueType num, ValueType denom) noexcept
constexpr ValueType divided () const noexcept
constexpr Fraction getReciprocal () const noexcept
template<typename T >
constexpr bool isEquivalentTo (const Fraction< T > &other) const noexcept
constexpr bool isNegative () const noexcept
constexpr ValueType leastCommonDenominatorWith (const Fraction &other) const noexcept
template<typename T >
constexpr operator T () const noexcept
constexpr bool operator!= (const Fraction &other) const noexcept
constexpr Fraction operator* (const Fraction &other) const noexcept
constexpr Fraction operator* (ValueType multiply) const noexcept
constexpr Fraction & operator*= (const Fraction &other) noexcept
constexpr Fraction & operator*= (ValueType multiply) noexcept
constexpr Fraction operator+ (const Fraction &other) const noexcept
constexpr Fraction operator+ (ValueType add) const noexcept
constexpr Fraction & operator+= (const Fraction &other) noexcept
constexpr Fraction & operator+= (ValueType add) noexcept
constexpr Fraction operator- (const Fraction &other) const noexcept
constexpr Fraction operator- (ValueType subtract) const noexcept
constexpr Fraction & operator-= (const Fraction &other) noexcept
constexpr Fraction & operator-= (ValueType subtract) noexcept
constexpr Fraction operator/ (const Fraction &other) const noexcept
constexpr Fraction operator/ (ValueType divide) const noexcept
constexpr Fraction & operator/= (const Fraction &other) noexcept
constexpr Fraction & operator/= (ValueType divide) noexcept
template<typename T >
constexpr bool operator< (const Fraction< T > &other) const noexcept
template<typename T >
constexpr bool operator< (T value) const noexcept
constexpr Fraction & operator= (const Fraction &)=default
template<typename T >
constexpr Fraction & operator= (const Fraction< T > &other) noexcept
template<typename T >
constexpr Fraction< ValueType > & operator= (const Fraction< T > &other) noexcept
constexpr Fraction & operator= (Fraction &&)=default
constexpr bool operator== (const Fraction &other) const noexcept
template<typename T >
constexpr bool operator> (const Fraction< T > &other) const noexcept
template<typename T >
constexpr bool operator> (T value) const noexcept
constexpr Fraction reduce () const noexcept
constexpr Fraction withDenominator (ValueType newDenominator) const noexcept
Public Attributes
ValueType denominator { 0 }
ValueType numerator { 0 }
Detailed Description
template<Scalar ValueType = int>
struct math::Fraction< ValueType >
Definition at line 26 of file Fraction.h.
Constructor & Destructor Documentation
Fraction() [1/5]
template<Scalar ValueType = int> constexpr math::Fraction< ValueType >::Fraction () constexpr default
Fraction() [2/5]
template<Scalar ValueType> constexpr math::Fraction< ValueType >::Fraction (ValueType num, ValueType denom) explicit constexpr noexcept
Definition at line 26 of file Fraction_impl.h.
References LIMES_ASSERT.
Fraction() [3/5]
template<Scalar ValueType> template<typename T > constexpr math::Fraction< ValueType >::Fraction (const Fraction< T > & other) explicit constexpr noexcept
Definition at line 34 of file Fraction_impl.h.
Fraction() [4/5]
template<Scalar ValueType = int> constexpr math::Fraction< ValueType >::Fraction (const Fraction< ValueType > &) constexpr default
Fraction() [5/5]
template<Scalar ValueType = int> constexpr math::Fraction< ValueType >::Fraction (Fraction< ValueType > &&) constexpr default
Member Function Documentation
divided()
template<Scalar ValueType> constexpr ValueType math::Fraction< ValueType >::divided constexpr noexcept
Definition at line 229 of file Fraction_impl.h.
References LIMES_ASSERT.
getReciprocal()
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::getReciprocal constexpr noexcept
Definition at line 275 of file Fraction_impl.h.
isEquivalentTo()
template<Scalar ValueType> template<typename T > constexpr bool math::Fraction< ValueType >::isEquivalentTo (const Fraction< T > & other) const constexpr noexcept
Definition at line 59 of file Fraction_impl.h.
isNegative()
template<Scalar ValueType> constexpr bool math::Fraction< ValueType >::isNegative constexpr noexcept
Definition at line 261 of file Fraction_impl.h.
leastCommonDenominatorWith()
template<Scalar ValueType> constexpr ValueType math::Fraction< ValueType >::leastCommonDenominatorWith (const Fraction< ValueType > & other) const constexpr noexcept
Definition at line 223 of file Fraction_impl.h.
References vecops::max().
operator T()
template<Scalar ValueType> template<typename T > constexpr math::Fraction< ValueType >::operator T constexpr noexcept
Definition at line 50 of file Fraction_impl.h.
References LIMES_ASSERT.
operator!=()
template<Scalar ValueType> constexpr bool math::Fraction< ValueType >::operator!= (const Fraction< ValueType > & other) const constexpr noexcept
Definition at line 71 of file Fraction_impl.h.
operator*() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator* (const Fraction< ValueType > & other) const constexpr noexcept
Definition at line 173 of file Fraction_impl.h.
References math::Fraction< ValueType >::numerator.
operator*() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator* (ValueType multiply) const constexpr noexcept
Definition at line 179 of file Fraction_impl.h.
References vecops::multiply().
operator*=() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator*= (const Fraction< ValueType > & other) constexpr noexcept
Definition at line 197 of file Fraction_impl.h.
operator*=() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator*= (ValueType multiply) constexpr noexcept
Definition at line 209 of file Fraction_impl.h.
References vecops::multiply().
operator+() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator+ (const Fraction< ValueType > & other) const constexpr noexcept
Definition at line 111 of file Fraction_impl.h.
References math::Fraction< ValueType >::numerator.
operator+() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator+ (ValueType add) const constexpr noexcept
Definition at line 135 of file Fraction_impl.h.
References vecops::add().
operator+=() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator+= (const Fraction< ValueType > & other) constexpr noexcept
Definition at line 147 of file Fraction_impl.h.
operator+=() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator+= (ValueType add) constexpr noexcept
Definition at line 159 of file Fraction_impl.h.
References vecops::add().
operator-() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator- (const Fraction< ValueType > & other) const constexpr noexcept
Definition at line 123 of file Fraction_impl.h.
References math::Fraction< ValueType >::numerator.
operator-() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator- (ValueType subtract) const constexpr noexcept
Definition at line 141 of file Fraction_impl.h.
References vecops::subtract().
operator-=() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator-= (const Fraction< ValueType > & other) constexpr noexcept
Definition at line 153 of file Fraction_impl.h.
operator-=() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator-= (ValueType subtract) constexpr noexcept
Definition at line 166 of file Fraction_impl.h.
References vecops::subtract().
operator/() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator/ (const Fraction< ValueType > & other) const constexpr noexcept
Definition at line 185 of file Fraction_impl.h.
References math::Fraction< ValueType >::reduce().
operator/() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::operator/ (ValueType divide) const constexpr noexcept
Definition at line 191 of file Fraction_impl.h.
References vecops::divide().
operator/=() [1/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator/= (const Fraction< ValueType > & other) constexpr noexcept
Definition at line 203 of file Fraction_impl.h.
operator/=() [2/2]
template<Scalar ValueType> constexpr Fraction< ValueType > & math::Fraction< ValueType >::operator/= (ValueType divide) constexpr noexcept
Definition at line 216 of file Fraction_impl.h.
References vecops::divide().
operator<() [1/2]
template<Scalar ValueType> template<typename T > constexpr bool math::Fraction< ValueType >::operator< (const Fraction< T > & other) const constexpr noexcept
Definition at line 88 of file Fraction_impl.h.
operator<() [2/2]
template<Scalar ValueType> template<typename T > constexpr bool math::Fraction< ValueType >::operator< (T value) const constexpr noexcept
Definition at line 105 of file Fraction_impl.h.
operator=() [1/4]
template<Scalar ValueType = int> constexpr Fraction& math::Fraction< ValueType >::operator= (const Fraction< ValueType > &) constexpr default
operator=() [2/4]
template<Scalar ValueType = int> template<typename T > constexpr Fraction& math::Fraction< ValueType >::operator= (const Fraction< T > & other) constexpr noexcept
operator=() [3/4]
template<Scalar ValueType = int> template<typename T > constexpr Fraction<ValueType>& math::Fraction< ValueType >::operator= (const Fraction< T > & other) constexpr noexcept
Definition at line 41 of file Fraction_impl.h.
operator=() [4/4]
template<Scalar ValueType = int> constexpr Fraction& math::Fraction< ValueType >::operator= (Fraction< ValueType > &&) constexpr default
operator==()
template<Scalar ValueType> constexpr bool math::Fraction< ValueType >::operator== (const Fraction< ValueType > & other) const constexpr noexcept
Definition at line 65 of file Fraction_impl.h.
operator>() [1/2]
template<Scalar ValueType> template<typename T > constexpr bool math::Fraction< ValueType >::operator> (const Fraction< T > & other) const constexpr noexcept
Definition at line 78 of file Fraction_impl.h.
operator>() [2/2]
template<Scalar ValueType> template<typename T > constexpr bool math::Fraction< ValueType >::operator> (T value) const constexpr noexcept
Definition at line 98 of file Fraction_impl.h.
reduce()
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::reduce constexpr noexcept
Definition at line 237 of file Fraction_impl.h.
References vecops::max(), and math::Fraction< ValueType >::numerator.
Referenced by math::Fraction< ValueType >::operator/().
withDenominator()
template<Scalar ValueType> constexpr Fraction< ValueType > math::Fraction< ValueType >::withDenominator (ValueType newDenominator) const constexpr noexcept
Definition at line 252 of file Fraction_impl.h.
Member Data Documentation
denominator
template<Scalar ValueType = int> ValueType math::Fraction< ValueType >::denominator { 0 }
Definition at line 98 of file Fraction.h.
numerator
template<Scalar ValueType = int> ValueType math::Fraction< ValueType >::numerator { 0 }
Definition at line 98 of file Fraction.h.
Referenced by math::Fraction< ValueType >::operator*(), math::Fraction< ValueType >::operator+(), math::Fraction< ValueType >::operator-(), and math::Fraction< ValueType >::reduce().
The documentation for this struct was generated from the following files:
Fraction.h
Fraction_impl.h