Limes: music::NoteDuration Struct Reference
music::NoteDuration Struct Reference final
#include <NoteDuration.h>
Public Member Functions
constexpr NoteDuration (int kind)
constexpr int getDuration () const noexcept
constexpr double getRatioToOtherDuration (const NoteDuration &other) const noexcept
constexpr bool hasStem () const noexcept
LIMES_CONSTEXPR_COPYABLE (NoteDuration)
LIMES_CONSTEXPR_MOVABLE (NoteDuration)
constexpr bool noteHeadIsFilled () const noexcept
constexpr bool operator!= (const NoteDuration &other) const noexcept
constexpr NoteDuration & operator++ () noexcept
constexpr NoteDuration & operator-- () noexcept
constexpr bool operator< (const NoteDuration &other) const noexcept
constexpr bool operator== (const NoteDuration &other) const noexcept
constexpr bool operator> (const NoteDuration &other) const noexcept
Detailed Description
Definition at line 24 of file NoteDuration.h.
Constructor & Destructor Documentation
NoteDuration()
constexpr music::NoteDuration::NoteDuration (int kind) explicit constexpr
Definition at line 24 of file NoteDuration_impl.h.
References math::isPowerOf2(), and LIMES_ASSERT.
Member Function Documentation
getDuration()
constexpr int music::NoteDuration::getDuration () const constexpr noexcept
Definition at line 89 of file NoteDuration_impl.h.
Referenced by music::NoteLength::getRelativeValue(), and music::NoteLength::NoteLength().
getRatioToOtherDuration()
constexpr double music::NoteDuration::getRatioToOtherDuration (const NoteDuration & other) const constexpr noexcept
Definition at line 94 of file NoteDuration_impl.h.
hasStem()
constexpr bool music::NoteDuration::hasStem () const constexpr noexcept
Definition at line 79 of file NoteDuration_impl.h.
Referenced by music::NoteLength::hasStem().
LIMES_CONSTEXPR_COPYABLE()
music::NoteDuration::LIMES_CONSTEXPR_COPYABLE (NoteDuration)
LIMES_CONSTEXPR_MOVABLE()
music::NoteDuration::LIMES_CONSTEXPR_MOVABLE (NoteDuration)
noteHeadIsFilled()
constexpr bool music::NoteDuration::noteHeadIsFilled () const constexpr noexcept
Definition at line 84 of file NoteDuration_impl.h.
Referenced by music::NoteLength::noteHeadIsFilled().
operator!=()
constexpr bool music::NoteDuration::operator!= (const NoteDuration & other) const constexpr noexcept
Definition at line 35 of file NoteDuration_impl.h.
operator++()
constexpr NoteDuration & music::NoteDuration::operator++ () constexpr noexcept
Definition at line 50 of file NoteDuration_impl.h.
operator--()
constexpr NoteDuration & music::NoteDuration::operator-- () constexpr noexcept
Definition at line 63 of file NoteDuration_impl.h.
operator<()
constexpr bool music::NoteDuration::operator< (const NoteDuration & other) const constexpr noexcept
Definition at line 45 of file NoteDuration_impl.h.
operator==()
constexpr bool music::NoteDuration::operator== (const NoteDuration & other) const constexpr noexcept
Definition at line 30 of file NoteDuration_impl.h.
operator>()
constexpr bool music::NoteDuration::operator> (const NoteDuration & other) const constexpr noexcept
Definition at line 40 of file NoteDuration_impl.h.
The documentation for this struct was generated from the following files:
NoteDuration.h
NoteDuration_impl.h