/*
 * ======================================================================================
 *  __    ____  __  __  ____  ___
 * (  )  (_  _)(  \/  )( ___)/ __)
 *  )(__  _)(_  )    (  )__) \__ \
 * (____)(____)(_/\/\_)(____)(___/
 *
 *  This file is part of the Limes open source library and is licensed under the terms of the GNU Public License.
 *
 * ======================================================================================
 */

#pragma once

#include <limes_export.h>
#include "../limes_namespace.h"
#include "../misc/preprocessor.h"
#include "./hour.h"
#include "../system/compiler_defs.h"
#include <ctime>
#include <string>
#include "./time_utils.h"
#include <time.pb.h>  // generated by protobuf

/** @file
	This file defines the Time class.
	@ingroup time
 */

LIMES_BEGIN_NAMESPACE

namespace time
{

/** This class represents a %time of day, with a specific Hour, minute, and second.
	@see Hour, DateTime
	@ingroup time
 */
class LIMES_EXPORT Time final
{
public:

	using InternalData = ::limes::core::time::proto::Time;

	/** @name Constructors */
	///@{
	/** Creates a Time object representing midnight on the hour. */
	Time() = default;

	/** Creates a Time object. */
	explicit Time (const Hour& h, int min, int sec) noexcept;

	/** Creates a Time object. */
	explicit Time (int hourIn24HourFormat, int min, int sec) noexcept;

	/** Creates a Time object from the given \c std::tm object. */
	explicit Time (const std::tm& timeObj) noexcept;

	/** Creates a Time object from the given \c std::time_t object. */
	explicit Time (std::time_t time);

	/** Creates a Time object from a \c std::chrono::time_point of any Clock type. */
	template <Clock ClockType>
	explicit Time (const Point<ClockType>& timePoint)
		: Time (toTimeObj (timePoint))
	{
	}
	///@}

	LIMES_DEFAULT_MOVABLE (Time)
	LIMES_DEFAULT_COPYABLE (Time)

	/** Returns true if this %time is between midnight and noon. */
	[[nodiscard]] bool isAM() const noexcept;

	/** Returns true if this %time is between noon and midnight. */
	[[nodiscard]] bool isPM() const noexcept;

	/** Returns true if this %time is exactly on the hour. */
	[[nodiscard]] bool isOnTheHour() const noexcept;

	/** Returns the Hour of this %time. */
	[[nodiscard]] Hour getHour() const noexcept;

	/** Returns the minute of the %hour of this %time. */
	[[nodiscard]] int getMinute() const noexcept;

	/** Returns the second of the minute of this %time. */
	[[nodiscard]] int getSecond() const noexcept;

	/** @name Greater/less than comparisons */
	///@{
	[[nodiscard]] bool isBefore (const Time& other) const noexcept;
	[[nodiscard]] bool isAfter (const Time& other) const noexcept;
	[[nodiscard]] bool operator> (const Time& other) const noexcept;
	[[nodiscard]] bool operator<(const Time& other) const noexcept;
	///@}

	/** @name Equality comparisons */
	///@{
	[[nodiscard]] bool operator== (const Time& other) const noexcept;
	[[nodiscard]] bool operator!= (const Time& other) const noexcept;
	///@}

	/** Returns true if this %time is before the current %time (agnostic of the date). */
	[[nodiscard]] bool isInPast() const noexcept;

	/** Returns true if this %time is after the current %time (agnostic of the date). */
	[[nodiscard]] bool isInFuture() const noexcept;

	/** Returns this Time represented as a string.
		The format of the string is \c "HH:MM:SS", suffixed with "AM" or "PM" if as24HourTime is false.
	 */
	[[nodiscard]] std::string toString (bool as24HourTime = true) const;

	/** Returns a Time object representing the current %time. */
	[[nodiscard]] static Time getCurrent();

	/** Returns a Time object representing the %time this code was compiled. */
	[[nodiscard]] LIMES_PURE_FUNCTION static Time getCompilationTime() noexcept;

	/** @name Protobuf access */
	///@{
	/** Returns the underlying Protobuf-generated object that holds this class's data and is used for serialization. */
	InternalData& getProtobufObject() noexcept { return internal_data; }

	const InternalData& getProtobufObject() const noexcept { return internal_data; }
	///@}

private:

	InternalData internal_data;
};

}  // namespace time

LIMES_END_NAMESPACE
