---
name: Create release

# yamllint disable rule:line-length

on:
    workflow_dispatch:
    push:
        branches:
            - main
    schedule:
        - cron: 0 0 * * 1

defaults:
    run:
        shell: bash

jobs:

    BuildWindowsClang:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            os: windows-latest
            c_compiler: clang
            cxx_compiler: clang++
            id_key: WindowsClang


    BuildWindowsMSVC:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            os: windows-latest
            cmake_generator: Visual Studio 17 2022
            id_key: WindowsMSVC


    BuildLinuxClang:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            os: ubuntu-latest
            c_compiler: clang
            cxx_compiler: clang++
            id_key: LinuxClang


    BuildLinuxGCC:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            os: ubuntu-latest
            c_compiler: gcc-10
            cxx_compiler: g++-10
            id_key: LinuxGCC


    BuildMacGCC:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            os: macos-latest
            c_compiler: gcc-10
            cxx_compiler: g++-10
            id_key: MacGCC


    BuildMacXcode:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            os: macos-latest
            cmake_generator: Xcode
            id_key: MacXcode


    Build_iOS:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            cmake_preset: iOS
            cmake_generator: Xcode
            id_key: iOS
            os: macos-latest


    Build_tvOS:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            cmake_preset: tvOS
            cmake_generator: Xcode
            id_key: tvOS
            os: macos-latest


    Build_watchOS:
        uses: ./.github/workflows/run_build.yml
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        with:
            cmake_preset: watchOS
            cmake_generator: Xcode
            id_key: watchOS
            os: macos-latest


    Release:

        name: Create release
        runs-on: ubuntu-latest
        needs: [BuildWindowsClang, BuildWindowsMSVC, BuildLinuxClang, BuildLinuxGCC, BuildMacGCC, BuildMacXcode, Build_iOS, Build_tvOS, Build_watchOS]
        timeout-minutes: 20

        steps:

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3.1.1
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm install

            - name: Install dependencies
              run: pip install --upgrade bumpversion

            - name: Download artefacts
              uses: actions/download-artifact@v3
              with:
                  path: '${{ github.workspace }}/stage'

            - name: Zip WindowsClang
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/WindowsClang.debug' '${{ github.workspace }}/stage/WindowsClang.release' '${{ github.workspace }}/deploy/WindowsClang'
                  cmake -E tar cvz WindowsClang.zip '${{ github.workspace }}/deploy/WindowsClang'

            - name: Zip WindowsMSVC
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/WindowsMSVC.debug' '${{ github.workspace }}/stage/WindowsMSVC.release' '${{ github.workspace }}/deploy/WindowsMSVC'
                  cmake -E tar cvz WindowsMSVC.zip '${{ github.workspace }}/deploy/WindowsMSVC'

            - name: Zip LinuxClang
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/LinuxClang.debug' '${{ github.workspace }}/stage/LinuxClang.release' '${{ github.workspace }}/deploy/LinuxClang'
                  cmake -E tar cvz LinuxClang.zip '${{ github.workspace }}/deploy/LinuxClang'

            - name: Zip LinuxGCC
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/LinuxGCC.debug' '${{ github.workspace }}/stage/LinuxGCC.release' '${{ github.workspace }}/deploy/LinuxGCC'
                  cmake -E tar cvz LinuxGCC.zip '${{ github.workspace }}/deploy/LinuxGCC'

            - name: Zip MacGCC
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/MacGCC.debug' '${{ github.workspace }}/stage/MacGCC.release' '${{ github.workspace }}/deploy/MacGCC'
                  cmake -E tar cvz MacGCC.zip '${{ github.workspace }}/deploy/MacGCC'

            - name: Zip MacXcode
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/MacXcode.debug' '${{ github.workspace }}/stage/MacXcode.release' '${{ github.workspace }}/deploy/MacXcode'
                  cmake -E tar cvz MacXcode.zip '${{ github.workspace }}/deploy/MacXcode'

            - name: Zip iOS
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/iOS.debug' '${{ github.workspace }}/stage/iOS.release' '${{ github.workspace }}/deploy/iOS'
                  cmake -E tar cvz iOS.zip '${{ github.workspace }}/deploy/iOS'

            - name: Zip tvOS
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/tvOS.debug' '${{ github.workspace }}/stage/tvOS.release' '${{ github.workspace }}/deploy/tvOS'
                  cmake -E tar cvz tvOS.zip '${{ github.workspace }}/deploy/tvOS'

            - name: Zip watchOS
              run: |
                  cmake -E copy_directory '${{ github.workspace }}/stage/watchOS.debug' '${{ github.workspace }}/stage/watchOS.release' '${{ github.workspace }}/deploy/watchOS'
                  cmake -E tar cvz watchOS.zip '${{ github.workspace }}/deploy/watchOS'

            - name: Run semantic release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
