---
name: Create release

on:
    workflow_dispatch:
    push:
        branches:
            - main
    schedule:
        - cron: 0 0 * * 1

defaults:
    run:
        shell: bash

jobs:

    Build:

        name: ${{ matrix.os }} - ${{ matrix.cmake_generator }} - ${{ matrix.compiler }} # yamllint disable-line
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ${{ matrix.os }}
        timeout-minutes: 120
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                cmake_generator: [Ninja]
                compiler: [GCC, clang]
                include:
                    - os: windows-latest
                      cmake_generator: Visual Studio 17 2022
                      compiler: MSVC
                    - os: macos-latest
                      cmake_generator: Xcode
                      compiler: AppleClang

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 1

            - name: Set up cache
              uses: actions/cache@v3
              with:
                  path: Cache
                  key: ${{ runner.os }}.${{ matrix.cmake_generator }}.test.${{ hashFiles('**/') }} # yamllint disable-line
                  restore-keys: ${{ runner.os }}.${{ matrix.cmake_generator }}.test. # yamllint disable-line

            - name: Install dependencies
              if: ${{ matrix.cmake_generator == 'Ninja' }}
              uses: seanmiddleditch/gha-setup-ninja@v3

            - name: Set compiler
              if: ${{ matrix.cmake_generator == 'Ninja' && matrix.compiler == GCC }} # yamllint disable-line
              run: |
                  echo "CC=gcc-10" >> $GITHUB_ENV \
                  echo "CXX=g++-10" >> $GITHUB_ENV

            - name: Set compiler
              if: ${{ matrix.cmake_generator == 'Ninja' && matrix.compiler == clang }} # yamllint disable-line
              run: |
                  echo "CC=clang" >> $GITHUB_ENV \
                  echo "CXX=clang++" >> $GITHUB_ENV

            - name: Run CMake
              run: cmake --preset default -G '${{ matrix.cmake_generator }}'

            - name: Run build
              run: cmake --build --preset default


    Release:

        name: Create release
        runs-on: ubuntu-latest
        needs: Build

        steps:

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3.1.1
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm install

            - name: Install dependencies
              run: pip install --upgrade bumpversion

            - name: Run semantic release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
